#!/bin/sh -e

if [ "$1" = "" ] ; then
   echo >&2 "Usage: $0 config_directory"
   exit 1
fi

sudo cp $1/interfaces /etc/network/interfaces && \
sudo mkdir -p /etc/nornet && \
sudo cp $1/nornetapi-config /etc/nornet

if [ -e /etc/init.d/nornet-tunnelbox ] ; then
   echo "Reconfiguring Tunnelbox ..."
   sudo service nornet-tunnelbox configure
elif [ -e /etc/init.d/nornet-node ] ; then
   echo "Reconfiguring Node ..."
   sudo service nornet-node configure
fi
