#!/usr/bin/env bash

ISO_DIRECTORY="$HOME/ISOs"
ISOs=`find $ISO_DIRECTORY -name *test*.iso`

VM_DISK=200
VM_MEMORY=1536
VM_DISK_TYPE=Standard

for iso in $ISOs ;do
   echo "##### $iso #####"

   name=`echo "$iso" | sed -e "s/.*\///g" -e "s/-x86_64-.*\.iso$//g" -e "s/.iso$//g"`
   site=`echo "$name" | sed -e "s/\.test-x86_64.*$//g" -e "s/\.test$//g" -e "s/^.*\.//g" -e "s/\b\(.\)/\u\1/g"`
   net="TestNetwork-${site}"
   vm="TEST-${site}-${name}"
   echo "====== Create: $vm -> $name in network $net ======"

   
   ../Make-Research-VM "$vm" "$iso" $VM_MEMORY $VM_DISK $VM_DISK_TYPE
   VBoxManage modifyvm "$vm" --nic1 intnet --intnet1 "$net"
done
