#!/bin/bash

ISO_DIRECTORY="$HOME/Downloads"
ISOs=`find $ISO_DIRECTORY -name *test.iso`

VM_DISK=200
VM_MEMORY=768
VM_DISK_TYPE=Standard

for iso in $ISOs ;do
   echo "##### $iso #####"

   name=`echo "$iso" | sed -e "s/.*\///g" -e "s/.iso$//g"`

   ../Make-Research-VM $name $iso $VM_MEMORY $VM_DISK $VM_DISK_TYPE
done
