#!/bin/bash -e

if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 [users_csv_file]"
   echo >&2 "users_csv_file is a TAB-separated participant list!"
   exit 1
fi

USERS_CSVFILE="$1"
ACCOUNTS="accounts.txt"
PWDLEN=8


echo "Converting $USERS_CSVFILE to $ACCOUNTS ..."

IFS=$'\t'
(
   while read number gname fname uname a b c d e f ; do
      if [[ "$number"  =~ ^[0-9]+$ ]] ; then
         uname=`echo "$uname" | sed -e "s/ø/oe/g" -e "s/Ø/OE/g" -e "s/æ/ae/g" -e "s/Æ/AE/g"  -e "s/å/AA/g" -e "s/Å/AA/g" | iconv -f utf-8 -t ascii//translit | tr "A-Z" "a-z" | tr -d " "`
         hash=`echo $uname | md5sum | sed -e "s/[^a-f0-9].*$//g"`
         eval "let number_$hash=\$number_$hash+1"
         
         number_name="\$number_$hash"
         eval "n=$number_name"
         
         passwd=`< /dev/urandom tr -dc _A-Z-a-z-0-9%.$ | head -c$PWDLEN`
         echo -e "$number\t$uname$n\t$passwd\t$gname\t$fname"
      fi
   done
) <$USERS_CSVFILE >$ACCOUNTS
