#!/bin/bash -e

ACCOUNTS="accounts.txt"


IFS=$'\t'
(
   while read number uname passwd gname fname a b c d e f ; do
      if [[ "$number"  =~ ^[0-9]+$ ]] ; then
         echo -e "\x1b[34mRemoving $uname ($gname $fname) ...\x1b[0m"
         if [ "$uname" = "root" -o "$uname" = "nornetpp" -o "$uname" = "dreibh" ] ; then
            echo >&2 "ERROR: Trying to remove protected user $uname!"
            exit 1
         fi
         deluser $uname || true
         rm -rf /home/$uname
      fi
   done
) <$ACCOUNTS
