#!/bin/bash -e
#
# Get URLs from Web-Checker output
# Copyright (C) 2015 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


if [ $# -ne 1 ] ; then
   echo >&2 "Usage: $0 log_file"
   exit 1
fi

LOG_FILE="$1"

# Show errors
(
 grep "^Real URL"  "$LOG_FILE" | sed -e "s/^Real URL[ \t]*//g"  | sort -u
 grep "^webcheck:" "$LOG_FILE" | sed -e "s/^webcheck:[ \t]*//g" | sort -u
) | grep "^http"
