#!/usr/bin/env bash
#
# TLS configuration helper script
# Copyright (C) 2012-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no
#

cat >ciphers.txt <<EOF

# ------ TLS 1.2 ------------------------------------------
ECDHE-ECDSA-AES256-GCM-SHA384
ECDH-ECDSA-AES256-GCM-SHA384
ECDHE-RSA-AES256-GCM-SHA384
ECDH-RSA-AES256-GCM-SHA384

ECDHE-ECDSA-AES256-SHA384
ECDH-ECDSA-AES256-SHA384
ECDHE-RSA-AES256-SHA384
ECDH-RSA-AES256-SHA384

# Need DH parameter to increase key size (Apache 2.4.7+)!
# DHE-RSA-AES256-GCM-SHA384
# DHE-DSS-AES256-GCM-SHA384

# No forward security!
# AES256-GCM-SHA384

# ------ TLS 1.0 ------------------------------------------
ECDHE-ECDSA-AES256-SHA
ECDH-ECDSA-AES256-SHA
ECDHE-RSA-AES256-SHA
ECDH-RSA-AES256-SHA

# Need DH parameter to increase key size (Apache 2.4.7+)!
# DHE-RSA-AES256-SHA
# DHE-DSS-AES256-SHA

# No forward security! FALLBACK for old browsers!
AES256-SHA

EOF

echo -en "SSLCipherSuite "
cat ciphers.txt | sed -e "/^#/d" -e "/^[ \t]*$/d" | tr '\n' ':' | sed -e "s/:$//g"
echo ""
echo ""

cat ciphers.txt | sed -e "/^#/d" -e "/^[ \t]*$/d" | (
   while read x ; do
      openssl ciphers -v "$x" || echo "BAD!"
   done
)
