#!/bin/bash

PREFIX="$1"
if [ "$PREFIX" = "" ] ; then
   echo >&2 "Usage: $0 file_name_prefix"
   exit 1
fi

KEYLEN=8192

# Create key and certificate (CRT)
openssl req -config nntb.config -x509 -nodes -days 380 -newkey rsa:$KEYLEN -sha512 -keyout "$PREFIX.key" -out "$PREFIX.crt"
openssl x509 -noout -text -in "$PREFIX.crt"

# Create certificate signing request (CSR)
openssl req -config nntb.config -new -key "$PREFIX.key" -out "$PREFIX.csr"
openssl req -noout -text -in "$PREFIX.csr"
