#!/bin/bash

PREFIX="$1"
if [ "$PREFIX" = "" ] ; then
   echo >&2 "Usage: $0 file_name_prefix"
   exit 1
fi

openssl req -x509 -nodes -newkey rsa:8192 -sha512 -keyout "$PREFIX.key" -out "$PREFIX.crt"
