#!/bin/bash -e
#
# Get urls from Link-Checker output
# Copyright (C) 2013 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

BROWSER="/usr/bin/firefox"
BROWSERARGS="-new-instance"
PREFIX="http://web.archive.org/save/"

MAXTABS=100
RESTARTDELAY=60

if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 delay [skip]"
   exit 1
fi
DELAY="$1"
SKIP="0$2"
if [ $DELAY -lt 1 ] ; then
   DELAY=30
fi


echo "Starting ..."
$BROWSER $BROWSERARGS >/dev/null 2>&1 &
pid=$!
sleep 10


n=1
while read url ; do

   if [ $n -lt $SKIP ] ; then
      echo "$n: SKIPPING $PREFIX$url ..."
   else
      let "m=$n % $MAXTABS" || true
      if [ $m -eq 0 ] ; then
         echo "Waiting ..."
         sleep $RESTARTDELAY
         echo "Stopping ..."
         kill $pid >/dev/null 2>&1 || true
         i=0
         while [ $i -lt $RESTARTDELAY ] ; do
            if ! ps -p $pid >/dev/null 2>&1 ; then
               break
            fi
            sleep 1
            let i=$i+1
         done
         killall -KILL $BROWSER >/dev/null 2>&1 || true
         echo "Restarting ..."
         $BROWSER $BROWSERARGS >/dev/null 2>&1 &
         pid=$!
         sleep $RESTARTDELAY
      fi
      
      echo "$n: Opening $PREFIX$url ..."
      $BROWSER -new-tab "$PREFIX$url" >/dev/null 2>&1

      if [ "$1" != "" ] ; then
         # echo "Waiting $DELAY seconds ..."
         sleep "$DELAY"
      fi
   fi
   let n=$n+1 || true

done
