#!/bin/bash -e
#
# Get URLs from Link-Checker output
# Copyright (C) 2013 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

BROWSER="firefox"
PREFIX="https://web.archive.org/save/"

if [ $# -lt 2 ] ; then
   echo >&2 "Usage: $0 delay url ..."
   exit 1
fi
DELAY="$1"
if [ $DELAY -lt 1 ] ; then
   DELAY=30
fi
shift


while [ "$1" != "" ] ; do
   URL="$1"
   shift

   echo "Opening $PREFIX$URL ..."
   $BROWSER "$PREFIX$URL"

   if [ "$1" != "" ] ; then
      echo "Waiting $DELAY seconds ..."
      sleep "$DELAY"
   fi
done


done
