#!/usr/bin/env bash
#
# TLS configuration helper script
# Copyright (C) 2017-2019 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no
#

# Bash options:
set -e

if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 file_name_prefix"
   exit 1
fi
PREFIX="$1"

sudo letsencrypt certonly --authenticator manual --server https://acme-v01.api.letsencrypt.org/directory --text --email dreibh@simula.no --csr $1.csr
