#!/bin/sh -e

PACKAGES=""
if [ "$1" = "node" ] ; then
   PACKAGES="nornet-api nornet-routing nornet-management nornet-node"
elif [ "$1" = "tunnelbox" ] ; then
   PACKAGES="nornet-api nornet-routing nornet-management nornet-node nornet-tunnelbox"
elif [ "$1" = "monitor" ] ; then
   PACKAGES="nornet-api nornet-routing nornet-management nornet-node nornet-monitor"
else
   echo >&2 "Usage: $0 [tunnelbox|node|monitor]"
   exit 1
fi

sudo rm -f /var/cache/pbuilder/result/*
./build-deb

for package in $PACKAGES ; do
   echo "Purging ${package} ..."
   sudo dpkg -P ${package} || true
done

for package in $PACKAGES ; do
   echo "Installing ${package} ..."
   sudo dpkg -i /var/cache/pbuilder/result/${package}*.deb
done
