#!/bin/sh -e

. ./debian.conf


CHANGELOG_HEADER="`head -n1 debian/changelog`"
PACKAGE=`echo $CHANGELOG_HEADER | sed -e "s/(.*//" -e "s/ //g"`
UPSTREAM_VERSION=`echo $CHANGELOG_HEADER | sed -e "s/[a-zA-Z0-9 ]*(//" -e "s/).*//" -e "s/[0-9]*$//" -e "s/ //g" -e "s/^[0-9]*://" -e "s/-[^ ]*$//g"`

echo "######################################################################"
echo "CHANGELOG_HEADER:   $CHANGELOG_HEADER"
echo "PACKAGE:            $PACKAGE"
echo "UPSTREAM_VERSION:   $UPSTREAM_VERSION"
echo "######################################################################"


if [ -e $PACKAGE-$UPSTREAM_VERSION ] ; then
   rm -rf $PACKAGE-$UPSTREAM_VERSION
fi
mkdir $PACKAGE-$UPSTREAM_VERSION || exit 1


# ---------------------------------------------------------
mkdir $PACKAGE-$UPSTREAM_VERSION/src
cp NEWS README BUGS COPYING ChangeLog *.lsm $PACKAGE-$UPSTREAM_VERSION
cp src/*.py $PACKAGE-$UPSTREAM_VERSION
cp src/*.[0-9] $PACKAGE-$UPSTREAM_VERSION
cp src/*-config $PACKAGE-$UPSTREAM_VERSION
cp src/*-constants $PACKAGE-$UPSTREAM_VERSION
cp src/*-authorized_keys $PACKAGE-$UPSTREAM_VERSION
cp src/*-config.example $PACKAGE-$UPSTREAM_VERSION
cp src/rt_tables.example $PACKAGE-$UPSTREAM_VERSION

cp src/Random-Sleep $PACKAGE-$UPSTREAM_VERSION
cp src/Tunnelbox-Setup $PACKAGE-$UPSTREAM_VERSION
cp src/Probe-Interface-Setup $PACKAGE-$UPSTREAM_VERSION
cp src/Probe-Endpoint-Setup $PACKAGE-$UPSTREAM_VERSION
cp src/Watchdog $PACKAGE-$UPSTREAM_VERSION
cp src/Server-Watchdog $PACKAGE-$UPSTREAM_VERSION
cp src/System-Backup $PACKAGE-$UPSTREAM_VERSION
cp src/System-Info $PACKAGE-$UPSTREAM_VERSION
cp src/System-Maintenance $PACKAGE-$UPSTREAM_VERSION
cp src/Start-VSystem $PACKAGE-$UPSTREAM_VERSION
cp src/Stop-VSystem $PACKAGE-$UPSTREAM_VERSION
cp src/Check-VSystem $PACKAGE-$UPSTREAM_VERSION
cp src/Show-VSystems $PACKAGE-$UPSTREAM_VERSION
cp src/Make-VSystem-Template $PACKAGE-$UPSTREAM_VERSION
cp src/Backup-VSystem $PACKAGE-$UPSTREAM_VERSION
cp src/Reset-VSystem $PACKAGE-$UPSTREAM_VERSION
cp src/Backup-All-VSystems $PACKAGE-$UPSTREAM_VERSION
cp src/Auto-Update-BootCD $PACKAGE-$UPSTREAM_VERSION
cp src/Auto-Update-Keys $PACKAGE-$UPSTREAM_VERSION
cp src/Change-VSystem-CDImage $PACKAGE-$UPSTREAM_VERSION
cp src/check_* $PACKAGE-$UPSTREAM_VERSION
cp src/Make-*-Configuration $PACKAGE-$UPSTREAM_VERSION
cp src/Tunnelbox-NAT-Helper $PACKAGE-$UPSTREAM_VERSION
cp src/Tunnelbox-Bootstrap-Helper $PACKAGE-$UPSTREAM_VERSION
cp src/Interface-Setup $PACKAGE-$UPSTREAM_VERSION
cp src/Server-Setup $PACKAGE-$UPSTREAM_VERSION
cp src/Convert-HDD-Images $PACKAGE-$UPSTREAM_VERSION
cp src/Reset-Networking $PACKAGE-$UPSTREAM_VERSION
cp src/Check-Research-Node $PACKAGE-$UPSTREAM_VERSION

echo "NorNet $UPSTREAM_VERSION, packaged `env LANG=en date`" >$PACKAGE-$UPSTREAM_VERSION/nornet-version

mkdir $PACKAGE-$UPSTREAM_VERSION/cron-apt
cp src/cron-apt/5-install $PACKAGE-$UPSTREAM_VERSION/cron-apt/

mkdir $PACKAGE-$UPSTREAM_VERSION/background
cp src/background/*.png $PACKAGE-$UPSTREAM_VERSION/background/

mkdir $PACKAGE-$UPSTREAM_VERSION/grub
cp src/grub/*_theme $PACKAGE-$UPSTREAM_VERSION/grub/
cp src/grub/grub-defaults $PACKAGE-$UPSTREAM_VERSION/grub/
convert -background Gold -fill "#02266b" -font Helvetica-Bold -pointsize 24 -gravity Center -size 1024x42 caption:"`cat $PACKAGE-$UPSTREAM_VERSION/nornet-version`" "$PACKAGE-$UPSTREAM_VERSION/grub/caption.png"
splashImages=`find src/grub/ -name '*.jpeg' -printf '%f '`
for splashImage in $splashImages ; do
   bgSize=`identify -format '%wx%h' "src/grub/$splashImage"`
   convert -size "$bgSize" -composite -gravity South \
   "src/grub/$splashImage" \
   "$PACKAGE-$UPSTREAM_VERSION/grub/caption.png" \
   "$PACKAGE-$UPSTREAM_VERSION/grub/$splashImage"

   # cp "$PACKAGE-$UPSTREAM_VERSION/grub/caption.png" "$PACKAGE-$UPSTREAM_VERSION/grub/$splashImage" /tmp/x0/
done
rm -f "$PACKAGE-$UPSTREAM_VERSION/grub/caption.png"

mkdir $PACKAGE-$UPSTREAM_VERSION/pbuilder
cp src/pbuilder/pbuilderrc $PACKAGE-$UPSTREAM_VERSION/pbuilder/

mkdir $PACKAGE-$UPSTREAM_VERSION/vsystems
cp src/vsystems/EXAMPLE-* $PACKAGE-$UPSTREAM_VERSION/vsystems/

mkdir $PACKAGE-$UPSTREAM_VERSION/Kontrollsenter
cp src/Kontrollsenter/NorNet-*.css src/Kontrollsenter/NorNet-*.js src/Kontrollsenter/NorNet-*.php src/Kontrollsenter/NorNet-*.html src/Kontrollsenter/Forward-*.html $PACKAGE-$UPSTREAM_VERSION/Kontrollsenter

mkdir $PACKAGE-$UPSTREAM_VERSION/Monitor
cp src/Monitor/*.cfg $PACKAGE-$UPSTREAM_VERSION/Monitor/

mkdir $PACKAGE-$UPSTREAM_VERSION/WebServer
cp src/WebServer/000-default $PACKAGE-$UPSTREAM_VERSION/WebServer/
cp src/WebServer/make-certificate $PACKAGE-$UPSTREAM_VERSION/WebServer/
cp src/WebServer/make-cipher-suites $PACKAGE-$UPSTREAM_VERSION/WebServer/
cp src/WebServer/favicon.ico $PACKAGE-$UPSTREAM_VERSION/WebServer/
cp src/WebServer/nntb.config $PACKAGE-$UPSTREAM_VERSION/WebServer/

mkdir $PACKAGE-$UPSTREAM_VERSION/Kontrollsenter/Clock
mkdir $PACKAGE-$UPSTREAM_VERSION/Kontrollsenter/Graphics
mkdir $PACKAGE-$UPSTREAM_VERSION/Kontrollsenter/Graphics/Backgrounds
mkdir $PACKAGE-$UPSTREAM_VERSION/Kontrollsenter/Graphics/Control
mkdir $PACKAGE-$UPSTREAM_VERSION/Kontrollsenter/Graphics/Flags
mkdir $PACKAGE-$UPSTREAM_VERSION/Kontrollsenter/Graphics/Icons
mkdir $PACKAGE-$UPSTREAM_VERSION/Kontrollsenter/Graphics/Markers
mkdir $PACKAGE-$UPSTREAM_VERSION/Kontrollsenter/Graphics/Sites
cp -r src/Kontrollsenter/Graphics/Backgrounds/*.png $PACKAGE-$UPSTREAM_VERSION/Kontrollsenter/Graphics/Backgrounds/
cp -r src/Kontrollsenter/Graphics/Control/*.png $PACKAGE-$UPSTREAM_VERSION/Kontrollsenter/Graphics/Control/
cp -r src/Kontrollsenter/Graphics/Flags/*.png $PACKAGE-$UPSTREAM_VERSION/Kontrollsenter/Graphics/Flags/
cp -r src/Kontrollsenter/Graphics/Flags/*.svg $PACKAGE-$UPSTREAM_VERSION/Kontrollsenter/Graphics/Flags/
cp -r src/Kontrollsenter/Graphics/Icons/*.png $PACKAGE-$UPSTREAM_VERSION/Kontrollsenter/Graphics/Icons/
cp -r src/Kontrollsenter/Graphics/Markers/*.svg $PACKAGE-$UPSTREAM_VERSION/Kontrollsenter/Graphics/Markers/
cp -r src/Kontrollsenter/Graphics/Sites/*.jpeg $PACKAGE-$UPSTREAM_VERSION/Kontrollsenter/Graphics/Sites/
cp -r src/Kontrollsenter/Clock/station-clock.svg $PACKAGE-$UPSTREAM_VERSION/Kontrollsenter/Clock/
cp -r src/Kontrollsenter/Clock/License.pdf $PACKAGE-$UPSTREAM_VERSION/Kontrollsenter/Clock/
# ---------------------------------------------------------


tar czvf $PACKAGE-$UPSTREAM_VERSION.tar.gz $PACKAGE-$UPSTREAM_VERSION
rm -rf $PACKAGE-$UPSTREAM_VERSION
