#!/bin/sh -e

VERSION=0.1.0~alpha1.2

. ./debian.conf

CHANGELOG_HEADER="`head -n1 debian/changelog`"
PACKAGE=`echo $CHANGELOG_HEADER | sed -e "s/(.*//" -e "s/ //g"`

if [ -e $PACKAGE-$VERSION ] ; then
   rm -rf $PACKAGE-$VERSION
fi
mkdir $PACKAGE-$VERSION || exit 1


# ---------------------------------------------------------
mkdir $PACKAGE-$VERSION/src
cp NEWS README BUGS COPYING ChangeLog *.lsm $PACKAGE-$VERSION
cp src/*.py $PACKAGE-$VERSION
cp src/*.1 $PACKAGE-$VERSION
cp src/*-config $PACKAGE-$VERSION
cp src/Routing-Setup $PACKAGE-$VERSION
cp src/Tunnelbox-Setup $PACKAGE-$VERSION
cp src/Make-Tunnelbox-Configuration $PACKAGE-$VERSION
cp src/Reset-Networking $PACKAGE-$VERSION
# ---------------------------------------------------------


tar czvf $PACKAGE-$VERSION.tar.gz $PACKAGE-$VERSION
rm -rf $PACKAGE-$VERSION
