#!/bin/bash
#
# SED Script
# Copyright (C) 2002-2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de


# Usage example:
# find -type f -print0 | xargs -0 ./UpdateDocFiles

SED_FILE="UpdateDoc1.sed"

while [ $# -gt 0 ] ; do

   BASENAME=`basename "$1"`
   if [ "$BASENAME" == "${SED_FILE}" ] ; then
      echo "Skipping $1 (is input SED file)"
   elif [[ "$BASENAME" =~ \.(jpeg|jpg|JPG|png|PNG|svg|SVG)$ ]] ; then
      echo "Skipping $1 (is binary file)"
   elif [[ "$1" =~ ^.*/\.git/.*$ ]] ; then
      echo "Skipping $1 (is Git file)"
   else
      echo "Updating $1 ..."
      sed -f ${SED_FILE} -i "$1"
   fi

   shift
done
