#!/bin/bash -e


# ====== pbuilder ===========================================================
sudo pbuilder create --debootstrapopts --variant=buildd
sudo pbuilder login --save-after-login <<EOF
apt install -y software-properties-common
apt-add-repository -sy ppa:dreibh/ppa
apt-get update
EOF


# ====== pbuilder-dist ======================================================
# DISTRIBUTIONS="precise"   # trusty xenial bionic cosmic"
# ARCHITECTURES="amd64"
# 
# for distribution in $DISTRIBUTIONS ; do
#    for architecture in $ARCHITECTURES ; do
#       
#       pbuilder-dist $distribution $architecture create --debootstrapopts --variant=buildd
# 
#       pbuilder-dist $distribution $architecture login --save-after-login <<EOF
# apt install -y software-properties-common
# apt-add-repository -sy ppa:dreibh/ppa
# apt-get update
# EOF
# 
#     done
# done
