#!/bin/sh

if [ $# -lt 2 ] ; then
   echo >&2 "Usage: $0 delay_in_seconds controlvm_parameters ..."
   exit 1
fi
DELAY="$1"
shift

VMs=`VBoxManage list vms | sed -e "s/ {.*}$//g"`
for vm in $VMs ; do
   vm=`eval echo $vm`
   echo "Controlling $vm ($@) ..."

   vboxmanage controlvm "$vm" $@

   echo "Waiting $DELAY seconds ..."
   sleep $DELAY
done
