#!/usr/bin/env bash
#
# iLO Configuration Script
# Copyright (C) 2015-2023 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -e


# ====== Handle arguments ===================================================
INSTALL_TOOLS=0
REMOVE_TOOLS=0
while [ "$1" != "" ] ; do
   if [ "$1" = "-install-tools" ] ; then
      INSTALL_TOOLS=1
   elif [ "$1" = "-remove-tools" ] ; then
      REMOVE_TOOLS=1
   elif [ "$1" = "-install-and-remove-tools" -o "$1" = "-a" ] ; then
      INSTALL_TOOLS=1
      REMOVE_TOOLS=1
   else
      echo 2>&1 "Usage: $0 [-install-tools] [-remove-tools] [-install-and-remove-tools|-a]"
      exit 1
   fi
   shift
done

if [ ! -e ~/.ilo-key ] ; then
   echo >&2 "ERROR: ~/.ilo-key not found!"
   exit 1
fi

# ====== Download and install HP tools ======================================
if [ $INSTALL_TOOLS -eq 1 ] ; then
   echo -e "\x1b[34mInstalling hponcfg ...\x1b[0m"
   apt-get install -y libc6-i386 lib32gcc1 xsltproc
   mkdir -p $HOME/hp-tools
   cd $HOME/hp-tools
   TOOLS="cpqacuxe_9.40.2-2._amd64.deb hpssaducli-2.40-13.0_amd64.deb hp-health_10.60-1842.10_amd64.deb hponcfg_4.6.0.5-23._amd64.deb hpsmh_7.6.1-9.1-1._amd64.deb"
   for tool in $TOOLS ; do
      if [ ! -e $tool ] ; then
         wget "https://downloads.linux.HPE.com/SDR/repo/mcp/ubuntu/pool/non-free/$tool"
      fi
   done
   dpkg -i $TOOLS
fi

if [ ! -e /usr/sbin/hponcfg ] ; then
   echo >&2 "ERROR: Cannot find /usr/sbin/hponcfg!"
   echo "Use $0 -install-tools to install it."
   exit 1
fi


# ====== Generate network configuration for iLO system ======================
NODE_FQDN=`hostname --fqdn`
NODE_HOSTNAME=`echo "$NODE_FQDN" | sed -e "s/^\([a-zA-Z0-9]*\)\.\([a-zA-Z0-9\.\-]*\)$/ilo-\1/g"`
NODE_DOMAINNAME=`echo "$NODE_FQDN" | sed -e "s/^\([a-zA-Z0-9]*\)\.\([a-zA-Z0-9\.\-]*\)$/\2/g"`

NODE_ADDRESS=`host "$NODE_HOSTNAME.$NODE_DOMAINNAME" | awk '/^[a-zA-Z0-9.-]+ has address/ { print $4 }'`
NODE_NETMASK="255.255.255.0"
NODE_TUNNELBOX=`echo "$NODE_ADDRESS" | sed -e 's/^\([0-9]*\.[0-9]*\.[0-9]*\)\.[0-9]*$/\1.1/g'`

SNMP_ADDRESS="10.1.1.3"   # !!! Update if necessary !!!


echo -e "\x1b[34mNew iLO settings from hostname:"
echo "NODE_HOSTNAME=$NODE_HOSTNAME"
echo "NODE_DOMAINNAME=$NODE_DOMAINNAME"
echo "NODE_ADDRESS=$NODE_ADDRESS"
echo "NODE_NETMASK=$NODE_NETMASK"
echo "NODE_TUNNELBOX=$NODE_TUNNELBOX"
echo -en "\x1b[0m"

if [ "$NODE_ADDRESS" = "" ] ; then
   echo 2>&1 "ERROR: Unable to determine IP address of $NODE_FQDN! Is DNS properly configured?"
   exit 1
fi


# ====== Obtain old iLO configuration and generate new one ==================
# Documentation: https://support.hpe.com/hpsc/doc/public/display?docId=emr_na-c03351064

NEW_SETTINGS_CONFIGURATION=/root/settings.xml
OLD_ILO_CONFIGURATION=/root/old-ilo-configuration.xml
NEW_ILO_CONFIGURATION=/root/new-ilo-configuration.xml

cat >$NEW_SETTINGS_CONFIGURATION <<EOF
<RIBCL VERSION="2.0">
  <LOGIN USER_LOGIN="Administrator" PASSWORD="password">
  <RIB_INFO MODE="write">
    <MOD_SNMP_IM_SETTINGS>
       <SNMP_ADDRESS_1 VALUE="$SNMP_ADDRESS"/>
       <RIB_TRAPS VALUE="Y"/>
    </MOD_SNMP_IM_SETTINGS>
    <MOD_GLOBAL_SETTINGS>
     <TELNET_ENABLE VALUE="N"/>
     <ENFORCE_AES VALUE="Y"/>
     <ENHANCED_CLI_PROMPT_ENABLE VALUE = "Yes"/>
    </MOD_GLOBAL_SETTINGS>
    <LICENSE>
     <ACTIVATE KEY="`cat ~/.ilo-key | tr -d '-'`"/>
    </LICENSE>
    <IMPORT_SSH_KEY>
-----BEGIN SSH KEY-----
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDODvIna1FXADBFU+8gnH7PrSYI0t/jMlNg84whF4ACMCMtqxt+xTVNTEwRxlfKf+3YsurgjAdYHxaNYj94bUEZEM1shNAqyLUJXwFo3DryyQUbkaFnzmC8pz806Sn1rwLPiqqUcxjSnFKKZgxAS/HmX041BrPippP7ezANboiY2Q= Administrator
-----END SSH KEY-----
    </IMPORT_SSH_KEY>
    <CSR_CERT_SETTINGS>
     <CSR_USE_CERT_CUSTOM_SUBJECT VALUE = "No"/>
     <CSR_USE_CERT_2048PKEY VALUE = "Yes" />
     <CSR_USE_CERT_FQDN VALUE = "Yes" />
     <CSR_SUBJECT_COUNTRY VALUE ="NO"/>
     <CSR_SUBJECT_STATE VALUE ="Akershus"/>
     <CSR_SUBJECT_LOCATION VALUE ="Fornebu"/>
     <CSR_SUBJECT_ORG_NAME VALUE ="Simula Research Laboratory"/>
     <CSR_SUBJECT_ORGUNIT_NAME VALUE ="Centre for Resilient Networks and Applications"/>
     <CSR_SUBJECT_COMMON_NAME VALUE ="$NODE_FQDN"/>
   </CSR_CERT_SETTINGS>
  </RIB_INFO>
  <SERVER_INFO mode="write"><SERVER_AUTO_PWR VALUE="30"/></SERVER_INFO>
  </LOGIN>
</RIBCL>
EOF

hponcfg -w $OLD_ILO_CONFIGURATION
sed \
   -e "s/^\(.*<DHCP_ENABLE VALUE = \"\).*\(\"\/>\)$/\1N\2/g" \
   -e "s/^\(.*<REG_WINS_SERVER VALUE = \"\).*\(\"\/>\)$/\1N\2/g" \
   -e "s/^\(.*<IP_ADDRESS VALUE = \"\).*\(\"\/>\)$/\1$NODE_ADDRESS\2/g" \
   -e "s/^\(.*<SUBNET_MASK VALUE = \"\).*\(\"\/>\)$/\1$NODE_NETMASK\2/g" \
   -e "s/^\(.*<GATEWAY_IP_ADDRESS VALUE = \"\).*\(\"\/>\)$/\1$NODE_TUNNELBOX\2/g" \
   -e "s/^\(.*<PRIM_DNS_SERVER VALUE = \"\).*\(\"\/>\)$/\1$NODE_TUNNELBOX\2/g" \
   -e "s/^\(.*<GATEWAY_IP_ADDRESS VALUE = \"\).*\(\"\/>\)$/\1$NODE_TUNNELBOX\2/g" \
   -e "s/^\(.*<DNS_NAME VALUE = \"\).*\(\"\/>\)$/\1$NODE_HOSTNAME\2/g" \
   -e "s/^\(.*<DOMAIN_NAME VALUE = \"\).*\(\"\/>\)$/\1$NODE_DOMAINNAME\2/g" \
   < $OLD_ILO_CONFIGURATION >$NEW_ILO_CONFIGURATION


# ====== Check and apply changes ============================================
echo -e "\x1b[34mSettings difference to running configuration:\x1b[0m"
colordiff $OLD_ILO_CONFIGURATION $NEW_ILO_CONFIGURATION || true
echo "SNMP_ADDRESS=$SNMP_ADDRESS"

echo -en "\x1b[33mApply changes to iLO configuration?\x1b[0m [yes/no]? "
read -er applyChanges
if [ "$applyChanges" != "yes" -a "$applyChanges" != "y" ] ; then
   echo "Skipped!"
else
   hponcfg -r
   hponcfg -f $NEW_ILO_CONFIGURATION
   hponcfg -f $NEW_SETTINGS_CONFIGURATION
   hponcfg -b
fi


# ====== Remove HP tools ====================================================
if [ $REMOVE_TOOLS -eq 1 ] ; then
   echo -e "\x1b[34mRemoving hponcfg ...\x1b[0m"
   dpkg -P cpqacuxe hp-health hponcfg hpsmh hpssaducli
   apt-get remove -y lib32gcc1 xsltproc
   apt-get autoremove -y
   rm -rf /opt/hp /var/spool/hp-health

   rm -f $NEW_SETTINGS_CONFIGURATION $OLD_ILO_CONFIGURATION $NEW_ILO_CONFIGURATION
fi
