#!/bin/bash

FROM=vdi
TO=qcow2

inputImages=`find . -name "*.${FROM}" | sort`

for inputImage in ${inputImages} ; do
   outputImage=`echo "${inputImage}" | sed -e "s/${FROM}$/${TO}/g"`
   echo "Converting ${inputImage} from $FROM to $TO ..."
   if [ ! -e "${outputImage}" ] ; then
      qemu-img convert -p "${inputImage}" -O $TO "${outputImage}"
   else
      echo >&2 "ERROR: ${outputImage} already exists!"
   fi
done
