#!/bin/bash

NEW="4.1.35-888.fc23"
OLD="4.1.27-888.fc23"

while [ $# -gt 0 ] ; do
   echo "Handling $1 ..."
   (
      #echo "service nm restart"
      #echo "NodeUpdate.py"
      #echo "uname -a"
      #echo "yum clean all"
      #echo "NodeUpdate.py"

      cat <<EOF
      NodeUpdate.py

      dnf install -y kernel-core-$NEW.x86_64 kernel-$NEW.x86_64 kernel-modules-$NEW.x86_64 kernel-modules-extra-$NEW.x86_64

      kernel=\$(uname -r)
      echo "K=\$kernel"
      if [ -e "/boot/vmlinuz-$NEW.x86_64" ] ; then
         if [ "\$kernel" = "$OLD.x86_64" ] ; then
            echo "OLD KERNEL -> Reboot!"
            rpm -ehv kernel-core-$OLD.x86_64 kernel-$OLD.x86_64 kernel-modules-$OLD.x86_64 kernel-modules-extra-$OLD.x86_64
            reboot
         else
            echo "Different kernel!"
            rpm -ehv kernel-core-$OLD.x86_64 kernel-$OLD.x86_64 kernel-modules-$OLD.x86_64 kernel-modules-extra-$OLD.x86_64
         fi
      fi
      echo "NodeUpdate.py"
EOF

   ) | sudo ssh -4 -o StrictHostKeyChecking=no -i /etc/planetlab/root_ssh_key.rsa root@$1 &
   shift
done
wait
