#!/bin/bash
#
# iLO Identification Script
# Copyright (C) 2018 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


printf "%-24s\t%-16s\t%-20s\t%s\n" "FQDN" "Host" "Domain" "SerialNo"
(
   while [ $# -gt 0 ] ; do
      fqdn="$1"
      shift
      (
         host=`echo "$fqdn" | sed -e "s/^\([a-zA-Z0-9-]*\)\(.*\)$/\1/g"`
         domain=`echo "$fqdn" | sed -e "s/^\([a-zA-Z0-9-]*\.\)\(.*\)$/\2/g"`
#          wget -q --no-check-certificate -O$fqdn.out "https://$fqdn/xmldata?item=all"
         sbsn=`xml_grep "SBSN" $fqdn.out --text_only`
         printf "%-24s\t%-16s\t%-20s\t%s\n" "$fqdn" "$host" $domain "$sbsn"
      ) &
      wait
   done
) | sort -k2

