#!/usr/bin/env bash
#
# System Maintenance
# Copyright (C) 2013-2021 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -e


# ###### Perform Python package upgrades with PIP ###########################
run-upgrade ()
{
   local sudo=""
   if [ "$1" != "" ] ; then
      sudo="$1 "
   fi
   local options=" $2"

   local pip
   for pip in pip pip3 ; do
      # ====== Check for PIP ================================================
      if [ -x /usr/local/bin/${pip} ] ; then
         # Prefer to use PIP-installed version of PIP
         pipCommand=/usr/local/bin/${pip}
      elif [ -x /usr/bin/${pip} ] ; then
         # Otherwise, try OS-installed version of PIP
         pipCommand=/usr/bin/${pip}
      else
         # Not found -> nothing to do!
         continue
      fi


      # ====== Perform upgrades =============================================
      echo "Running PIP by using \"${sudo}${pipCommand} ...\""
      ${sudo} ${pipCommand} list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1 | xargs -r -- ${sudo} ${pipCommand} install --quiet --upgrade ${options} &
   done
}



# ###### Main program #######################################################

# ====== Run as superuser ===================================================
run-upgrade "sudo -H"

# ====== Run as user, if script is run as user ==============================
if [ "${SUDO_USER}" != "" -a "${SUDO_GID}" != "" ] ; then
   run-upgrade "sudo -u ${SUDO_USER} -g#${SUDO_GID}" --user
fi

wait
