#!/usr/bin/env bash

isp=1
site=1

i=1
while [ $i -lt 255 ] ; do

   address="10.$isp.$site.$i"
   name=`dig -x $address ptr +short | sed -e "s/\.$//g"`
   #status=`ping -c1 $address >/dev/null && echo "OK" || echo "BAD"`

   echo -e "$i\t$address\t$name\t$status"

   let i=$i+1
done
