#!/bin/bash -e
#
# Kernel Test Script
# Copyright (C) 2016 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

git clean -x -d -f
cp /home/dreibh/kernel-config .config
make-kpkg --rootcmd fakeroot clean
make-kpkg --rootcmd fakeroot \
   --stem linux \
   --initrd --overlay-dir /home/dreibh/src/kernel-package/kernel
#    --append-to-version "-custom" --revision "3000"

# \   buildpackage


debian/rules debian/stamp/pre-config-common


echo 'Building Package' >stamp-building
test ! -e scripts/package/builddeb || mv -f scripts/package/builddeb scripts/package/builddeb.kpkg-dist
test ! -e scripts/package/Makefile ||              \
    test -f scripts/package/Makefile.kpkg-dist ||  \
    (mv -f scripts/package/Makefile scripts/package/Makefile.kpkg-dist && \
       (echo "# Dummy file "; echo "help:") >  scripts/package/Makefile)

export MAINTAINER="Thomas Dreibholz <dreibh@iem.uni-due.de>"
export CONCURRENCY_LEVEL=1   # `getconf _NPROCESSORS_ONLN`
dpkg-buildpackage -S -sa -k"${MAINTAINER}" -rfakeroot -I.git -I.gitignore -i'\.git.*'

test ! -f scripts/package/builddeb.kpkg-dist ||   mv -f scripts/package/builddeb.kpkg-dist scripts/package/builddeb
test ! -f scripts/package/Makefile.kpkg-dist ||   mv -f scripts/package/Makefile.kpkg-dist scripts/package/Makefile
rm -f stamp-building
