#!/bin/bash -e

wget https://launchpad.net/~dreibh/+archive/ubuntu/ppa/+files/virtualbox-dkms-nornet-stable_5.0.10%7ETD8888-1ubuntu1%7Etrusty1%7Eppa0_all.deb
wget https://launchpad.net/~dreibh/+archive/ubuntu/ppa/+files/virtualbox-nornet-stable_5.0.10%7ETD8888-1ubuntu1%7Etrusty1%7Eppa0_amd64.deb

OLD='3.2.0-95'
NEW='3.1[3-9].*'

sudo apt-get update && \
sudo apt-get dist-upgrade -yd && \
sudo apt-get install -yd virtualbox-dkms-nornet-stable virtualbox-nornet-stable && \
sudo apt-get install -y linux-image-$OLD-generic linux-headers-$OLD-generic && \
sudo apt-get autoremove 'virtualbox-.*nornet-experimental' ;\
sudo apt-get dist-upgrade ;\
sudo apt-get autoremove linux-image-generic-lts-trusty linux-headers-generic-lts-trusty linux-image-$NEW-generic linux-headers-$NEW-generic ;\
sudo grub-install /dev/sda ;\
sudo update-grub ;\
sudo update-grub ;\
sudo dpkg -i virtualbox-nornet-stable_5.0.10~TD8888-1ubuntu1~trusty1~ppa0_amd64.deb virtualbox-dkms-nornet-stable_5.0.10~TD8888-1ubuntu1~trusty1~ppa0_all.deb
