#!/usr/bin/env bash

echo -e "\x1b[33m##########################################################################\x1b[0m"
echo -e "\x1b[33m!!! WARNING! All research systems need reinstall when proceeding here! !!!\x1b[0m"
echo -e "\x1b[33m##########################################################################\x1b[0m"

echo -en "\x1b[33mRenew *ALL* ISO files? [yes/no]\x1b[0m? "
read -er applyChanges
if [ "$applyChanges" != "yes" -a "$applyChanges" != "y" ] ; then
   echo "Skipped!"
else
   ./Make-Boot-ISO --directory=. ALL
fi
