#!/bin/bash -e

# HP DOWNLOAD URL: http://downloads.linux.hp.com/SDR/repo/mcp/pool/non-free/

sudo apt-get install -y lib32gcc1 xsltproc
sudo dpkg -i cpqacuxe_9.40.2-2._amd64.deb hpssaducli-2.0-16.0_amd64.deb hp-health_10.0.0.1.3-4._amd64.deb hponcfg_4.4.0.8-2._amd64.deb hpsmh_7.3.2-1.5-2._amd64.deb
sudo hponcfg -r
sudo dpkg -P cpqacuxe hpacucli hp-health hponcfg hpsmh
sudo apt-get remove -y lib32gcc1 xsltproc
