#!/usr/bin/env bash

# node=`hostname -f`
# site=`echo "$node" | sed -e "s/^[a-z0-9]*\.//g"`

nslint -c /etc/bind/named.conf 2>&1 | \
   grep -v "^nslint: multiple " | \
   grep -v loc | \
   grep -v sshfp | \
   grep -vE "Missing \"ptr\": (.*)\.all\."
