#!/usr/bin/env bash

# VBoxManage storageattach HAW-NorNet-Tunnelbox-hamburg.haw.nornet --storagectl "SATA" --port 0 --device 0 --nonrotational on --discard on

while [ $# -gt 0 ] ; do
   echo "===== $1 ... ====="
   sed -e 's/nonrotational="true" type="HardDisk"/nonrotational="true" discard="true" type="HardDisk"/g' -i $1
   grep 'discard="true"' $1
   shift
done

