#!/bin/bash

FCDISTRO="f24"
PLDISTRO="nornet"

../Slice-Setup add --name=srl_test           --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=9999 --user=dreibh@simula.no
../Slice-Setup add --name=srl_mptcp          --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=4    --user=dreibh@simula.no

../Slice-Setup add --name=srl_netperformance --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2   --user=dreibh@simula.no --user=pratikt@ifi.uio.no
../Slice-Setup add --name=srl_queuing        --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2   --user=dreibh@simula.no --user=kargar@simula.no
../Slice-Setup add --name=srl_nndemo         --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2   --user=dreibh@simula.no --user=henrikvs@ifi.uio.no
../Slice-Setup add --name=srl_thuen          --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=4   --user=dreibh@simula.no --user=andreasthuen@gmail.com
../Slice-Setup add --name=srl_seattle        --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2   --user=dreibh@simula.no --user=albert.rafetseder+nyu@univie.ac.at
../Slice-Setup add --name=srl_cps            --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2   --user=dreibh@simula.no --user=dipesh@simula.no
../Slice-Setup add --name=srl_sards          --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2   --user=dreibh@simula.no --user=eirikrosnes@simula.no --user=maximiliano.vela@hotmail.com

../Slice-Setup add --name=uio_fling          --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2   --user=dreibh@simula.no --user=dipesh@simula.no --user=michawe@ifi.uio.no --user=runabk@ifi.uio.no --user=ahmed@simula.no

../Slice-Setup add --name=uib_mptcp          --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2 --user=dreibh@simula.no --user=k.b.i@lyse.net --user=dse075@student.uib.no

../Slice-Setup add --name=haw_cmt            --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=4 --user=dreibh@simula.no --user=hauke.buhr@haw-hamburg.de --user=denis.lugowski@haw-hamburg.de --user=martin.becke@haw-hamburg.de

../Slice-Setup add --name=tuda_sereon        --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=6 --user=dreibh@simula.no --user=kubidem@deeds.informatik.tu-darmstadt.de

../Slice-Setup add --name=ntnu_test          --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=9999 --user=dreibh@simula.no --user=sune.jakobsson@gmail.com

../Slice-Setup add --name=ude_multipath      --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2 --user=dreibh@simula.no --user=hakim.adhari@uni-due.de
../Slice-Setup add --name=ude_delaytest      --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2 --user=dreibh@simula.no --user=hakim.adhari@uni-due.de --user=tobias.cloosters@stud.uni-due.de

../Slice-Setup add --name=kau_multipath      --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2 --user=dreibh@simula.no --user=per.hurtig@kau.se --user=johan.eklund@kau.se --user=stefan.alfredsson@kau.se
../Slice-Setup add --name=kau_mptcpsecurity  --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2 --user=dreibh@simula.no --user=zeeshan.afzal@kau.se

../Slice-Setup add --name=hu_multipath       --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=6 --user=dreibh@simula.no --user=zhouxing@hainu.edu.cn --user=fufa@hainu.edu.cn
../Slice-Setup add --name=hu_jerry           --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=1 --user=dreibh@simula.no --user=zhouxing@hainu.edu.cn --user=fufa@hainu.edu.cn # --user=arnoldjerry52@gmail.com
../Slice-Setup add --name=hu_zhoufeng        --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=4 --user=dreibh@simula.no --user=zhouxing@hainu.edu.cn --user=fufa@hainu.edu.cn --user=969493314@qq.com
../Slice-Setup add --name=hu_hanbaokuang     --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2 --user=dreibh@simula.no --user=zhouxing@hainu.edu.cn --user=fufa@hainu.edu.cn --user=1521793003@qq.com
../Slice-Setup add --name=hu_jiangshuihong   --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2 --user=dreibh@simula.no --user=zhouxing@hainu.edu.cn --user=fufa@hainu.edu.cn --user=75154166@qq.com
../Slice-Setup add --name=hu_tanqilin        --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2 --user=dreibh@simula.no --user=zhouxing@hainu.edu.cn --user=fufa@hainu.edu.cn --user=447542994@qq.com
../Slice-Setup add --name=hu_kunwang         --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2 --user=dreibh@simula.no --user=zhouxing@hainu.edu.cn --user=fufa@hainu.edu.cn --user=780952372@qq.com
../Slice-Setup add --name=hu_yuyintan        --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2 --user=dreibh@simula.no --user=zhouxing@hainu.edu.cn --user=fufa@hainu.edu.cn --user=tanyuyin@hainu.edu.cn
../Slice-Setup add --name=hu_fufa            --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2 --user=dreibh@simula.no --user=zhouxing@hainu.edu.cn --user=fufa@hainu.edu.cn
../Slice-Setup add --name=hu_xingzhou        --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2 --user=dreibh@simula.no --user=zhouxing@hainu.edu.cn --user=fufa@hainu.edu.cn
../Slice-Setup add --name=hu_chengxi         --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2 --user=dreibh@simula.no --user=zhouxing@hainu.edu.cn --user=fufa@hainu.edu.cn --user=391204334@qq.com
../Slice-Setup add --name=hu_yulilioa        --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=2 --user=dreibh@simula.no --user=zhouxing@hainu.edu.cn --user=fufa@hainu.edu.cn --user=1333760123@163.com

# ../Slice-Setup add --name=hu_ --own-addresses --fcdistro=$FCDISTRO --pldistro=$PLDISTRO --permanent --maxnodespersite=4 --user=dreibh@simula.no --user=zhouxing@hainu.edu.cn --user=fufa@hainu.edu.cn --user=
