#!/bin/sh

cd ..
./Check-Nodes-Loop 120 srl_test ~/.ssh/demo-user \
   boao.hu.nornet             wanqun.hu.nornet \
   nordlys.unis.nornet        snoeflak.unis.nornet \
   altenessen.ude.nornet      borbeck.ude.nornet \
   akerbrygge.simula.nornet   solvang.simula.nornet
