#!/bin/sh -e
#
# Tune VirtualBox VMs
# Copyright (C) 2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


while [ $# -gt 0 ] ; do
   echo "===== $1 ... ====="
   vm="$1"
   vmStatusFile=`mktemp`

   vboxmanage showvminfo --machinereadable "${vm}" >${vmStatusFile}

   controllers=`grep "^storagecontrollername.*=" ${vmStatusFile} | sed -e "s/^storagecontrollername.*=//g" -e "s/\"//g"`
   for controller in ${controllers} ; do

      # ====== Enable host cache ============================================
      echo "${controller}"
      VBoxManage storagectl "${vm}" \
         --name "${controller}" --hostiocache on

      # ====== Set discard and nonrotational options ========================
      for port in 0 1 2 3 4 5 6 7 8 9 ; do
         # Look for port with attached image
         if grep -q "^\"${controller}-ImageUUID-${port}-0\"=" ${vmStatusFile} ; then
            echo "${controller}-${port}-0"

            VBoxManage storageattach "${vm}" \
               --storagectl "${controller}" --port ${port} --device 0 --nonrotational on --discard on

         fi
      done
   done

   rm -f ${vmStatusFile}
   shift
done
