#!/bin/sh

if [ $# -ne 2 ] ; then
   echo >&2 "Usage: $0 ControlBox Tunnelbox_iLO_Address"
   exit 1
fi

CONTROLBOX="$1"
TUNNELBOX="$2"

echo "Connecting to ControlBox $CONTROLBOX ..."
echo "NOTE: Use \"sudo net.ipv4.tcp_ecn=2\" to turn ECN off, since HP fails to handle it properly ..."

sudo ssh nornetpp@$CONTROLBOX -L 5000:$TUNNELBOX:443 -L 23:$TUNNELBOX:23 -L 17988:$TUNNELBOX:17988
