#!/bin/sh

env DEBIAN_FRONTEND=noninteractive do-release-upgrade -f DistUpgradeViewNonInteractive
apt-add-repository -sy ppa:dreibh/ppa
env DEBIAN_FRONTEND=noninteractive apt install -y linux-generic-hwe-22.04
apt-show-versions | grep "No avail" | IFS=":" awk '{ print $1 }'|xargs sudo apt remove -y

# Clean-up:
# find /etc -name "*-dist" -or -name "*old" -or -name "*~" -or -name "*.distUpgrade" -or -name "*.save" | xargs -r rm 
