#!/bin/bash

TB=`Show-VSystems | head -n1`
echo "TB=$TB"

vboxmanage modifyvm $TB --nic3 bridged --nictype3 virtio --bridgeadapter3 eth3
vboxmanage modifyvm $TB --nic4 bridged --nictype4 virtio --bridgeadapter4 eth4
VBoxManage createhd --filename VirtualBox\ VMs/$TB/$TB-DH1-0.fixed.vdi --size 60000 --format vdi --variant Fixed
VBoxManage storageattach $TB --storagectl "SATA Controller" --port 2 --device 0 --type hdd --medium VirtualBox\ VMs/$TB/$TB-DH1-0.fixed.vdi
