#!/bin/bash

find /etc/apt/ -name "*.save" -or -name "*.distUpgrade" -or -name "*~" | xargs --no-run-if-empty sudo rm -f && \
find /etc/apt/sources.list.d -name "dreibh-ppa-*"  | xargs --no-run-if-empty sudo rm -f && \
sudo rm -f /etc/apt/apt.conf.d/50unattended-upgrades.ucf-old && \
sudo rm -f /etc/apt/apt.conf.d/50unattended-upgrades.ucf-dist && \
sudo apt-add-repository -y -s ppa:dreibh/ppa && \
sudo apt-get -o Acquire::ForceIPv4=true update && \
sudo apt-get -o Acquire::ForceIPv4=true  dist-upgrade -y && \
sudo service nornet-tunnelbox configure || true && \
sudo apt-get -o Acquire::ForceIPv4=true  install -y linux-generic-hwe-16.04 && \
sudo apt-get remove -y linux-*-generic-lts-xenial && \
sudo rm -rf /var/lib/cfengine3 /var/log/cfengine3 && \
sudo apt-get purge -y 'virtualbox.*' paris-traceroute tracebox stab collectd cfengine3 && \
sudo apt autoremove -y && \
sudo swapoff -a
