#!/usr/bin/env bash
#
# NorNet Configuration Backup Script
# Copyright (C) 2022 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


# ###### Backup file ########################################################
backup-file ()
{
   inputFile="$1"
   outputDirectory="$2"
   option="$3"
   if [ -e "${inputFile}" ] ; then
      outputFile="${outputDirectory}/`basename ${inputFile}`"
      if [ ! -e ${outputFile} ] ; then
         echo "Copying ${inputFile} to ${outputFile} ..."
         cp ${inputFile} ${outputFile}
      elif ! diff -q ${inputFile} ${outputFile} >/dev/null ; then
         echo "Updating ${inputFile} to ${outputFile} ..."
         colordiff ${inputFile} ${outputFile}
         cp ${inputFile} ${outputFile}
      fi

      # Ensure that the file is tracked by Git:
      sudo -u ${SUDO_USER} git add ${outputFile}
   else
      if [ "${option}" == "MANDATORY" ] ; then
         echo >&2 "ERROR: File ${inputFile} does not exist!"
         exit 1
      elif [ "${option}" == "WARNING" ] ; then
         echo >&2 "WARNING: File ${inputFile} does not exist!"
      fi
   fi
}


# ###### Main program #######################################################
name=`hostname`
mkdir -p "${name}"

echo "Backup to ${name} ... $SUDO_USER"
for file in hosts hostname sysctl.conf netplan/${name}.yaml apt/sources.list ; do
   backup-file /etc/${file} ${name} MANDATORY
done
for file in nornetapi-config nornetapi-constants ; do
   backup-file /etc/nornet/${file} ${name}
done

sudo cp /etc/sudoers ${name}/
sudo chown ${SUDO_USER}:${SUDO_USER} ${name}/sudoers

ls -l ${name}/
