#!/bin/bash

VM="NEW-TestSetup-Crossconnect"
vboxmanage modifyvm ${VM} --memory 1024 --audio none --vram 16 --nested-hw-virt off --hwvirtex off
vboxmanage modifyvm ${VM} --nic1 bridged --nictype1 virtio --bridgeadapter1 oslomet
vboxmanage modifyvm ${VM} --nic2 intnet  --nictype2 virtio --intnet2 OneAlpha
vboxmanage modifyvm ${VM} --nic3 intnet  --nictype3 virtio --intnet3 OneBeta
vboxmanage modifyvm ${VM} --nic4 intnet  --nictype4 virtio --intnet4 OneGamma
vboxmanage modifyvm ${VM} --nic5 intnet  --nictype5 virtio --intnet5 OneDelta
vboxmanage modifyvm ${VM} --nic6 intnet  --nictype6 virtio --intnet6 TwoAlpha
vboxmanage modifyvm ${VM} --nic7 intnet  --nictype7 virtio --intnet7 TwoBeta
vboxmanage modifyvm ${VM} --nic8 intnet  --nictype8 virtio --intnet8 TwoGamma
vboxmanage modifyvm ${VM} --nic9 intnet  --nictype9 virtio --intnet9 TwoDelta


VM="NEW-TestSetup-Tunnelbox-bjoernson.alpha.test"
vboxmanage modifyvm ${VM} --memory 2048 --audio none --vram 16 --nested-hw-virt off --hwvirtex off
vboxmanage modifyvm ${VM} --nic1 intnet  --nictype1 virtio --intnet1 TestNetwork-Alpha
vboxmanage modifyvm ${VM} --nic2 intnet  --nictype2 virtio --intnet2 OneAlpha
vboxmanage modifyvm ${VM} --nic3 intnet  --nictype3 virtio --intnet3 TwoAlpha
vboxmanage modifyvm ${VM} --nic4 bridged --nictype4 virtio --bridgeadapter4 oslomet

VM="NEW-TestSetup-Tunnelbox-ibsen.beta.test"
vboxmanage modifyvm ${VM} --memory 2048 --audio none --vram 16 --nested-hw-virt off --hwvirtex off
vboxmanage modifyvm ${VM} --nic1 intnet  --nictype1 virtio --intnet1 TestNetwork-Beta
vboxmanage modifyvm ${VM} --nic2 intnet  --nictype2 virtio --intnet2 OneBeta
vboxmanage modifyvm ${VM} --nic3 intnet  --nictype3 virtio --intnet3 TwoBeta
vboxmanage modifyvm ${VM} --nic4 bridged --nictype4 virtio --bridgeadapter4 oslomet

VM="NEW-TestSetup-Tunnelbox-wergeland.gamma.test"
vboxmanage modifyvm ${VM} --memory 2048 --audio none --vram 16 --nested-hw-virt off --hwvirtex off
vboxmanage modifyvm ${VM} --nic1 intnet  --nictype1 virtio --intnet1 TestNetwork-Gamma
vboxmanage modifyvm ${VM} --nic2 intnet  --nictype2 virtio --intnet2 OneGamma
vboxmanage modifyvm ${VM} --nic3 intnet  --nictype3 virtio --intnet3 TwoGamma
vboxmanage modifyvm ${VM} --nic4 bridged --nictype4 virtio --bridgeadapter4 oslomet

VM="NEW-TestSetup-Tunnelbox-uluru.delta.test"
vboxmanage modifyvm ${VM} --memory 2048 --audio none --vram 16 --nested-hw-virt off --hwvirtex off
vboxmanage modifyvm ${VM} --nic1 intnet  --nictype1 virtio --intnet1 TestNetwork-Delta
vboxmanage modifyvm ${VM} --nic2 intnet  --nictype2 virtio --intnet2 OneDelta
vboxmanage modifyvm ${VM} --nic3 intnet  --nictype3 virtio --intnet3 TwoDelta
vboxmanage modifyvm ${VM} --nic4 bridged --nictype4 virtio --bridgeadapter4 oslomet


VM="NEW-TestSetup-FileServer-kongleveien.alpha.test"
vboxmanage modifyvm ${VM} --memory 2048 --audio none --vram 16 --nested-hw-virt off --hwvirtex off
vboxmanage modifyvm ${VM} --nic1 intnet  --nictype1 virtio --intnet1 TestNetwork-Alpha

VM="NEW-TestSetup-Monitor-grefsen.alpha.test"
vboxmanage modifyvm ${VM} --memory 2048 --audio none --vram 16 --nested-hw-virt off --hwvirtex off
vboxmanage modifyvm ${VM} --nic1 intnet  --nictype1 virtio --intnet1 TestNetwork-Alpha

VM="NEW-TestSetup-Database-rolfsbukta.alpha.test"
vboxmanage modifyvm ${VM} --memory 2048 --audio none --vram 16 --nested-hw-virt off --hwvirtex off
vboxmanage modifyvm ${VM} --nic1 intnet  --nictype1 virtio --intnet1 TestNetwork-Alpha


VM="NEW-TestSetup-Development-vika.alpha.test"
vboxmanage modifyvm ${VM} --memory 2048 --audio none --vram 16 --nested-hw-virt off --hwvirtex off
vboxmanage modifyvm ${VM} --nic1 intnet  --nictype1 virtio --intnet1 TestNetwork-Alpha

VM="NEW-TestSetup-Development-mortensrud.beta.test"
vboxmanage modifyvm ${VM} --memory 2048 --audio none --vram 16 --nested-hw-virt off --hwvirtex off
vboxmanage modifyvm ${VM} --nic1 intnet  --nictype1 virtio --intnet1 TestNetwork-Beta

VM="NEW-TestSetup-Development-soedermalm.gamma.test"
vboxmanage modifyvm ${VM} --memory 2048 --audio none --vram 16 --nested-hw-virt off --hwvirtex off
vboxmanage modifyvm ${VM} --nic1 intnet  --nictype1 virtio --intnet1 TestNetwork-Gamma
