#!/bin/bash

./build-kernel-for-distribution dreibh/nornet-ubuntu:16.04 xenial >xenial.log 2>&1 &
./build-kernel-for-distribution dreibh/nornet-ubuntu:18.04 bionic >bionic     2>&1 &
./build-kernel-for-distribution dreibh/nornet-ubuntu:20.04 focal  >focal      2>&1 &
./build-kernel-for-distribution dreibh/nornet-ubuntu:22.04 jammy  >jammy      2>&1 &
wait
