#!/bin/bash -e


CONTAINER="jammy"
IMAGE="dreibh/nornet-ubuntu:22.04"
DIRECTORY="/tmp/${CONTAINER}"
LOCALVERSION="-mptcp"

# ====== Configure ==========================================================
cd ${HOME}/src/multipath/mptcp-kernel
echo "Cleaning sources ..."
sudo git clean -dfx --quiet
echo "Configuring build ..."
cat /boot/config-`uname -r` ~/src/nornet/planetlab-kernel/config-planetlab >.config && make config </dev/null >/dev/null 2>&1

# ====== Build ==============================================================
docker rm -f ${CONTAINER} >/dev/null 2>&1 || true

echo "RSync'ing sources ..."
rsync -a --delete ${HOME}/src/multipath/mptcp-kernel/ ${DIRECTORY}/

echo "Staring build ..."
docker run --rm -it --name ${CONTAINER} \
   --volume `realpath ${DIRECTORY}`:/home/nornetpp/src/mptcp-kernel \
   ${IMAGE} \
   bash -c "\
cd /home/nornetpp/src/mptcp-kernel && \
apt install -y rsync kmod cpio bison flex libssl-dev && \
pwd && \
id && \
bash
" && echo "OK" || echo "BAD"



# sudo apt install -y rsync kmod cpio bison flex libssl-dev && \
# make deb-pkg LOCALVERSION=\"${LOCALVERSION}\" && \
