#!/usr/bin/env bash
#
# Build NorNet Kernel Repository
# Copyright (C) 2017-2022 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no
#

# Bash options:
set -e


DISTRIBUTIONS="xenial bionic focal jammy   buster bullseye testing"
PACKAGE_STORAGE="/storage/mptcp-kernels"
PUBLIC_REPOSITORY="nornetpp@nfs.simula.nornet:/nfs/adm/packages/nornet-kernel/"
README_FILE="files/README.html"


for distribution in ${DISTRIBUTIONS} ; do
   echo -e "\x1b[34mSynchronising packages for ${distribution^} ...\x1b[0m"
   mkdir -p ${PACKAGE_STORAGE}/${distribution}-deb
   rsync -a packages/${distribution}/ ${PACKAGE_STORAGE}/${distribution}-deb/
done


# !!! rm -rf ${PACKAGE_STORAGE}/ubuntu
mkdir -p ${PACKAGE_STORAGE}/ubuntu/conf
cp distributions ${PACKAGE_STORAGE}/ubuntu/conf

cd ${PACKAGE_STORAGE}/ubuntu
for distribution in ${DISTRIBUTIONS} ; do
   echo -e "\x1b[34mProcessing packages for ${distribution^} ...\x1b[0m"

   dscFiles=`find ${PACKAGE_STORAGE}/${distribution}-deb -name "*dsc"`
   debFiles=`find ${PACKAGE_STORAGE}/${distribution}-deb -name "*.deb"`

   for dscFile in ${dscFiles} ; do   # Add source package
      reprepro -C main                   includedsc ${distribution} ${dscFile}
      reprepro -C ${distribution}-kernel includedsc ${distribution} ${dscFile}
   done
   for debFile in ${debFiles} ; do   # Add binary package
      reprepro -C main                   includedeb ${distribution} ${debFile}
      reprepro -C ${distribution}-kernel includedeb ${distribution} ${debFile}
   done
done


echo -e "\x1b[34mCopying to server ...\x1b[0m"
rsync --archive --partial --delete \
   --info=progress2 \
   -e "ssh -J 128.39.37.188" \
   ${PACKAGE_STORAGE}/ubuntu ${README_FILE} ${PUBLIC_REPOSITORY}/


echo -e "\x1b[34mDone!\x1b[0m"
