#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Image Best-Fit (resize with cropping, keeping aspect ratio)
# Copyright (C) 2015 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no
#

from PythonMagick import *
from math import *
from sys import *


if len(argv) != 4:
   print 'Usage: ' + argv[0] + ' [Input] [Output] [Aspect|A4]'
   exit(1)

inputFileName  = argv[1]
outputFileName = argv[2]
if ((argv[3] == 'A4') or (argv[3] == 'a4')):
   outputAspect = sqrt(2)
else:
   outputAspect = float(argv[3])

image       = Image(inputFileName)
inputWidth  = image.size().width()
inputHeight = image.size().height()

inputAspect = inputWidth / inputHeight
if inputAspect < 1.0:
   outputAspect = 1 / outputAspect   # Portrait


print 'Input:  ' + inputFileName + ' ' + str(inputWidth) + '*' + str(inputHeight) + ' (' + str(inputAspect) + ':1)'
if inputAspect < outputAspect:
   newWidth  = inputWidth
   newHeight = int(floor(newWidth / outputAspect))
else:
   newHeight = inputHeight
   newWidth  = int(floor(inputHeight * outputAspect))

cropWidth  = inputWidth - newWidth
cropHeight = inputHeight - newHeight
print ' -> crop: w=' + str(cropWidth) + ' h=' + str(cropHeight)

print 'Output: ' + outputFileName + ' ' + str(newWidth) + '*' + str(newHeight) + ' (' + str(outputAspect) + ':1)'
image.crop(str(newWidth) + 'x' + str(newHeight) + '+' + str(cropWidth / 2) + '+' + str(cropHeight / 2))
image.write(outputFileName)
