#!/bin/sh

rm -rf big
mkdir big
ls Flag-*.svg | (
   while read input ; do
      output=`echo $input | sed -e "s/.svg$/.png/g"`

      echo "Converting $input to $output ..."
      convert -quiet "$input" -sample 256 "big/$output-tmp.png"
      ./image-resize-with-cropping "big/$output-tmp.png" "big/$output" 1.5
      rm -f "big/$output-tmp.png"
   done
)
