#!/usr/bin/env bash
#
# NorNet Helper Scripts
# Copyright (C) 2012-2023 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

PROXY="128.39.37.188"   # oesthorn.nntb.no

Random-Sleep 0 5
while [ true ] ; do
   echo "Connecting to $1 ..."
   ssh -t -J $PROXY nornetpp@$1 || Random-Sleep 0 300
done
