#!/bin/bash

for level in 251 252 253 254 1 ; do
   (
      for site in 1 2 3 4 5 6 7 8 9 10 ; do
         address="10.1.$site.$level"
         echo "title: ${address};; command: /usr/bin/ssh -t -J oesthorn.nntb.no nornetpp@${address} ;; profile: Shell"
      done
   ) >tabs${level}
done
