#!/bin/bash

rm -f tbox* tbext* cbox*

../Get-Control-IPs >control.list

(
   while read number index tbint tbext cbext name ; do
      siteName=`echo "$name" | tr -d '"'`
      # echo "n=$number $tbint - $tbext   N=$siteName."

      for type in tbox tbext cbox ; do
         if [ "$type" == "tbox" -o "$type" == "tbext" ] ; then
            if [ "$type" == "tbext" ] ; then
               ip="$tbext"
            else
               ip="$tbint"
            fi
            typeName="Tunnelbox"
         else
            ip="$cbext"
            typeName="Control Box"
            if [ "$ip" == "0.0.0.0" ] ; then
               echo >&2 "ERROR: No control box address! Needs to access PLC as admin"
               continue
            fi
         fi

         outputFile=`printf "$type%02d" $number`
         ( echo "#!/bin/sh"
           echo "echo \"Connecting to $typeName of $siteName ($ip) ...\""
           echo "ssh -C nornetpp@$ip" ) >$outputFile
         chmod +x $outputFile
      done
   done
) <control.list


ILOGATEWAY="158.39.4.3:10.1.1.244 129.240.66.75:10.1.2.244 128.39.49.165:10.1.3.244 129.242.157.229:4002:10.1.4.244 152.94.120.7:10.1.5.244 158.37.6.194:10.1.6.244 158.36.50.182:10.1.7.244 158.39.149.133:10.1.8.244 129.241.200.129:10.1.9.244 158.39.93.232:10.1.10.244"
i=1
iloPort=4001
for iloGateway in $ILOGATEWAY ; do
   controlBoxAddress=`echo "$iloGateway" | sed -e "s/:.*$//g"`
   iloAddress=`echo "$iloGateway" | sed -e "s/^.*://g"`
   name=`printf "ilogateway%02d" $i`
   ( echo "#!/bin/sh"
     echo "echo \"Connecting to $controlBoxAddress ...\""
     echo "ssh -C nornetpp@$controlBoxAddress -L $iloPort:$iloAddress:443" ) >$name
   chmod +x $name
   let i=$i+1
   let iloPort=$iloPort+1
done
