#!/usr/bin/env bash
#
# NorNet Helper Scripts
# Copyright (C) 2012-2022 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

for level in 251 252 253 254 1 ; do
   (
      for site in 1 2 3 4 5 6 7 8 9 10 ; do
         address="10.1.$site.$level"
         name=`dig -x ${address} +short | sed -e "s/\..*$//g"`
         if [ "${name}" == "" ] ; then
            name="${address}"
         fi
         echo "title: ${name};; command: `realpath access` ${address}"
      done
   ) >tabs${level}
done


(
   for level in 251 252 253 254 1 ; do
      for site in 88 ; do
         address="10.80.$site.$level"
         name=`dig -x ${address} +short | sed -e "s/\..*$//g"`
         if [ "${name}" == "" ] ; then
            name="${address}"
         fi
         echo "title: ${name};; command: `realpath access` ${address}"
      done
   done
) >tabsHU
