#!/usr/bin/env bash
#
# NorNet Helper Scripts
# Copyright (C) 2012-2021 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# NOTE:
# Turn OFF setting General -> Remember window size
# Otherwise, Konsole is going to ignore the size settings here!

konsole \
   --separate --fallback-profile \
   -p ShowTerminalSizeHint=true -p TerminalColumns=256 -p TerminalRows=50 \
   -p ColorScheme=WhiteOnBlack \
   --tabs-from-file tabs1 -e date
