#!/usr/bin/env bash
#
# Print system information
# Copyright (C) 2013-2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


# ====== Print banner =======================================================

NORNET_VERSION=""
if [ -e /etc/nornet/nornet-version ] ; then
   NORNET_VERSION=`cat /etc/nornet/nornet-version`
fi

echo -en "\x1b[1;34m"
echo "================================================================="
echo -en "\x1b[1;31m"
echo "         #     #                 #     #"
echo "         ##    #   ####   #####  ##    #  ######   #####"
echo "         # #   #  #    #  #    # # #   #  #          #"
echo "         #  #  #  #    #  #    # #  #  #  #####      #"
echo "         #   # #  #    #  #####  #   # #  #          #"
echo "         #    ##  #    #  #   #  #    ##  #          #"
echo "         #     #   ####   #    # #     #  ######     #"
echo -en "\x1b[1;34m"
if [ "$NORNET_VERSION" != "" ] ; then
   echo ""
   y=$(( (66-${#NORNET_VERSION}) / 2 ))
   while [ $y -gt 0 ] ; do
      echo -n " "
      let y=$y-1
   done
   echo $NORNET_VERSION
fi
echo "================================================================="
echo -e "\x1b[0m"


exit 1   # With exit code 1, no further files in /etc/system-info.d are processed!

# Use exit code 0 to process further files!
