#!/bin/bash -e
#
# Thomas Dreibholz's Website Toolchain
# Copyright (C) 2012-2015 by Thomas Dreibholz, dreibh@iem.uni-due.de
#
# $Id: insert-section 3319 2013-05-01 13:54:22Z dreibh $
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNES6S FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
# Contact: dreibh@iem.uni-due.de
#


if [ $# -ne 5 ] ; then
    echo >&2 "Usage: $0 input section output begin_tag end_tag"
    exit 1
fi

INPUT="$1"
SECTION="$2"
OUTPUT="$3"
BEGIN="$4"
END="$5"

lineStart=$(cat $INPUT | grep -n "$BEGIN" | grep -o '^[0-9]*' || true)
lineEnd=$(cat $INPUT | grep -n "$END" | grep -o '^[0-9]*' || true)

if [ "$lineStart" = "" ] ; then
   echo >&2 "ERROR: No start line!"
   exit 1
fi
if [ "$lineEnd" = "" ] ; then
   echo >&2 "ERROR: No end line!"
   exit 1
fi

let lineInsert=$lineStart
let lineStart=$lineStart+1
let lineEnd=$lineEnd-1

cmd="sed <$INPUT"

cmd="$cmd -e \"s/<\!-- BEGIN-OF-DATE -->.*<\!-- END-OF-DATE -->/<\!-- BEGIN-OF-DATE -->`date "+%d.%m.%Y"`<\!-- END-OF-DATE -->/g\""
# Für Datum mit Uhrzeit: %H:%M:%S %Z

if [ $lineStart -le $lineEnd ] ; then
   cmd="$cmd -e \"${lineStart},${lineEnd}d\""
fi
cmd="$cmd -e \"${lineInsert}r $SECTION\""
cmd="$cmd >$OUTPUT"

# echo $cmd
eval $cmd
