#!/bin/bash -e

Get-NorNet-Configuration -noaddresses -noslivers >config.html.tmp
./extract-section config.html.tmp config.tmp BEGIN-OF-SITES-BLOCK END-OF-SITES-BLOCK
./insert-section NorNetCore-Sites.html.in config.tmp NorNetCore-Sites.html.new BEGIN-OF-SITES-BLOCK END-OF-SITES-BLOCK
# validate NorNetCore-Sites.html.new
rm -f config.html.tmp config.tmp

if ! diff NorNetCore-Sites.html.new NorNetCore-Sites.html >/dev/null 2>&1 ; then
   mv NorNetCore-Sites.html.new NorNetCore-Sites.html
fi
