etc/grub.d/??_nornet_tunnelbox_theme
usr/bin/Flush-Squid-Cache
usr/bin/Make-Tunnelbox-Configuration
usr/bin/Probe-Interface-Setup
usr/bin/Tunnelbox-Bootstrap-Helper
usr/bin/Tunnelbox-NAT-Helper
usr/bin/Tunnelbox-Setup
usr/share/man/man1/Flush-Squid-Cache.1
usr/share/man/man1/Make-Tunnelbox-Configuration.1
usr/share/man/man1/Probe-Interface-Setup.1
usr/share/man/man1/Tunnelbox-Bootstrap-Helper.1
usr/share/man/man1/Tunnelbox-NAT-Helper.1
usr/share/man/man1/Tunnelbox-Setup.1
usr/share/nornet-desktop/Splash/Tunnelbox1-*.jpeg /boot/NorNet
