Artwork/Graphics/Backgrounds/*.png /var/www/Artwork/Graphics/Backgrounds/
Artwork/Graphics/Control/*.png     /var/www/Artwork/Graphics/Control/
Artwork/Graphics/Flags/*.png       /var/www/Artwork/Graphics/Flags/
Artwork/Graphics/Flags/*.svg       /var/www/Artwork/Graphics/Flags/
Artwork/Graphics/Icons/*.png       /var/www/Artwork/Graphics/Icons/
Artwork/Graphics/Markers/*.svg     /var/www/Artwork/Graphics/Markers/
Artwork/Graphics/Sites/*.jpeg      /var/www/Artwork/Graphics/Sites/
