#!/bin/sh

set -e

case "$1" in
   configure)
      # Get rid of snmpd's stupid "error on subcontainer 'ia_addr' insert (-1)" errors in syslog.
      sed </etc/default/snmpd -e "s/SNMPDOPTS='-Lsd /SNMPDOPTS='-LS6d /g" -e "s/TRAPDOPTS='-Lsd /TRAPDOPTS='-LS6d /g" >/etc/default/snmpd.new && \
      mv /etc/default/snmpd.new /etc/default/snmpd

      if [ -x /usr/sbin/update-grub ] ; then
         /usr/sbin/update-grub || true
      fi
      ;;
esac

#DEBHELPER#

exit 0
