Kontrollsenter/Graphics/Backgrounds/*.png /var/www/Kontrollsenter/Graphics/Backgrounds/
Kontrollsenter/Graphics/Control/*.png     /var/www/Kontrollsenter/Graphics/Control/
Kontrollsenter/Graphics/Flags/*.png       /var/www/Kontrollsenter/Graphics/Flags/
Kontrollsenter/Graphics/Flags/*.svg       /var/www/Kontrollsenter/Graphics/Flags/
Kontrollsenter/Graphics/Icons/*.png       /var/www/Kontrollsenter/Graphics/Icons/
Kontrollsenter/Graphics/Markers/*.svg     /var/www/Kontrollsenter/Graphics/Markers/
Kontrollsenter/Graphics/Sites/*.jpeg      /var/www/Kontrollsenter/Graphics/Sites/
