#!/bin/sh -e

if [ $# -lt 2 ] ; then
   echo >&2 "Usage: $0 [Disk] [VDI file]"
   exit 1
fi


DISK="$1"
VDI="$2"

DISK_SIZE=`sudo fdisk -l $DISK | head -n2 | tail -n1 | awk '{ print $5; }'`
echo "Disk $DISK has $DISK_SIZE bytes!"

echo "Converting $DISK to $VDI ..."
rm -f "$VDI" "$VDI.dd" || true
# sudo dd "if=$DISK" | VBoxManage convertfromraw stdin "$VDI" $DISK_SIZE --format VDI --variant Standard

sudo dd "if=$DISK" "of=$VDI.dd"
VBoxManage convertfromraw "$VDI.dd" $DISK_SIZE --format VDI
rm -f "$VDI.dd"
