#!/bin/sh

if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 delay_in_seconds [-testonly]"
   exit 1
fi
DELAY="$1"
TESTONLY="$2"

VMs=`VBoxManage list vms | sed -e "s/ {.*}$//g"`
for vm in $VMs ; do
   echo "Starting $vm ..."

   if [ ! "$TESTONLY" = "-testonly" ] ; then
      vboxmanage startvm "$vm" --type headless
   fi

   echo "Waiting $DELAY seconds ..."
   sleep $DELAY
done
