#!/bin/sh

if [ $# -ne 1 ] ; then
   echo >&2 "Usage: $0 delay_in_seconds"
   exit 1
fi
DELAY="$1"

VMs=`VBoxManage list vms | sed -e "s/ {.*}$//g"`
for vm in $VMs ; do
   echo "Starting $vm ..."

   vboxmanage startvm "$vm" --type headless

   echo "Waiting $DELAY seconds ..."
done
