#!/bin/sh -e
#
# Install PlanetLab build dependencies
# Copyright (C) 2013 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no
#

sudo yum install -y libxml2-devel readline-devel ncurses-devel inotify-tools-devel php-devel PyXML check popt-static docbook-utils-pdf texlive python-setuptools python-dateutil python-lxml m2crypto rpm-sign
