#!/bin/sh

if [ $# -ne 1 ] ; then
   echo >&2 "Usage: $0 [kbuild source directory]"
   exit 1
fi
KBUILD_DIRECTORY="$1"
if [ ! -e "$KBUILD_DIRECTORY" ] ; then
   echo >&2 "ERROR: Directory $KBUILD_DIRECTORY does not exist!"
   exit 1
fi

cp make-deb clean-deb build-deb debian.conf filter-empty-entries renew-debian-changelog make-ppa "$KBUILD_DIRECTORY"
rm -rf "$KBUILD_DIRECTORY/debian"
cp -r debian "$KBUILD_DIRECTORY/debian"
