#!/usr/bin/python

# NorNet
from NorNetTools import *;
from NorNetAPI   import *;


# ###### Main program #######################################################
loginToPLC(quietMode=True)

for i in range(1,1000000):
   print('i=' + str(i))

   filter = { 'hostname':  'akerbrygge.simula.nornet' }
   nodeList = getPLCServer().GetNodes(getPLCAuthentication(), filter,
                                      ['node_id', 'site_id', 'hostname', 'model', 'boot_state'])


