#!/bin/bash -e
#
# Change CD image of virtual system
# Copyright (C) 2013 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


if [ $# -lt 2 ] ; then
   echo >&2 "Usage: $0 VM_name ISO_name [-restart-on-change]"
   exit 1
fi

MACHINE_NAME="$1"
ISO_NAME="$2"
OPTION="$3"


MACHINE_STATUS_FILE=`mktemp`
VBoxManage showvminfo "$MACHINE_NAME" --machinereadable >$MACHINE_STATUS_FILE

CONFIG_FILE=`cat $MACHINE_STATUS_FILE | grep "^CfgFile=" | sed -e "s/^CfgFile=\"//" -e "s/\"$//g"`
CONFIG_DIR=`dirname "$CONFIG_FILE"`

for controller in 0 1 2 3 ; do
   for port in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 ; do
      imageFile=`cat $MACHINE_STATUS_FILE | grep "^\"SATA Controller-$port-$controller" | sed -e "s/^\"SATA Controller-$port-$controller\"=\"//"  -e "s/\"$//" || echo ""`
      if [ "$imageFile" != "" ] ; then
         oldImage=`cat $MACHINE_STATUS_FILE | grep "^\"SATA Controller-$port-$controller" | sed -e "s/^\"SATA Controller-$port-$controller\"=\"//"  -e "s/\"$//" || echo ""`
         if [ "$oldImage" = "emptydrive" -o "`echo "$oldImage" | grep ".iso$"`" != "" ] ; then
            if [ "$oldImage" != "$ISO_NAME" ] ; then
               echo "Controller $controller, port $port: $imageFile -> $ISO_NAME"
               VBoxManage storageattach "$MACHINE_NAME" --storagectl "SATA Controller" --port $port --device $controller --type dvddrive --medium "$ISO_NAME"
               status=`Check-VSystem "$MACHINE_NAME"`
               if [ "$OPTION" = "-restart-on-change" -a "$status" = "running" ] ; then
                  echo "Restarting $MACHINE_NAME ..."
                  service nornet-server restart "$MACHINE_NAME"
               fi
            else
               echo "Controller $controller, port $port: $imageFile already set."
            fi
            rm -f $MACHINE_STATUS_FILE
            exit 0
         fi
      fi
   done
done

rm -f $MACHINE_STATUS_FILE
