.\" Get Nodes
.\" Copyright (C) 2016-2023 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd June 22, 2016
.Dt Check-Nodes-Loop 1
.Os Check-Nodes-Loop
.\" ###### Name #############################################################
.Sh NAME
.Nm Check-Nodes-Loop
.Nd Run Check-Nodes in a loop.
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm Check-Nodes-Loop
sleep_time
.Op arguments ...
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm Check-Nodes-Loop
runs Check-Nodes in a loop, with given time interval.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
.Bl -tag -width indent
.It sleep_time
The time between Check-Nodes calls in seconds.
.It arguments ...
Arguments to be given to Check-Nodes.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It Check-Nodes-Loop 60
.It Check-Nodes-Loop 300 srl_test /home/user/.ssh/id_rsa
.El
