#!/bin/bash
#
# Check whether login to test slice is possible
# Copyright (C) 2016 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

SLICE=srl_test
KEY=~/.ssh/test2

unreachableIntro="\x1b[34m"
goodIntro="\x1b[32m"
badIntro="\x1b[31m"
normalMode="\x1b[0m"
connectTimeout=10


function check-node ()
{
   local nodeName="$1"

   if ! ping -c3 >/dev/null 2>&1 ; then
      ssh -oStrictHostKeyChecking=no -oConnectTimeout=$connectTimeout -i $KEY $SLICE@$nodeName echo "Node is OK" >$nodeName.log 2>&1
      if [ "`head -n1 $nodeName.log`" = "Node is OK" ] ; then
         echo -e "$goodIntro$site\tOK\t$nodeName$normalMode"
      else
         echo -e "$badIntro$site\tBAD\t$nodeName\t\"`head -n1 $nodeName.log | tr --delete '\n\r'`\"$normalMode"
      fi
   else
      echo -e "$unreachableIntro$site\tUNREACHABLE\t$nodeName$normalMode"
   fi
}


if [ "$1" = "-n" ] ; then
   unreachableIntro=""
   goodIntro=""
   badIntro=""
   normalMode=""
fi

./Get-Nodes | awk '{ print $2 }' | xargs -n1 | (
   while read node ; do
      site=`echo "$node" | sed -e "s/^[a-z0-9]*\.//g"`
      check-node "$node" &
   done
   wait
) | sort -k2,2r -k1,1
