#!/bin/bash
#
# Check whether login to test slice is possible
# Copyright (C) 2016 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

SLICE=srl_test
KEY=~/.ssh/test2

./Get-Nodes | awk '{ print $2 }' | xargs -n1 | (
   while read node ; do
      site=`echo "$node" | sed -e "s/^[a-z0-9]*\.//g"`
      echo "Trying $node ..."
      (
         if ! ping -c3 >/dev/null 2>&1 ; then
            result=`ssh -oStrictHostKeyChecking=no -oConnectTimeout=30 -i $KEY $SLICE@$node echo "Node is OK"`
            if [ "$result" = "Node is OK" ] ; then
               echo -e "$site\tOK\t$node"
            else
               echo -e "$site\tBAD\t$node"
               echo "$result"
            fi
         else
            echo -e "$site\tUNREACHABLE\t$node"
         fi
      ) &
   done
   wait
)

echo "Done."
