#!/bin/bash -e
#
# Check status of virtual system
# Copyright (C) 2013 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


# ###### Call VBoxManage with timeouts #######################################
vminfo ()
{
   intTimeout=30
   killTimeout=35
# ################### VirtualBox #####################
   if [ "$1" = "vbox" ] ; then
      echo $NorNet_LocalNode_NorNetUser
      sudo -u $NorNet_LocalNode_NorNetUser env HOME=~$NorNet_LocalNode_NorNetUser timeout -s INT -k $killTimeout $intTimeout VBoxManage showvminfo --machinereadable $2 || true
      
# ####################  KVM ###########################
   elif [ "$1" = "kvm" ] ; then
      sudo -u $NorNet_LocalNode_NorNetUser env HOME=~$NorNet_LocalNode_NorNetUser timeout -s INT -k $killTimeout $intTimeout virsh dominfo $2 || true
   fi
}


# ###### Main program #######################################################
if [ $# -ne 1 ] ; then
   echo >&2 "Usage: $0 VM_name"
   exit 1
fi

NORNET_DIRECTORY="/etc/nornet"
MACHINE_NAME="$1"


# ====== Get NorNet user name ===============================================
if [ -e $NORNET_DIRECTORY/nornetapi-config ] ; then
   . $NORNET_DIRECTORY/nornetapi-config
elif [ -e ./nornetapi-config ] ; then
   . ./nornetapi-config
fi
if [ "$NorNet_LocalNode_NorNetUser" = "" ] ; then
   NorNet_LocalNode_NorNetUser="nornetpp"
fi


# ====== Obtain machine status ==============================================
status="BAD_MACHINE"
# #################### VirtualBox #######################################

if [ "$NorNet_LocalNode_Vplatform" = "vbox" ] ;  then
    Vplatform="vbox"
#    s=`vminfo "$MACHINE_NAME" --machinereadable "$Vplatform" | grep VMState=` && \
    s=`vminfo "$Vplatform" "$MACHINE_NAME" | grep VMState=` && \
    status=`echo $s | sed -e "s/VMState=//" -e "s/\"//g"` || true
elif [ "$NorNet_LocalNode_Vplatform" = "kvm" ] ; then
    
#################### KVM Machine status ########################## 
    Vplatform="kvm"
    s=`vminfo  "$Vplatform" "$MACHINE_NAME"  | grep State:` && \
    status=`echo $s | sed -e "s/State://" -e "s/^ *//g" -e "s/ *$//g"` || true
fi
####################


echo "$status"
