#!/bin/bash
#
# Remove SSH keys of all nodes (useful when they have updated)
# Copyright (C) 2014 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

./Get-Nodes | awk '{ print $2 }' | (
   while read name ; do
      fullName=`echo "$name" | sed -e "s/\./.all./"`
      echo "Removing keys of $name ($fullName) ..."
      A="`dig $fullName a +short` `dig $fullName aaaa +short`"
      for a in $A ; do
         echo "ssh-keygen -q -R $a"
         ssh-keygen -q -R "$a" >/dev/null 2>&1
      done
   done
)
