#!/bin/bash
#
# Create new SSH host keys
# Copyright (C) 2016 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

RSA_BITS=2048
ECDSA_BITS=521


show-keys ()
{
   keys=`find /etc/ssh -name "ssh_host_*.pub" | sort`
   firstKey=1
   for key in $keys ; do
      if [ $firstKey -eq 1 ] ; then
         echo -n "SSH Keys: "
         firstKey=0
      else
         echo -n "          "
      fi
      ssh-keygen -lf $key | sed -e "s/^\([0-9]*\) \([^ ]*\) \(.*\) (\(.*\))$/\2 (\4 \1)/g"
   done
}


echo -en "\x1b[33mRemove existing SSH host keys and generate new ones? [yes/no]?\x1b[0m "
read -er applyChanges
if [ "$applyChanges" != "yes" -a "$applyChanges" != "y" ] ; then
   exit 0
fi

BACKUP_DIRECTORY="backup-`env LANG=C date +%FT%H:%M:%S`"

echo "Making backup in $BACKUP_DIRECTORY ..."
cd /etc/ssh
mkdir $BACKUP_DIRECTORY/
find . -maxdepth 1 -name "ssh_host_*_key*" | xargs -n1 -i§ --no-run-if-empty mv § $BACKUP_DIRECTORY/
find . -maxdepth 1 -name "moduli*"         | xargs -n1 -i§ --no-run-if-empty mv § $BACKUP_DIRECTORY/
cp sshd_config $BACKUP_DIRECTORY/

echo "Generating moduli, step 1 ..."
time ssh-keygen -G moduli.candidates -b $RSA_BITS
echo "Generating moduli, step 2 ..."
time ssh-keygen -T moduli -f moduli.candidates

echo "Generating ED25519 key ..."
time ssh-keygen -N "" -t ed25519 -f ssh_host_ed25519_key
echo "Generating ED25519 key ..."
time ssh-keygen -N "" -t ecdsa -b $ECDSA_BITS -f ssh_host_ecdsa_key
echo "Generating RSA key ..."
time ssh-keygen -N "" -t rsa -b $RSA_BITS -f ssh_host_rsa_key

echo "Done!"
