#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Find Nodes with Problems
# Copyright (C) 2012-2018 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

import re
import os

# NorNet
from NorNetTools import *
from NorNetAPI   import *


# ###### Main program #######################################################
loginToPLC()

nodeList = getPLCServer().GetNodes(getPLCAuthentication(),
              { },
              [ 'hostname', 'boot_state', 'run_level' ])

for node in nodeList:
   print(node)
   if ((node['boot_state'] == 'boot') and
       (node['run_level'] == 'failboot')):
      print("-> reinstall")
      getPLCServer().UpdateNode(getPLCAuthentication(),
         node['hostname'],
         { 'boot_state' : 'reinstall' })
