#!/bin/bash

while [ $# -gt 0 ] ; do
   echo "Handling $1 ..."
   (
      echo "yum clean all"
      echo "yum -y remove 'ipfwroot*'"
   ) | sudo ssh -o StrictHostKeyChecking=no -i /etc/planetlab/root_ssh_key.rsa root@$1 &
   shift
done
wait
