#!/bin/bash

while [ $# -gt 0 ] ; do
   echo "Handling $1 ..."
   (
      #echo "service nm restart"
      echo "yum install -y nornet-nn"
      #echo "uname -a"
      #echo "yum clean all"
      #echo "NodeUpdate.py"
   ) | sudo ssh -o StrictHostKeyChecking=no -i /etc/planetlab/root_ssh_key.rsa root@$1 &
   shift
done
wait
