#!/bin/bash -e
#
# Flush Squid Cache
# Copyright (C) 2012-2019 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no
#

echo -e "\x1b[34m`date +%FT%H:%M:%S`: Stopping Squid service ...\x1b[0m"
service squid stop

for directory in /var/spool/squid /var/spool/squid3 ; do
   if [ -e ${directory} ] ; then
      echo "Cleaning up ${directory} ..."
      find ${directory} -type f | xargs -i rm -f
      fstrim -v ${directory}
      du -sch ${directory}
   fi
done

echo -e "\x1b[34m`date +%FT%H:%M:%S`: Starting Squid service ...\x1b[0m"
service squid start
service squid status
