#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Get all users
# Copyright (C) 2016-2021 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# NorNet
from NorNetSiteSetup import *
from NorNetTools     import *
from NorNetAPI       import *



# ###### Main program #######################################################
loginToPLC(quietMode = True)

userList = fetchNorNetUser(None)
for userID in userList:
   user = userList[userID]
   # print(user)

   print('{:32} {:1}, {:1}'.format(
      user['user_email'],
      user['user_last_name'],
      user['user_first_name']
   ))
