.\" Get Configuration
.\" Copyright (C) 2014 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd November 14, 2014
.Dt Get-NorNet-Configuration 1
.Os Get-NorNet-Configuration
.\" ###### Name #############################################################
.Sh NAME
.Nm Get-NorNet-Configuration
.Nd Export the testbed configuration.
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm Get-NorNet-Configuration
.Op Fl directory=data_directory
.Op Fl nohyperlinks
.Op Fl noaddresses
.Op Fl noslivers
.Op Fl html|\-latex
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm Get-NorNet-Configuration
export the testbed configuration from the PLC.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
.Bl -tag -width indent
.It Fl directory=data_directory
Put the image files (LaTeX output only!) into the given directory.
.It Fl nohyperlinks
Do not generate hyperlinks.
.It Fl noaddresses
Hide addresses.
.It Fl noslivers
Hide sliver information.
.It Fl html
Generate HTML output (default).
.It Fl latex
Generate LaTeX output.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It Get-NorNet-Configuration
.It Get-NorNet-Configuration \-noaddresses
.It Get-NorNet-Configuration \-noaddresses \-noslivers
.It Get-NorNet-Configuration \-noaddresses \-noslivers \-nohyperlinks
.It Get-NorNet-Configuration \-noaddresses \-latex \-directory=LaTeX-Images >NorNet.tex
.El
