.\" Get Slices
.\" Copyright (C) 2016-2019 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd June 22, 2016
.Dt Get-Slices 1
.Os Get-Slices
.\" ###### Name #############################################################
.Sh NAME
.Nm Get-Slices
.Nd Export a table of all slices.
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm Get-Slices
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm Get-Slices
export a table of all slices from the PLC.
.Pp
.\" .\" ###### Arguments ########################################################
.\" .Sh ARGUMENTS
.\" .Bl -tag -width indent
.\" .It option
.\" ...
.\" .El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It Get-Slices
.It Get-Slices | sort
.El
