#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Get all sites
# Copyright (C) 2012-2014 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

import re;
import os;
import base64;

# NorNet
from NorNetSiteSetup import *;
from NorNetTools     import *;
from NorNetAPI       import *;



# ###### Main program #######################################################
loginToPLC(quietMode = True)

siteList = fetchNorNetSite(None)
for siteIndex in siteList:
   site = siteList[siteIndex]
   #print site
   siteIndex = site['site_index']
   siteName  = site['site_utf8']

   print(str(siteIndex) + ' ' + \
         fill(siteName, 32))
