#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Get all sites
# Copyright (C) 2012-2023 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# NorNet
from NorNetSiteSetup import *
from NorNetTools     import *
from NorNetAPI       import *


# ###### Get IP address of control box ######################################
def getControlBoxForSite(siteID):
   for node in nodeList:
      if node['node_site_id'] == siteID:
         pcuID = lookupPCUIDforNode(node['node_id'])

         pcu = getPLCServer().GetPCUs(getPLCAuthentication(), { 'pcu_id' : pcuID }, [ 'ip' ])
         if len(pcu) > 0:
            return IPv4Address(pcu[0]['ip'])
         #else:
            #print('ERROR: No control box address. Needs to access PLC as admin!')

   return IPv4Address('0.0.0.0')


# ###### Main program #######################################################
publicIPTable = False
i = 1
while i < len(sys.argv):
   if sys.argv[i] == '-public-ip-table':
      publicIPTable = True
   i = i + 1   


loginToPLC(quietMode = True)

nodeList = fetchNorNetNode(None)
siteList = fetchNorNetSite(None)


if publicIPTable == False:
   n=1
   for siteIndex in sorted(siteList):
      site = siteList[siteIndex]
      siteIndex = site['site_index']
      siteName  = site['site_utf8']
      siteTags  = site['site_tags']

      tunnelboxIPext = IPv4Interface(getTagValue(siteTags, 'nornet_site_tbp0_address_ipv4', None)).ip
      tunnelboxIPint = makeNorNetIP(site['site_default_provider_index'], siteIndex, NorNet_NodeIndex_Tunnelbox, 4).ip
      controlboxIP   = getControlBoxForSite(site['site_id'])

      print(str(n) + '\t' + str(siteIndex) + '\t' + str(tunnelboxIPint) + '\t' + str(tunnelboxIPext) + '\t' + str(controlboxIP) + '\t"' + siteName + '\"')

      n = n + 1


else:
   for siteIndex in sorted(siteList):
      site = siteList[siteIndex]
      siteIndex    = site['site_index']
      siteName     = site['site_utf8']
      siteTags     = site['site_tags']
      providerList = getNorNetProvidersForSite(siteList[siteIndex])

      for i in range(0, NorNet_MaxProviders):
         providerIndex = int(getTagValue(siteTags, 'nornet_site_tbp' + str(i) + '_index', '-1'))
         if providerIndex <= 0:
            continue
         provider = providerList[providerIndex]
         providerName = provider['provider_long_name']
         providerTbIPv4 = IPv4Interface(getTagValue(siteTags, 'nornet_site_tbp' + str(i) + '_address_ipv4', '0.0.0.0/0'))
         if providerTbIPv4 != IPv4Interface('0.0.0.0/0'):
            print('"' + siteName + '"\t"' + providerName + '"\t' + '"Tunnelbox"\t' + str(providerTbIPv4.ip))
         providerTbIPv6 = IPv6Interface(getTagValue(siteTags, 'nornet_site_tbp' + str(i) + '_address_ipv6', '::/0'))
         if providerTbIPv6 != IPv6Interface('::/0'):
            print('"' + siteName + '"\t"' + providerName + '"\t' + '"Tunnelbox"\t' + str(providerTbIPv6.ip))

      controlboxIP = getControlBoxForSite(site['site_id'])
      if controlboxIP != IPv4Address('0.0.0.0'):
         print('"' + siteName + '"\t"' + providerName + '"\t' + '"Control Box"\t' + str(controlboxIP))
