#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Get all sites
# Copyright (C) 2012-2014 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

import re;
import os;
import base64;

# NorNet
from NorNetSiteSetup import *;
from NorNetTools     import *;
from NorNetAPI       import *;


# ###### Main program #######################################################
loginToPLC(quietMode = True)

siteList = fetchNorNetSite(None)
nodeList = fetchNorNetNode(None)

for siteIndex in siteList:
   site = siteList[siteIndex]
   #print site
   siteIndex    = site['site_index']
   siteName     = site['site_utf8']
   providerList = getNorNetProvidersForSite(site)

   print(str(siteIndex) + ' ' + \
         fill(siteName, 32))



   for node in nodeList:
      if node['node_site_id'] == site['site_id']:
         #print node
         nodeIndex = node['node_index']
         nodeName  = node['node_name']
         nodeUTF8  = node['node_utf8']
         nodeState = node['node_state']

         nodeFC = 'NA'
         nodePL = 'NA'
         nodeTagsList = fetchNodeTagsList(node['node_id'])
         for nodeTag in nodeTagsList:
            if nodeTag['tagname'] == 'fcdistro':
               nodeFC = nodeTag['value']
            if nodeTag['tagname'] == 'pldistro':
               nodePL = nodeTag['value']

         print(str(nodeIndex) + ' ' + fill(nodeUTF8,32) + ' ' + fill(nodeName,32) + ' ' + fill(nodeState,10) + ' ' + fill(nodeFC,4) + ' ' + fill(nodePL,6))


         sliceNodeIndex = 0
         for onlyDefault in [ True, False ]:
            for providerIndex in providerList:
               if ( ((onlyDefault == True)  and (providerIndex == site['site_default_provider_index'])) or \
                     ((onlyDefault == False) and (providerIndex != site['site_default_provider_index'])) ):

                  provider = providerList[providerIndex]
                  #print provider

                  ifIPv4 = makeNorNetIP(providerIndex, siteIndex, nodeIndex, 4, sliceNodeIndex)
                  ifIPv6 = makeNorNetIP(providerIndex, siteIndex, nodeIndex, 6, sliceNodeIndex)

                  print '\t' + provider['provider_long_name'] + '\t' + str(ifIPv4) + ' ' + str(ifIPv6)
