.\" Get Nodes
.\" Copyright (C) 2014-2021 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd July 30, 2014
.Dt Get-Nodes 1
.Os Get-Nodes
.\" ###### Name #############################################################
.Sh NAME
.Nm Get-Nodes
.Nd Export a table of nodes and their status.
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm Get-Nodes
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm Get-Nodes
export a table of nodes and their status from the PLC.
.Pp
.\" .\" ###### Arguments ########################################################
.\" .Sh ARGUMENTS
.\" .Bl -tag -width indent
.\" .It option
.\" ...
.\" .El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It Get-Nodes
.It Get-Nodes | grep '^100' | awk '{ print $2 }'
.El
