#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# NorNet Test Setup
# Copyright (C) 2012 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


# Needs package python-ipaddr (Fedora Core, Ubuntu, Debian)!
from ipaddr import IPv4Address, IPv4Network, IPv6Address, IPv6Network;

# NorNet
from NorNetTools         import *;
from NorNetAPI           import *;
from NorNetProviderSetup import *;
from NorNetSiteSetup     import *;


# ###### Remove test setup ##################################################
def removeTestConfiguration():
   # ====== Remove test sites ===============================================
   removeNorNetSite("Alpha Test Site")
   removeNorNetSite("Beta Test Site")
   removeNorNetSite("Gamma Test Site")


# ###### Make test setup ####################################################
def createTestConfiguration(userName, sliceName):
   # ====== Add tag types ===================================================
   makeNorNetTagTypes()

   # ====== Add test sites ==================================================
   norNetInformation = getNorNetInformationForAddress(getPLCAddress())
   plcNodeIndex      = norNetInformation['node_index']
   dnsServers = [ makeNorNetIP(NorNet_SiteIndex_Central, NorNet_CentralSite_BootstrapProviderIndex, plcNodeIndex, -1, 4),
                  makeNorNetIP(NorNet_SiteIndex_Central, NorNet_CentralSite_BootstrapProviderIndex, plcNodeIndex, -1, 6) ]
   ntpServerNames = [ 'ntp1.ptb.de', 'ntp2.ptb.de', 'ntp3.ptb.de',   # The PTB servers (very reliable sources)
                      'ntp1.uio.no', 'ntp2.uio.no' ]                 # UiO (nearby)

   ntpServers = []
   for ntpServer in ntpServerNames:
      ntpAddress = resolveHostname(ntpServer, AF_INET6)
      if ntpAddress != None:
         ntpServers.append(ntpAddress)
      ntpAddress = resolveHostname(ntpServer, AF_INET)
      if ntpAddress != None:
         ntpServers.append(ntpAddress)


   siteAlphaNorNetIndex = 1
   siteAlpha = makeNorNetSite('Alpha Test Site', 'TA', 'ta', 'http://www.alpha.site', 'alpha.site',
                              siteAlphaNorNetIndex, 'Fornebu', 'Østlandet', 'Norge', 'NO', 59.895933, 10.627635, [
                                 [ 'Uninett', 'eth0', IPv4Address('132.252.156.70'), IPv6Address('fd55:5555::70') ],
                                 [ 'Telenor', 'eth0', IPv4Address('169.254.100.70'), IPv6Address('::') ]
                              ], 'Uninett', 'eth0', dnsServers, ntpServers)
   siteAlphaPCUID = makeNorNetPCU(siteAlpha, 'pcu', 'alpha.site', IPv4Address('132.252.156.2'),
                                  'pcu-root', 'a-secret-password', 'ssh', 'Amiga 5099', 'Jeg vet ikke.')

   siteBetaNorNetIndex = 2
   siteBeta  = makeNorNetSite('Beta Test Site', 'TB', 'tb', 'http://www.beta.site', 'beta.site',
                              siteBetaNorNetIndex, 'Blindern',  'Østlandet', 'Norge', 'NO', 59.944086, 10.719056, [
                                 [ 'Uninett', 'eth0', IPv4Address('132.252.156.71'), IPv6Address('fd55:5555::71') ],
                                 [ 'Telenor', 'eth0', IPv4Address('169.254.100.71'), IPv6Address('::') ]
                              ], 'Uninett', 'eth0', dnsServers, ntpServers)
   siteBetaPCUID = makeNorNetPCU(siteBeta, 'pcu', 'beta.site', IPv4Address('132.252.156.3'),
                                 'pcu-root', 'a-secret-password', 'ssh', 'Amiga 5099', 'Jeg vet ikke.')

   siteGammaNorNetIndex = 3
   siteGamma = makeNorNetSite('Gamma Test Site', 'TC', 'tc', 'http://www.gamma.site', 'gamma.site',
                              siteGammaNorNetIndex, 'Essen',  'Nordrhein-Westfalen', 'Deutschland', 'DE', 51.476144, 7.011656, [
                                 [ 'Uninett', 'eth0', IPv4Address('132.252.156.72'), IPv6Address('::') ],
                                 [ 'Telenor', 'eth0', IPv4Address('169.254.100.72'), IPv6Address('::') ],
                                 [ 'Deutsches Forschungsnetz', 'eth0', IPv4Address('172.31.255.72'),  IPv6Address('::') ]
                              ], 'Deutsches Forschungsnetz', 'eth0', dnsServers, ntpServers)
   siteGammaPCUID = makeNorNetPCU(siteGamma, 'pcu', 'gamma.site', IPv4Address('132.252.156.4'),
                                  'pcu-root', 'a-secret-password', 'ssh', 'Amiga 5099', 'Jeg vet ikke.')


   # ====== Add test nodes ==================================================
   firstAddressIndex = 101

   names = sorted(['akerbrygge', 'bygdoey', 'ekeberg', 'fornebu', 'majorstuen', 'ullevaal'])
   i = 0
   for name in names:
      n = makeNorNetNode(siteAlpha, name, 1 + i, firstAddressIndex,
                         siteAlphaPCUID, 1 + i, 'eth0')
      i = i + 1

   names = sorted(['bjordammen', 'maridalsvannet', 'sognsvann', 'svartkulp', 'skjennungen', 'tryvann'])
   i = 0
   for name in names:
      makeNorNetNode(siteBeta, name, 1 + i, firstAddressIndex,
                     siteBetaPCUID, 1 + i, 'eth0')
      i = i + 1

   names = sorted(['altenessen', 'baldeneysee', 'borbeck', 'zollvererin'])
   i = 0
   for name in names:
      makeNorNetNode(siteGamma, name, 1 + i, firstAddressIndex,
                     siteGammaPCUID, 1 + i, 'eth0')
      i = i + 1


   # ====== Add person to all test sites ====================================
   personID = lookupPersonID(userName)
   if personID == 0:
      error('Unable to find user ' + userName + '\n')

   getPLCServer().AddRoleToPerson(getPLCAuthentication(), 'user', personID)
   getPLCServer().AddRoleToPerson(getPLCAuthentication(), 'pi',   personID)
   getPLCServer().AddRoleToPerson(getPLCAuthentication(), 'tech', personID)

   getPLCServer().AddPersonToSite(getPLCAuthentication(), personID, siteAlpha['site_id'])
   getPLCServer().AddPersonToSite(getPLCAuthentication(), personID, siteBeta['site_id'])
   getPLCServer().AddPersonToSite(getPLCAuthentication(), personID, siteGamma['site_id'])

   getPLCServer().SetPersonPrimarySite(getPLCAuthentication(), personID, siteBeta['site_id'])


   # ====== Add slice to all nodes ==========================================
   sliceID = lookupSliceID(sliceName)
   if sliceID == 0:
      error('Unable to find slice ' + sliceName + '\n')
   nodeList = getPLCServer().GetNodes(getPLCAuthentication(), { })
   nodeIDs  = []
   for node in nodeList:
      nodeID = int(node['node_id'])
      nodeIDs.append(nodeID)

   getPLCServer().AddSliceToNodes(getPLCAuthentication(), sliceID, nodeIDs)



createSetup = False
removeSetup = False

if len(sys.argv) > 1:
   if sys.argv[1] == '-create':
      createSetup = True
   elif sys.argv[1] == '-remove':
      removeSetup = True
   elif sys.argv[1] == '-renew':
      createSetup = True
      removeSetup = True
   else:
      error('Usage: ' + sys.argv[0] + ' [-create|-remove|-renew]')
else:
      error('Usage: ' + sys.argv[0] + ' [-create|-remove|-renew]')


log('***** This is NorNet *****')
loginToPLC()
if removeSetup == True:
   removeTestConfiguration()
if createSetup == True:
   createTestConfiguration('dreibh@simula.no', 'nn_test')
