#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# NorNet Test Setup
# Copyright (C) 2012 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


# Needs package python-ipaddr (Fedora Core, Ubuntu, Debian)!
from ipaddr import IPv4Address, IPv4Network, IPv6Address, IPv6Network;

# NorNet
from NorNetTools         import *;
from NorNetAPI           import *;
from NorNetProviderSetup import *;
from NorNetSiteSetup     import *;



# ###### Make test setup ####################################################
# WARNING: A previous test setup is completely REMOVED!
def createTestConfiguration(userName, sliceName):
   # ====== Add tag types ===================================================
   makeNorNetTagTypes()


   # ====== Remove test sites ===============================================
   removeNorNetSite("Alpha Test Site")
   removeNorNetSite("Beta Test Site")
   removeNorNetSite("Gamma Test Site")


   # ====== Add test sites ==================================================
   siteAlphaNorNetIndex = 1
   siteAlpha = makeNorNetSite('Alpha Test Site', 'TA', 'ta', 'http://www.alpha.site', 'alpha.site',
                              siteAlphaNorNetIndex, 'Ullevål', 'Østlandet', 'Norge', 'NO', 10.0, 50.0, [
                                 [ 'Uninett', 'eth0', IPv4Address('132.252.156.70'), IPv6Address('fd55:5555::70') ],
                                 [ 'Telenor', 'eth0', IPv4Address('169.254.100.70'), IPv6Address('::') ]
                              ], 'Uninett', 'eth0')
   siteAlphaPCUID = makeNorNetPCU(siteAlpha, 'pcu', 'alpha.site', IPv4Address('132.252.156.2'),
                                  'pcu-root', 'a-secret-password', 'ssh', 'Amiga 5099', 'Jeg vet ikke.')

   siteBetaNorNetIndex = 2
   siteBeta  = makeNorNetSite('Beta Test Site', 'TB', 'tb', 'http://www.beta.site', 'beta.site',
                              siteBetaNorNetIndex, 'Bygdøy',  'Østlandet', 'Norge', 'NO', 15.0, 55.0, [
                                 [ 'Uninett', 'eth0', IPv4Address('132.252.156.71'), IPv6Address('fd55:5555::71') ],
                                 [ 'Telenor', 'eth0', IPv4Address('169.254.100.71'), IPv6Address('::') ]
                              ], 'Uninett', 'eth0')
   siteBetaPCUID = makeNorNetPCU(siteBeta, 'pcu', 'beta.site', IPv4Address('132.252.156.3'),
                                 'pcu-root', 'a-secret-password', 'ssh', 'Amiga 5099', 'Jeg vet ikke.')

   siteGammaNorNetIndex = 3
   siteGamma = makeNorNetSite('Gamma Test Site', 'TC', 'tc', 'http://www.gamma.site', 'gamma.site',
                              siteGammaNorNetIndex, 'Essen',  'Nordrhein-Westfalen', 'Deutschland', 'DE', 12.5, 40.0, [
                                 [ 'Uninett', 'eth0', IPv4Address('132.252.156.72'), IPv6Address('::') ],
                                 [ 'Telenor', 'eth0', IPv4Address('169.254.100.72'), IPv6Address('::') ],
                                 [ 'Deutsches Forschungsnetz', 'eth0', IPv4Address('172.31.255.72'),  IPv6Address('::') ]
                              ], 'Deutsches Forschungsnetz', 'eth0')
   siteGammaPCUID = makeNorNetPCU(siteGamma, 'pcu', 'gamma.site', IPv4Address('132.252.156.4'),
                                  'pcu-root', 'a-secret-password', 'ssh', 'Amiga 5099', 'Jeg vet ikke.')


   # ====== Add test nodes ==================================================
   firstAddressIndex = 81
   i = 0

   names = sorted(['akerbrygge', 'bygdoey', 'ekeberg', 'fornebu', 'majorstuen', 'ullevaal'])
   for name in names:
      n = makeNorNetNode(siteAlpha, name, 1 + i, firstAddressIndex,
                     siteAlphaPCUID, 1 + i,
                     [ getPLCAddress() ], 'eth0')
      i = i + 1

   names = sorted(['bjordammen', 'maridalsvannet', 'sognsvann', 'svartkulp', 'skjennungen', 'tyrvann'])
   for name in names:
      makeNorNetNode(siteBeta, name, 1 + i, firstAddressIndex,
                     siteBetaPCUID, 1 + i,
                     [ getPLCAddress() ], 'eth0')
      i = i + 1

   names = sorted(['altenessen', 'baldeneysee', 'borbeck', 'zollvererin'])
   for name in names:
      makeNorNetNode(siteGamma, name, 1 + i, firstAddressIndex,
                     siteGammaPCUID, 1 + i,
                     [ getPLCAddress() ], 'eth0')
      i = i + 1


   # ====== Add person to all test sites ====================================
   personID = lookupPersonID(userName)
   if personID == 0:
      error('Unable to find user ' + userName + '\n')

   getPLCServer().AddRoleToPerson(getPLCAuthentication(), 'user', personID)
   getPLCServer().AddRoleToPerson(getPLCAuthentication(), 'pi',   personID)
   getPLCServer().AddRoleToPerson(getPLCAuthentication(), 'tech', personID)

   getPLCServer().AddPersonToSite(getPLCAuthentication(), personID, siteAlpha['site_id'])
   getPLCServer().AddPersonToSite(getPLCAuthentication(), personID, siteBeta['site_id'])
   getPLCServer().AddPersonToSite(getPLCAuthentication(), personID, siteGamma['site_id'])

   getPLCServer().SetPersonPrimarySite(getPLCAuthentication(), personID, siteBeta['site_id'])


   # ====== Add slice to all nodes ==========================================
   sliceID = lookupSliceID(sliceName)
   if sliceID == 0:
      error('Unable to find slice ' + sliceName + '\n')
   nodeList = getPLCServer().GetNodes(getPLCAuthentication(), { })
   nodeIDs  = []
   for node in nodeList:
      nodeID = int(node['node_id'])
      nodeIDs.append(nodeID)

   getPLCServer().AddSliceToNodes(getPLCAuthentication(), sliceID, nodeIDs)



log('***** This is NorNet *****')
loginToPLC()
createTestConfiguration('dreibh@simula.no', 'nn_test')
