#!/bin/bash -e
#
# Interface Setup
# Copyright (C) 2013 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


# ###### Exit with usage information ########################################
exit_with_usage ()
{
   /bin/echo >&2 "Usage: $0 interface pre-up|up|post-up|pre-down|down|post-down ipv4|ipv6 [address/prefix gateway metric options] ..."
   exit 1
}


# ###### Write log information ##############################################
log ()
{
   /bin/echo -e "\x1b[1;34m`date +%FT%H:%M:%S`: $@\x1b[0m"
}


# ###########################################################################
# #### Main Program                                                      ####
# ###########################################################################

# ====== Handle arguments ===================================================
if [ $# -lt 3 ] ; then
   exit_with_usage
fi

logFile="/var/log/nornet-ifupdown.log"
interface="$1"
state="$2"
type="$3"
if [ "$type" != "ipv4" -a "$type" != "ipv6" ] ; then
   exit_with_usage
fi

if [ "$state" = "pre-up" ] ; then
   (
      log "Pre-Up of interface $interface"
      if [ "$type" == "ipv6" ] ; then
         /sbin/sysctl -q -e -w net.ipv6.conf.$interface.use_tempaddr=0 net.ipv6.conf.$interface.accept_ra=0 net.ipv6.conf.$interface.autoconf=0 || true
      fi

      # NOTE:
      # For some reason, listening to the solicited node multicast
      # address sometimes does not work. Then, IPv6 connectivity is lost.
      # Turning on promiscuous mode as a work-around here!
      /sbin/ip link set up promisc on dev "$interface" || true
   ) >>$logFile 2>&1

elif [ "$state" = "post-up" ] ; then
   (
      log "Post-Up of interface $interface"
      if [ "$type" == "ipv4" ] ; then
         ip -4 addr show dev "$interface"
      else
         ip -6 addr show dev "$interface"
      fi
   ) >>$logFile 2>&1

elif [ "$state" = "post-down" ] ; then
   (
      log "Post-Down of interface $interface"
      /sbin/ip link set down promisc off dev "$interface" || true
   ) >>$logFile 2>&1

elif [ "$state" = "up" ] ; then
   if [ $# -lt 2 ] ; then
      exit_with_usage
   fi
   shift ; shift ; shift

   (
      log "Up of interface $interface"

      while [ "$4" != "" ] ; do
         address="$1"
         network="$2"
         gateway="$3"
         metric="$4"
         options="$5"
         shift ; shift ; shift ; shift ; shift
         /bin/echo "Adding $address, route to $network via $gateway with metric $metric ..."
         /sbin/ip addr add "$address" dev "$interface" $options || /bin/echo "ERROR: Failed to add address"
         /sbin/ip route add "$network" via "$gateway" dev "$interface" metric "$metric" || /bin/echo "ERROR: Failed to add route"
      done

   ) >>$logFile 2>&1

elif [ "$state" = "down" ] ; then
   if [ $# -lt 2 ] ; then
      exit_with_usage
   fi
   shift ; shift ; shift

   (
      log "Down of interface $interface"

      while [ "$4" != "" ] ; do
         address="$1"
         network="$2"
         gateway="$3"
         metric="$4"
         options="$5"
         shift ; shift ; shift ; shift ; shift
         /bin/echo "Removing $address, route to $network via $gateway with metric $metric ..."
         /sbin/ip route del "$network" via "$gateway" dev "$interface" metric "$metric" || /bin/echo "ERROR: Failed to remove route"
         /sbin/ip addr del "$address" dev "$interface" $options || /bin/echo "ERROR: Failed to remove address"
      done

   ) >>$logFile 2>&1

else
   exit_with_usage

fi
