#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Make Node Configuration
# Copyright (C) 2012 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


import sys;

# NorNet
from NorNetAPI       import *;
from NorNetNodeSetup import *;


# ====== Handle arguments ===================================================
if len(sys.argv) < 4:
   error('Usage: ' + sys.argv[0] + ' NodeName Interface Debian|Fedora')
nodeName     = sys.argv[1]
interface    = sys.argv[2]
distribution = sys.argv[3]


# ====== Get configuration ==================================================
loginToPLC()

node = fetchNorNetNode(nodeName)
if node == None:
   error('Unable to find node ' + nodeName + ' in database!')

fullSiteList = fetchNorNetSiteList()
localSite    = getNorNetSiteOfNode(fullSiteList, node)
if localSite == None:
   error('Unable to find site of node ' + nodeName + ' in database!')

fullUserList = fetchNorNetUserList()

makeNodeConfiguration(fullSiteList, node, interface, distribution, '')
makeNTPConfiguration(fullSiteList, localSite, 'ntp')
makeSNMPConfiguration(fullSiteList, fullUserList, localSite, 'snmpd', 'node', 'Node')
