#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Make Tunnelbox Configuration
# Copyright (C) 2012 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


import sys;

# NorNet
from NorNetAPI           import *;
from NorNetConfiguration import *;


bootstrapOnly = False

if len(sys.argv) > 1:
   if sys.argv[1] == '-bootstrap':
      bootstrapOnly = True
   else:
      error('Usage: ' + sys.argv[0] + ' [-bootstrap]')


if bootstrapOnly:
   loadNorNetConfiguration()
else:
   loginToPLC()


localSiteIndex            = getLocalSiteIndex()
localDefaultProviderIndex = getLocalDefaultProviderIndex()

if localSiteIndex == None:
   error('NorNet_LocalSite_SiteIndex has not been set in configuration file!')
if ((localSiteIndex < 1) or (localSiteIndex > 255)):
    error('Bad NorNet_LocalSite_SiteIndex ' + str(localSiteIndex))
if localDefaultProviderIndex == None:
   error('NorNet_LocalSite_DefaultProviderIndex has not been set in configuration file!')
if ((localDefaultProviderIndex < 1) or (localDefaultProviderIndex > 255)):
    error('Bad NorNet_LocalSite_DefaultProviderIndex ' + str(localDefaultProviderIndex))


if bootstrapOnly:
   makeTunnelboxBootstrap(localSiteIndex, localDefaultProviderIndex, '132.252.156.71', 'tunnelbox')
else:
   fullSiteList = fetchNorNetSiteList()
   localSite    = None
   try:
      localSite = fullSiteList[localSiteIndex]
   except:
      error('Cannot find local site ' + str(localSiteIndex) + ' at PLC database!')

   makeTunnelBoxConfiguration(fullSiteList, localSite, 'tunnelbox', False)
