.\" Make Tunnelbox Configuration
.\" Copyright (C) 2012-2013 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd May 23, 2013
.Dt Make-Tunnelbox-Configuration 1
.Os Make-Tunnelbox-Configuration
.\" ###### Name #############################################################
.Sh NAME
.Nm Make-Tunnelbox-Configuration
.Nd NorNet Tunnelbox Configuration Script
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm Make-Tunnelbox-Configuration
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm Make-Tunnelbox-Configuration
generates the configurations scripts for Tunnelbox-Setup. It contacts the
Central Site PLC to obtain the configuration.
.Pp
.\" .\" ###### Arguments ########################################################
.\" .Sh ARGUMENTS
.\" The following options are available:
.\" .Bl -tag -width indent
.\" .El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It Make-Tunnelbox-Configuration
.El
