#!/bin/bash -e
# -*- coding: utf-8 -*-
#
# Make Research VM
# Copyright (C) 2012 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

if [ $# -ne 4 ] ; then
   echo >&2 "Usage: $0 VM_name ISO_name memory_MiB disk_GiB"
   exit 1
fi

VM_NAME="$1"
ISO_NAME="$2"
MEMORY_SIZE="$3"
DISK_SIZE="$4"

CPUS="2"
VRAM="12"


VBoxManage unregistervm "$VM_NAME" --delete || true

VBoxManage createvm --register --name "$VM_NAME" --ostype Ubuntu_64
VBoxManage modifyvm "$VM_NAME" --cpus "$CPUS" \
                               --memory "$MEMORY_SIZE" --vram "$VRAM" \
                               --rtcuseutc on --firmware bios --chipset ich9 --acpi on --ioapic on \
                               --hwvirtex on --pae off
VBoxManage modifyvm "$VM_NAME" --nic1 bridged --nictype1 virtio --bridgeadapter1 eth0  --cableconnected1 on --macaddress1 auto
VBoxManage createhd --filename "~/VirtualBox VMs/$VM_NAME/DH0.vdi" --size "$DISK_SIZE" --format vdi --variant Standard
VBoxManage storagectl "$VM_NAME" --name "SATA Controller" --add sata --controller IntelAHCI
VBoxManage storageattach "$VM_NAME" --storagectl "SATA Controller" --port 0 --device 0 --type dvddrive \
                                    --medium "$ISO_NAME"
VBoxManage storageattach "$VM_NAME" --storagectl "SATA Controller" --port 1 --device 0 --type hdd \
                                    --medium "~/VirtualBox VMs/$VM_NAME/DH0.vdi"

(
   echo "NAME=\"$VM_NAME"\"
   echo "STARTDELAY=60"
   echo "STOPDELAY=60"
) >"70-$VM_NAME"
