#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Make Tunnelbox Configuration
# Copyright (C) 2012-2013 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


import sys;

# NorNet
from NorNetAPI       import *;
from NorNetNodeSetup import *;


loginToPLC()

#fullSiteList = fetchNorNetSiteList(False)
# NOTE: Site list also includes disabled sites!
#fullNodeList = fetchNorNetNodeList()


rwSystemList = []
rwSystems = getFileServRWSystemsConfigurationString()
if rwSystems != None:
   parameters = re.split(r'''[ ]*(?=(?:[^'"]|'[^']*'|"[^"]*")*$)''', rwSystems)
   for i in range(0, len(parameters)):
      name = unquote(parameters[i])
      # print i, name
      # print resolveHostname(name, AF_INET)
      # print resolveHostname(name, AF_INET6)
      rwSystemList.append(name)


makeTFTPDConfiguration('tftpd-hpa')
makeNFSDConfiguration(rwSystemList, 'nfsd')
