#!/bin/sh

# ###### NorNet PLC configuration ###########################################
# NOTE:
# The following information is needed to access the PLC at the Central Site.
# It is mandatory for all NorNet PLC-database operations!

# This is the address of the PLC and the Central Site:
NorNetPLC_Address='10.1.1.2'

# These are the user name and corresponding password for accessing the PLC.
# SECURITY ADVICE:
# Use a user with restricted access permissions. For most operations (e.g.
# obtaining the node configurations), it is just sufficient to read the PLC
# database. Only modifying the configuration needs a more "powerful" user!
NorNetPLC_User='dummy@simula.nornet'
NorNetPLC_Password='dummy-password'


# ###### NorNet Node configuration ##########################################
# Node Index; needed,if if the node is not a PLC-managed node:
# This is also the case for tunnelboxes (in this case: always 1)!
NorNet_LocalNode_Index="1"

# This is the full hostname of the node:
NorNet_LocalNode_Hostname='fornebu.simula.nornet'

# This is the name of the NorNet interface (with the site's provider
# networks) of the node:
NorNet_LocalNode_NorNetInterface='eth0'

# ###### NorNet system user #################################################
# The NorNet user on this system. By default, it is 'nornetpp'.
# NorNet_LocalNode_NorNetUser='nornetpp'


# ###### NorNet Server configuration ########################################
# The default VNC password to access virtual systems on this host. It may be
# superseeded by VNCPASSWORD settings in the virtual systems configurations.
# NorNet_Server_DefaultVNCPassword=""


# ###### NorNet Tunnelbox configuration #####################################
# NOTE:
# The following information is only necessary to bootstrap a tunnelbox on the
# local site. For other nodes, the variables do not have to be set!

# This is the Site Index of the local site:
NorNet_LocalSite_SiteIndex=1

# This is the Provider Index of the local Default Provider:
NorNet_LocalSite_DefaultProviderIndex=1

# This is the local tunnelbox's outer IPv4 address for the default provider:
NorNet_LocalSite_TBDefaultProviderIPv4='128.39.36.143'

# DHCP configuration
NorNet_LocalSite_DHCPServer_Dynamic='"40" "49"'
NorNet_LocalSite_DHCPServer_Static242='"f0:de:f1:11:22:33"'
NorNet_LocalSite_DHCPServer_Static243='"f0:de:f1:aa:bb:cc" "pxe-boot.img"'
NorNet_LocalSite_DHCPServer_Static244='"f0:de:f1:aa:bb:ee" "pxe-boot.img" "pxe-server.simula.nornet"'

# NAT range for Central Site
NorNet_LocalSite_NAT_Range='"172.31.255.1" "172.31.255.9"'


# ###### Additional DNS names ###############################################
# Add additional, non-managed nodes here.
# The syntax is NorNet_LocalSite_Node<XXX>='"Hostname" "Hardware" "Type"',
# where <XXX> denotes the node index (i.e. 2 to 254).

NorNet_LocalSite_Node254='"skjennungen"    "HP DL-320"  "Physical Server #1"'
NorNet_LocalSite_Node253='"sognsvann"      "HP DL-320"  "Physical Server #2"'
NorNet_LocalSite_Node252='"svartkulp"      "HP DL-320"  "Physical Server #3"'
NorNet_LocalSite_Node251='"maridalsvannet" "HP DL-320"  "Physical Server #4"'
NorNet_LocalSite_Node250='"tryvann"        "HP DL-320"  "Physical Server #5"'
NorNet_LocalSite_Node249='"aaklungen"      "HP DL-320"  "Physical Server #6"'
NorNet_LocalSite_Node248='"bjordammen"     "HP DL-320"  "Physical Server #7"'
NorNet_LocalSite_Node247='"blanksjoe"      "HP DL-320"  "Physical Server #8"'

NorNet_LocalSite_Node2='"vigelandsparken"  "Amiga 8000" "NorNet PLC"'
NorNet_LocalSite_Node3='"holmenkollen"     "Amiga 8000" "NorNet Monitor"'
NorNet_LocalSite_Node4='"kirkeveien"       "Amiga 8000" "NorNet Display"'


# ###### File server read-write-permitted systems##############################
NorNet_FileServ_RWSystems='"kirkeveien.simula.nornet" "nordmarka.simula.nornet"'
