#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# NorNet Setup
# Copyright (C) 2012 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

import re;
import os;
import base64;

# Needs package python-ipaddr (Fedora Core, Ubuntu, Debian)!
from ipaddr import IPv4Address, IPv4Network, IPv6Address, IPv6Network;

# NorNet
from NorNetTools         import *;
from NorNetAPI           import *;
from NorNetProviderSetup import *;
from NorNetSiteSetup     import *;


norNetSetup = [
 { 'site_index'        : 1,
   'site_enabled'      : True,
   'site_long_name'    : u'Simula Research Laboratory',
   'site_short_name'   : 'SRL',
   'site_url'          : 'http://www.simula.nornet',
   'site_domain'       : 'simula.nornet',
   'site_city'         : 'Fornebu',
   'site_province'     : 'Akershus',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 59.895933,
   'site_longitude'    : 10.627635,
   'site_pcu'          : [ IPv4Address('128.39.36.131'), 'pcu-root', 'a-secret-password' ],
   'site_providers' : [
      [ 'Uninett',  'eth1', IPv4Address('128.39.36.143'), IPv6Address('::') ],
      [ 'Hafslund', 'eth2', IPv4Address('77.88.71.151'),  IPv6Address('::') ]
   ],
   'site_nodes' : [
      [ 100,  1, 'akerbrygge'      ],
      [ 101,  2, 'bygdoey'         ],
      [ 102,  3, 'tullinloekka'    ],
      [ 103,  4, 'frogner'         ],
      [ 104,  5, 'nordberg'        ],
      [ 105,  6, 'solvang'         ],
      [ 106,  7, 'nordreaker'      ],
      [ 107,  8, 'vestreaker'      ],
      [ 108,  9, 'ullevaal'        ],
      [ 109, 10, 'majorstuen'      ],
      [ 110, 11, 'vigelandsparken' ],
      [ 111, 12, 'holmenkollen'    ]
   ] },

 { 'site_index'        : 2,
   'site_enabled'      : True,
   'site_long_name'    : u'Universitetet i Oslo',
   'site_short_name'   : 'UiO',
   'site_url'          : 'http://www.uio.nornet',
   'site_domain'       : 'uio.nornet',
   'site_city'         : 'Oslo',
   'site_province'     : 'Oslo',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 59.944034,
   'site_longitude'    : 10.719013,
   'site_pcu'          : [ IPv4Address('129.240.66.61'), 'pcu-root', 'a-secret-password' ],
   'site_providers' : [
      [ 'Uninett', 'eth1', IPv4Address('129.240.66.60'), IPv6Address('::') ]
   ],
   'site_nodes' : [
      [ 100, 1, 'bjoervika' ],
      [ 101, 2, 'ekeberg'   ],
      [ 102, 3, 'furuset'   ],
      [ 103, 4, 'grefsen'   ],
      [ 104, 5, 'helsfyr'   ],
      [ 105, 6, 'toyen'     ]
   ] },

 { 'site_index'        : 3,
   'site_enabled'      : True,
   'site_long_name'    : u'Høgskolen i Gjøvik',
   'site_short_name'   : 'HiG',
   'site_url'          : 'http://www.hig.nornet',
   'site_domain'       : 'hig.nornet',
   'site_city'         : 'Gjøvik',
   'site_province'     : 'Oppland',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 60.789615,
   'site_longitude'    : 10.68166,
   'site_pcu'          : [ IPv4Address('128.39.49.154'), 'pcu-root', 'a-secret-password' ],
   'site_providers' : [
      [ 'Uninett', 'eth1', IPv4Address('128.39.49.154'),  IPv6Address('::') ]
   ],
   'site_nodes' : [
      [ 100, 1, 'kapp'      ],
      [ 101, 2, 'eina'      ],
      [ 102, 3, 'raufoss'   ],
      [ 103, 4, 'reinsvoll' ],
      [ 104, 5, 'skreia'    ],
      [ 105, 6, 'lena'      ]
   ] },

 { 'site_index'        : 4,
   'site_enabled'      : True,
   'site_long_name'    : u'Universitetet i Tromsø',
   'site_short_name'   : 'UiT',
   'site_url'          : 'http://www.uit.nornet',
   'site_domain'       : 'uit.nornet',
   'site_city'         : 'Tromsø',
   'site_province'     : 'Troms',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 69.681897,
   'site_longitude'    : 18.980541,
   'site_pcu'          : [ IPv4Address('129.242.157.229'), 'pcu-root', 'a-secret-password' ],
   'site_providers' : [
      [ 'Uninett', 'eth1', IPv4Address('129.242.157.228'), IPv6Address('::') ]
   ],
   'site_nodes' : [
      [ 100, 1, 'aunegaarden' ],
      [ 101, 2, 'egon'        ],
      [ 102, 3, 'arctandria'  ],
      [ 103, 4, 'lutefisk'    ],
      [ 104, 5, 'skarven'     ],
      [ 105, 6, 'steakers'    ]
   ] },

 { 'site_index'        : 5,
   'site_enabled'      : True,
   'site_long_name'    : u'Universitetet i Stavanger',
   'site_short_name'   : 'UiS',
   'site_url'          : 'http://www.uis.nornet',
   'site_domain'       : 'uis.nornet',
   'site_city'         : 'Stavanger',
   'site_province'     : 'Rogaland',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 58.938063,
   'site_longitude'    : 5.691172,
   'site_pcu'          : [ IPv4Address('152.94.1.7'), 'pcu-root', 'a-secret-password' ],
   'site_providers' : [
      [ 'Uninett', 'eth1', IPv4Address('152.94.1.7'), IPv6Address('::') ]
   ],
   'site_nodes' : [
      [ 100, 1, 'mosteroey'  ],
      [ 101, 2, 'klosteroey' ],
      [ 102, 3, 'askje'      ],
      [ 103, 4, 'sokn'       ],
      [ 104, 5, 'rennesoey'  ],
      [ 105, 6, 'fjoeloey'   ]
   ] },

 { 'site_index'        : 6,
   'site_enabled'      : True,
   'site_long_name'    : u'Universitetet i Bergen',
   'site_short_name'   : 'UiB',
   'site_url'          : 'http://www.uib.nornet',
   'site_domain'       : 'uib.nornet',
   'site_city'         : 'Bergen',
   'site_province'     : 'Hordaland',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 60.384904,
   'site_longitude'    : 5.328636,
   'site_pcu'          : [ IPv4Address('158.37.6.195'), 'pcu-root', 'a-secret-password' ],
   'site_providers' : [
      [ 'Uninett', 'eth1', IPv4Address('158.37.6.195'), IPv6Address('::') ]
   ],
   'site_nodes' : [
      [ 100, 1, 'floeibanen'        ],
      [ 101, 2, 'fisketorget'       ],
      [ 102, 3, 'ulriksbanen'       ],
      [ 103, 4, 'lungegaardsvannet' ],
      [ 104, 5, 'bergenhus'         ],
      [ 105, 6, 'sverresborg'       ]
   ] },

 { 'site_index'        : 7,
   'site_enabled'      : True,
   'site_long_name'    : u'Universitetet i Agder',
   'site_short_name'   : 'UiA',
   'site_url'          : 'http://www.uia.nornet',
   'site_domain'       : 'uia.nornet',
   'site_city'         : 'Kristiansand',
   'site_province'     : 'Vest-Agder',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 58.163833,
   'site_longitude'    : 8.002936,
   'site_pcu'          : [ IPv4Address('158.36.50.178'), 'pcu-root', 'a-secret-password' ],
   'site_providers' : [
      [ 'Uninett', 'eth1', IPv4Address('158.36.50.178'), IPv6Address('::') ]
   ],
   'site_nodes' : [
      [ 100, 1, 'julenissen'  ],
      [ 101, 2, 'fjoesnisse'  ],
      [ 102, 3, 'gaardsnisse' ],
      [ 103, 4, 'hagenisse'   ],
      [ 104, 5, 'skipsnisse'  ],
      [ 105, 6, 'kirkenisse'  ]
   ] },

 { 'site_index'        : 8,
   'site_enabled'      : False,
   'site_long_name'    : u'Universitetet i Trondheim',
   'site_short_name'   : 'NTNU',
   'site_url'          : 'http://www.ntnu.nornet',
   'site_domain'       : 'ntnu.nornet',
   'site_city'         : 'Trondheim',
   'site_province'     : 'Sør-Trøndelag',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 63.419034,
   'site_longitude'    : 10.4022,
   'site_pcu'          : [ IPv4Address('132.252.156.7'), 'pcu-root', 'a-secret-password' ],
   'site_providers' : [
      [ 'Uninett', 'eth1', IPv4Address('132.252.156.75'), IPv6Address('fd55:5555::75') ],
      [ 'Telenor', 'eth1', IPv4Address('169.254.100.75'), IPv6Address('::') ]
   ],
   'site_nodes' : [
      [ 100, 1, 'bjoern'   ],
      [ 101, 2, 'hund'     ],
      [ 102, 3, 'katt'     ],
      [ 103, 4, 'mus'      ]
   ] },

 { 'site_index'        : 9,
   'site_enabled'      : False,
   'site_long_name'    : u'Universitetet i Nordland',
   'site_short_name'   : 'UiN',
   'site_url'          : 'http://www.uin.nornet',
   'site_domain'       : 'uin.nornet',
   'site_city'         : 'Bodø',
   'site_province'     : 'Nordland',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 67.289645,
   'site_longitude'    : 14.560402,
   'site_pcu'          : [ IPv4Address('132.252.156.10'), 'pcu-root', 'a-secret-password' ],
   'site_providers' : [
      [ 'Uninett', 'eth1', IPv4Address('132.252.156.78'), IPv6Address('fd55:5555::78') ],
      [ 'Telenor', 'eth1', IPv4Address('169.254.100.78'), IPv6Address('::') ]
   ],
   'site_nodes' : [
      [ 100, 1, 'hydrogen'  ],
      [ 101, 2, 'helium'    ],
      [ 102, 3, 'litium'    ],
      [ 103, 4, 'beryllium' ]
   ] },

 { 'site_index'        : 10,
   'site_enabled'      : False,
   'site_long_name'    : u'Universitetet på Svalbard',
   'site_short_name'   : 'UNIS',
   'site_url'          : 'http://www.unis.nornet',
   'site_domain'       : 'unis.nornet',
   'site_city'         : 'Longyearbyen',
   'site_province'     : 'Svalbard',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 78.222972,
   'site_longitude'    : 15.648537,
   'site_pcu'          : [ IPv4Address('132.252.156.11'), 'pcu-root', 'a-secret-password' ],
   'site_providers' : [
      [ 'Uninett', 'eth1', IPv4Address('132.252.156.79'), IPv6Address('fd55:5555::79') ],
      [ 'Telenor', 'eth1', IPv4Address('169.254.100.79'), IPv6Address('::') ]
   ],
   'site_nodes' : [
      [ 100, 1, 'hval'     ],
      [ 101, 2, 'isbjoern' ],
      [ 102, 3, 'isbre'    ],
      [ 103, 4, 'nordlys'  ]
   ] },

 { 'site_index'        : 42,
   'site_enabled'      : False,
   'site_long_name'    : u'Universität Duisburg-Essen',
   'site_short_name'   : 'UDE',
   'site_url'          : 'http://www.ude.nornet',
   'site_domain'       : 'ude.nornet',
   'site_city'         : 'Essen',
   'site_province'     : 'Nordrhein-Westfalen',
   'site_country'      : 'Deutschland',
   'site_country_code' : 'DE',
   'site_latitude'     : 51.476144,
   'site_longitude'    : 7.011656,
   'site_pcu'          : [ IPv4Address('132.252.156.12'), 'pcu-root', 'a-secret-password' ],
   'site_providers' : [
      [ 'Deutsches Forschungsnetz', 'eth0', IPv4Address('172.31.255.100'),  IPv6Address('::') ],
      [ 'Uninett',                  'eth1', IPv4Address('132.252.156.100'), IPv6Address('fd55:5555::100') ],
      [ 'Telenor',                  'eth2', IPv4Address('169.254.100.100'), IPv6Address('::') ]
   ],
   'site_nodes' : [
      [ 100, 1, 'altenessen'  ],
      [ 101, 2, 'baldeneysee' ],
      [ 102, 3, 'borbeck'     ],
      [ 103, 4, 'kettwig'     ],
      [ 104, 5, 'kray'        ],
      [ 105, 6, 'kupferdreh'  ],
      [ 106, 7, 'steele'      ],
      [ 107, 8, 'zollverein'  ]
   ] }

]


# ###### Remove site ########################################################
def removeSite(site):
   if site == None:
      fullSiteList = fetchNorNetSiteList()
      if fullSiteList != None:
         for siteIndex in fullSiteList:
            site = fullSiteList[siteIndex]
            removeNorNetSite(site['site_long_name'])
   else:
      removeNorNetSite(site['site_long_name'])


# ###### Add site ###########################################################
def makeSite(site, norNetInformation, dnsServers, ntpServers):
   # ====== Add tag types ===================================================
   makeNorNetTagTypes()

   # ====== Make site ========================================================
   siteIndex = site['site_index']

   newSite = makeNorNetSite(site['site_long_name'], site['site_short_name'], site['site_enabled'], str.lower(site['site_short_name']),
                            site['site_url'], site['site_domain'], siteIndex,
                            site['site_city'], site['site_province'], site['site_country'], site['site_country_code'],
                            site['site_latitude'], site['site_longitude'],
                            site['site_providers'],
                            site['site_providers'][0][0], site['site_providers'][0][1],
                            dnsServers, ntpServers)
   newPCU = makeNorNetPCU(newSite, 'pcu', site['site_domain'],
                          site['site_pcu'][0], site['site_pcu'][1], site['site_pcu'][2],
                          'ssh', 'Amiga 5099', 'Jeg vet ikke.')

   # ====== Make nodes ======================================================
   i = 100
   for node in site['site_nodes']:
      address = node[0]
      if address <= 0:
         address = i
      port = node[1]
      if port <= 0:
        port = i
      makeNorNetNode(newSite, node[2], address, newPCU, port, 'eth0', 'Amiga 5000', 'reinstall')


# ###### Make test setup ####################################################
def getBootISOs(isoDirectory):
   allNorNetNodes = fetchNorNetNodeList()
   for node in allNorNetNodes:
      nodeID   = node['node_id']
      nodeName = node['node_name']
      isoName  = os.path.normpath(os.path.join(isoDirectory, nodeName + '.iso'))
      if not os.path.exists(isoName):
         log('Downloading ' + isoName + ' ...')
         try:
            isoBase64 = getPLCServer().GetBootMedium(getPLCAuthentication(), nodeID, 'node-iso' , '', [])
            iso       = base64.b64decode(isoBase64)
            outputFile = open(isoName, 'w')
            outputFile.write(iso)
            outputFile.close()
         except:
            error('Unable to generate ' + isoName + '!')

      else:
         log('Not downloading ' + isoName + ', it already exists!')


# ###### Perform site action ################################################
def performAction(action, site):
   if ((action == 'remove') or (action == 'renew')):
      removeSite(site)
   if ((action == 'add') or (action == 'renew')):
      makeSite(site, norNetInformation, dnsServers, ntpServers)



# ###### Main program #######################################################
action = ''
if len(sys.argv) > 2:
   if sys.argv[1] == 'add':
      action = 'add'
   elif sys.argv[1] == 'renew':
      action = 'renew'
   elif sys.argv[1] == 'remove':
      action = 'remove'
   elif sys.argv[1] == 'manage':
      action = 'manage'
if action == '':
   error('Usage: ' + sys.argv[0] + ' add|renew|remove|manage Site|ALL [Site] ... [--user=user_name] [--slice=slice_name]')


log('***** Welcome to NorNet! *****')
loginToPLC()


# ====== Some server settings ===============================================
norNetInformation = getNorNetInformationForAddress(getPLCAddress())
plcNodeIndex      = norNetInformation['node_index']
dnsServers = [ makeNorNetIP(NorNet_SiteIndex_Central, NorNet_CentralSite_BootstrapProviderIndex, plcNodeIndex, -1, 4),
               makeNorNetIP(NorNet_SiteIndex_Central, NorNet_CentralSite_BootstrapProviderIndex, plcNodeIndex, -1, 6) ]
ntpServerNames = [ 'ntp1.ptb.de', 'ntp2.ptb.de', 'ntp3.ptb.de',   # The PTB servers (very reliable sources)
                   'ntp1.uio.no', 'ntp2.uio.no' ]                 # UiO (nearby)

ntpServers = []
for ntpServer in ntpServerNames:
   ntpAddress = resolveHostname(ntpServer, AF_INET6)
   if ntpAddress != None:
      ntpServers.append(ntpAddress)
   ntpAddress = resolveHostname(ntpServer, AF_INET)
   if ntpAddress != None:
      ntpServers.append(ntpAddress)
# ===========================================================================


# ====== Add tag types ======================================================
if ((action == 'add') or (action == 'renew')):
   makeNorNetTagTypes()


# ====== Remove or create sites =============================================
if str.upper(sys.argv[2]) == 'ALL':
   if ((action == 'remove') or (action == 'renew')):
      removeSite(None)
   if action != 'remove':
      for site in norNetSetup:
         performAction(action, site)
   i = 3
else:
   i = 2

userID       = 0
sliceID      = 0
isoDirectory = None
while i < len(sys.argv):
   match = re.search('^--([a-z]*)=(.*)', sys.argv[i])
   if ((match != None) and (match.group(1) == 'user')):
      userName = match.group(2)
      userID   = lookupPersonID(userName)
      if userID == 0:
         error('Unable to find user ' + userName + '\n')

   elif ((match != None) and (match.group(1) == 'slice')):
      sliceName = match.group(2)
      sliceID   = lookupSliceID(sliceName)
      if sliceID == 0:
         error('Unable to find slice ' + sliceName + '\n')

   elif ((match != None) and (match.group(1) == 'isodirectory')):
      isoDirectory = match.group(2)

   else:
      found = None
      for site in norNetSetup:
         if ((site['site_long_name'] == sys.argv[i]) or
             (site['site_short_name'] == sys.argv[i])):
            found = site
            break
      if found == None:
         error('Site "' + sys.argv[i] + '" is not defined!')
      performAction(action, found)

   i = i + 1


# ====== Set user ===========================================================
if userID != 0:
   log('Setting PI for all sites ...')
   getPLCServer().AddRoleToPerson(getPLCAuthentication(), 'user', userID)
   getPLCServer().AddRoleToPerson(getPLCAuthentication(), 'pi',   userID)
   getPLCServer().AddRoleToPerson(getPLCAuthentication(), 'tech', userID)
   # ====== Add user to all sites ===========================================
   allNorNetSites = fetchNorNetSiteList(False)
   for siteIndex in allNorNetSites:
      site = allNorNetSites[siteIndex]
      getPLCServer().AddPersonToSite(getPLCAuthentication(), userID, site['site_id'])
      if site['site_id'] == NorNet_SiteIndex_Central:
         getPLCServer().SetPersonPrimarySite(getPLCAuthentication(), userID, site['site_id'])

# ====== Set slice ==========================================================
if sliceID != 0:
   log('Adding slice to all nodes ...')
   # ====== Add slice to all nodes ==========================================
   nodeIDs = []
   allNorNetNodes = fetchNorNetNodeList()
   for node in allNorNetNodes:
      nodeIDs.append(int(node['node_id']))
   getPLCServer().AddSliceToNodes(getPLCAuthentication(), sliceID, nodeIDs)

# ====== Get boot ISOs ======================================================
if isoDirectory != None:
   getBootISOs(isoDirectory)
