#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# NorNet Setup
# Copyright (C) 2012-2015 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

import re;
import os;
import base64;

# Needs package python-ipaddr (Fedora Core, Ubuntu, Debian)!
from ipaddr import IPv4Address, IPv4Network, IPv6Address, IPv6Network;

# NorNet
from NorNetTools         import *;
from NorNetAPI           import *;
from NorNetProviderSetup import *;
from NorNetSiteSetup     import *;


norNetSetup = [
 { 'site_index'        : 1,
   'site_enabled'      : True,
   'site_long_name'    : u'Simula Research Laboratory',
   'site_short_name'   : 'SRL',
   'site_url'          : 'https://www.simula.no',
   'site_domain'       : 'simula.nornet',
   'site_city'         : 'Fornebu',
   'site_province'     : 'Akershus',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 59.895933,
   'site_longitude'    : 10.627635,
   'site_altitude'     : 15,
   'site_contacts'     : [ u'Dreibholz, Thomas: dreibh@simula.no', u'Elmokashfi, Ahmed: ahmed@simula.no', u'Werme, Jonas: jonasw@simula.no' ],
   'site_pcu'          : [ IPv4Address('158.39.4.3'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'Uninett',  'eth1',
           IPv4Network('158.39.4.2/24'),                     IPv4Address('158.39.4.1'),
           IPv6Network('2001:700:4100:4::2/64'),             IPv6Address('2001:700:4100:4::1'),
           1500, 'fibre, business', 0, 0 ],
      [ u'Kvantel', 'eth2',
           IPv4Network('77.88.71.151/26'),                   IPv4Address('77.88.71.133'),
           IPv6Network('2a02:270:2014:111:77:88:71:151/64'), IPv6Address('2a02:270:2014:111::1'),
           1500, 'fibre, business', 0, 0 ],
      [ u'Telenor', 'eth3',
           IPv4Network('62.92.88.42/30'),                    IPv4Address('62.92.88.41'),
           IPv6Network('::/0'),                              IPv6Address('::'),
           1492, 'ADSL, consumer', 0, 0 ],
      [ u'PowerTech', 'eth4',
           IPv4Network('80.241.88.26/29'),                   IPv4Address('80.241.88.25'),
           IPv6Network('2001:840:4ad5::34/64'),              IPv6Address('2001:840:4ad5::1'),
           1492, 'ADSL, consumer', 0, 0 ]
   ],
   'site_nodes' : [
      [ 100,  1, u'akerbrygge',  'sognsvann.simula.nornet',      'vnc://sognsvann.simula.nornet:5700'      ],
      [ 101,  2, u'bygdøy',      'sognsvann.simula.nornet',      'vnc://sognsvann.simula.nornet:5701'      ],
      [ 102,  3, u'tullinløkka', 'svartkulp.simula.nornet',      'vnc://svartkulp.simula.nornet:5700'      ],
      [ 103,  4, u'frogner',     'svartkulp.simula.nornet',      'vnc://svartkulp.simula.nornet:5701'      ],
      [ 104,  5, u'nordberg',    'maridalsvannet.simula.nornet', 'vnc://maridalsvannet.simula.nornet:5700' ],
      [ 105,  6, u'solvang',     'maridalsvannet.simula.nornet', 'vnc://maridalsvannet.simula.nornet:5701' ],
      [ 106,  7, u'nordreaker',  'blanksjoe.simula.nornet',      'vnc://blanksjoe.simula.nornet:5700'      ],
      [ 107,  8, u'vestreaker',  'blanksjoe.simula.nornet',      'vnc://blanksjoe.simula.nornet:5701'      ],
      [ 108,  9, u'skøyen' ,     'tryvann.simula.nornet',        'vnc://tryvann.simula.nornet:5700'        ],
      [ 109, 10, u'vækerø',      'tryvann.simula.nornet',        'vnc://tryvann.simula.nornet:5701'        ],
      [ 110, 11, u'akerselva',   'aaklungen.simula.nornet',      'vnc://aaklungen.simula.nornet:5700'      ],
      [ 111, 12, u'ullern',      'aaklungen.simula.nornet',      'vnc://aaklungen.simula.nornet:5701'      ],

      # --- Test only! ---
      #[ 117, 18, u'vmtest1'     ],
      #[ 118, 19, u'vmtest2'     ],
      [ 119, 20, u'test'        ]
   ] },

 { 'site_index'        : 2,
   'site_enabled'      : True,
   'site_long_name'    : u'Universitetet i Oslo',
   'site_short_name'   : 'UiO',
   'site_url'          : 'http://www.uio.no',
   'site_domain'       : 'uio.nornet',
   'site_city'         : 'Oslo',
   'site_province'     : 'Oslo',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 59.944034,
   'site_longitude'    : 10.719013,
   'site_altitude'     : 100,
   'site_contacts'     : [ u'IT-Ooperations@IFI/UiO: drift@ifi.uio.no', u'Welzl, Michael: michawe@ifi.uio.no', u'Håkedal, Lars: larsha@ifi.uio.no' ],
   'site_pcu'          : [ IPv4Address('129.240.66.75'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'Uninett', 'eth1',
           IPv4Network('129.240.66.74/29'),       IPv4Address('129.240.66.73'),
           IPv6Network('2001:700:100:279::4/64'), IPv6Address('2001:700:100:279::1'),
           1500, 'fibre, business', 0, 0 ],
      [ u'PowerTech', 'eth2',
           IPv4Network('195.159.158.198/30'),     IPv4Address('195.159.158.197'),
           IPv6Network('2001:840:4abd::4/64'),    IPv6Address('2001:840:4abd::1'),
           1492, 'ADSL, consumer', 0, 0 ],
      [ u'Broadnet', 'eth3',
           IPv4Network('85.252.121.218/30'),     IPv4Address('85.252.121.217'),
           IPv6Network('::/0'),                   IPv6Address('::'),
           1492, 'ADSL, consumer', 0, 0 ]
   ],
   'site_nodes' : [
      [ 100, 1, u'bjørvika', 'langevann.uio.nornet', 'vnc://langevann.uio.nornet:5700' ],
      [ 101, 2, u'ekeberg',  'langevann.uio.nornet', 'vnc://langevann.uio.nornet:5701' ],
      [ 102, 3, u'furuset',  'kringla.uio.nornet',   'vnc://kringla.uio.nornet:5700'   ],
      [ 103, 4, u'grefsen',  'kringla.uio.nornet',   'vnc://kringla.uio.nornet:5701'   ],
      [ 104, 5, u'helsfyr',  'smaavann.uio.nornet',  'vnc://smaavann.uio.nornet:5700'  ],
      [ 105, 6, u'tøyen',    'smaavann.uio.nornet',  'vnc://smaavann.uio.nornet: 5701' ]
   ] },

 { 'site_index'        : 3,
   'site_enabled'      : True,
   'site_long_name'    : u'Høgskolen i Gjøvik',
   'site_short_name'   : 'HiG',
   'site_url'          : 'https://www.hig.no',
   'site_domain'       : 'hig.nornet',
   'site_city'         : 'Gjøvik',
   'site_province'     : 'Oppland',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 60.789615,
   'site_longitude'    : 10.68166,
   'site_altitude'     : 200,
   'site_contacts'     : [ u'IT-operations@HiG: helpdesk@hig.no', u'Langseth, Jon: jon.langseth@hig.no', u'Hjelmås, Erik: erikh@hig.no' ],
   'site_pcu'          : [ IPv4Address('128.39.49.165'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'Uninett', 'eth1',
           IPv4Network('128.39.49.154/25'),         IPv4Address('128.39.49.129'),
           IPv6Network('2001:700:1d00:18::154/64'), IPv6Address('2001:700:1d00:18::1'),
           1500, 'fibre, business', 0, 0 ],
      [ u'PowerTech', 'eth2',
           IPv4Network('195.159.158.254/30'),       IPv4Address('195.159.158.253'),
           IPv6Network('2001:840:490b::254/64'),    IPv6Address('2001:840:490b::1'),
           1492, 'ADSL, consumer', 0, 0 ]
   ],
   'site_nodes' : [
      [ 100, 1, u'kapp',      'fjellhallen.hig.nornet', 'vnc://fjellhallen.hig.nornet:5700' ],
      [ 101, 2, u'eina',      'fjellhallen.hig.nornet', 'vnc://fjellhallen.hig.nornet:5701' ],
      [ 102, 3, u'raufoss',   'skibladner.hig.nornet',  'vnc://skibladner.hig.nornet:5700'  ],
      [ 103, 4, u'reinsvoll', 'skibladner.hig.nornet',  'vnc://skibladner.hig.nornet:5701'  ],
      [ 104, 5, u'skreia',    'toten.hig.nornet',       'vnc://toten.hig.nornet:5700'       ],
      [ 105, 6, u'lena',      'toten.hig.nornet',       'vnc://toten.hig.nornet:5701'       ]
   ] },

 { 'site_index'        : 4,
   'site_enabled'      : True,
   'site_long_name'    : u'Universitetet i Tromsø',
   'site_short_name'   : 'UiT',
   'site_url'          : 'http://www.uit.no',
   'site_domain'       : 'uit.nornet',
   'site_city'         : 'Tromsø',
   'site_province'     : 'Troms',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 69.681897,
   'site_longitude'    : 18.980541,
   'site_altitude'     : 50,
   'site_contacts'     : [ u'Wulff Hauglann, Maria: maria.wulff.hauglann@uit.no', u'Brunes, Børge: borge.brunes@uit.no', u'Anshus, Otto: otto.anshus@uit.no' ],
   'site_pcu'          : [ IPv4Address('129.242.157.229'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'Uninett', 'eth1',
           IPv4Network('129.242.157.228/28'),    IPv4Address('129.242.157.225'),
           IPv6Network('::/0'),                  IPv6Address('::'),
           1500, 'fibre, business', 0, 0 ],
      [ u'PowerTech', 'eth2',
           IPv4Network('195.159.158.162/30'),    IPv4Address('195.159.158.161'),
           IPv6Network('2001:840:490c::162/64'), IPv6Address('2001:840:490c::1'),
           1492, 'ADSL, consumer', 0, 0 ],
      [ u'Telenor', 'eth3',
           IPv4Network('62.92.89.210/30'),       IPv4Address('62.92.89.209'),
           IPv6Network('::/0'),                  IPv6Address('::'),
           1492, 'ADSL, consumer', 0, 0 ]
   ],
   'site_nodes' : [
      [ 100, 1, u'amundsen',    'ishav.uit.nornet',       'vnc://ishav.uit.nornet:5700'       ],
      [ 101, 2, u'nansen',      'ishav.uit.nornet',       'vnc://ishav.uit.nornet:5701'       ],
      [ 102, 3, u'aunegården',  'polaria.uit.nornet',     'vnc://polaria.uit.nornet:5700'     ],
      [ 103, 4, u'skarven',     'polaria.uit.nornet',     'vnc://polaria.uit.nornet:5701'     ],
      [ 104, 5, u'arctandria',  'tromsoebrua.uit.nornet', 'vnc://tromsoebrua.uit.nornet:5700' ],
      [ 105, 6, u'kongsbakken', 'tromsoebrua.uit.nornet', 'vnc://tromsoebrua.uit.nornet:5701' ]
   ] },

 { 'site_index'        : 5,
   'site_enabled'      : True,
   'site_long_name'    : u'Universitetet i Stavanger',
   'site_short_name'   : 'UiS',
   'site_url'          : 'https://www.uis.no',
   'site_domain'       : 'uis.nornet',
   'site_city'         : 'Stavanger',
   'site_province'     : 'Rogaland',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 58.938063,
   'site_longitude'    : 5.691172,
   'site_altitude'     : 25,
   'site_contacts'     : [ u'Ivesdal, Theodor: theo@ux.uis.no', u'Meling, Hein: hein.meling@uis.no' ],
   'site_pcu'          : [ IPv4Address('152.94.120.7'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'Uninett', 'eth1',
           IPv4Network('152.94.120.6/24'),       IPv4Address('152.94.120.1'),
           IPv6Network('::/0'),                  IPv6Address('::'),
           1500, 'fibre, business', 0, 0 ],
      [ u'PowerTech', 'eth2',
           IPv4Network('195.159.158.210/30'),    IPv4Address('195.159.158.209'),
           IPv6Network('2001:840:4908::210/64'), IPv6Address('2001:840:4908::1'),
           1492, 'ADSL, consumer', 0, 0 ],
      [ u'Altibox', 'eth3',
           IPv4Network('79.161.4.42/30'),        IPv4Address('79.161.4.41'),
           IPv6Network('2a01:798:1:9::1/127'),   IPv6Address('2a01:798:1:9::'),
           1492, 'ADSL, consumer', 0, 0 ]
   ],
   'site_nodes' : [
      [ 100, 1, u'mosterøy',  'petroleum.uis.nornet', 'vnc://petroleum.uis.nornet:5700' ],
      [ 101, 2, u'klosterøy', 'petroleum.uis.nornet', 'vnc://petroleum.uis.nornet:5701' ],
      [ 102, 3, u'askje',     'bensin.uis.nornet',    'vnc://bensin.uis.nornet:5700'    ],
      [ 103, 4, u'sokn',      'bensin.uis.nornet',    'vnc://bensin.uis.nornet:5701'    ],
      [ 104, 5, u'rennesoey', 'diesel.uis.nornet',    'vnc://diesel.uis.nornet:5700'    ],
      [ 105, 6, u'fjøløy',    'diesel.uis.nornet',    'vnc://diesel.uis.nornet:5701'    ]
   ] },

 { 'site_index'        : 6,
   'site_enabled'      : True,
   'site_long_name'    : u'Universitetet i Bergen',
   'site_short_name'   : 'UiB',
   'site_url'          : 'http://www.uib.no',
   'site_domain'       : 'uib.nornet',
   'site_city'         : 'Bergen',
   'site_province'     : 'Hordaland',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 60.384904,
   'site_longitude'    : 5.328636,
   'site_altitude'     : 50,
   'site_contacts'     : [ u'Lædre, Tor: tor.ladre@it.uib.no', u'Johnsen, Jan Kristian Walde: jan.johnsen@adm.uib.no' ],
   'site_pcu'          : [ IPv4Address('158.37.6.194'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'Uninett', 'eth1',
           IPv4Network('158.37.6.195/26'),           IPv4Address('158.37.6.193'),
           IPv6Network('2001:700:201:F002::195/64'), IPv6Address('2001:700:201:F002::1'),
           1500, 'fibre, business', 0, 0 ],
      [ u'Bergenshalvøens Kommunale Kraftselskap', 'eth2',
           IPv4Network('62.97.202.70/30'),           IPv4Address('62.97.202.69'),
           IPv6Network('2A00:14D8:1001:556::2/126'), IPv6Address('2A00:14D8:1001:556::1'),
           1500, 'fibre, business', 0, 0 ]
   ],
   'site_nodes' : [
      [ 100, 1, u'fløibanen',        'floeyfjellet.uib.nornet',      'vnc://floeyfjellet.uib.nornet:5700'      ],
      [ 101, 2, u'fisketorget',      'floeyfjellet.uib.nornet',      'vnc://floeyfjellet.uib.nornet:5701'      ],
      [ 102, 3, u'ulriksbanen',      'ulriken.uib.nornet',           'vnc://ulriken.uib.nornet:5700'           ],
      [ 103, 4, u'lungegårdsvannet', 'ulriken.uib.nornet',           'vnc://ulriken.uib.nornet:5701'           ],
      [ 104, 5, u'bergenhus',        'damsgaardsfjellet.uib.nornet', 'vnc://damsgaardsfjellet.uib.nornet:5700' ],
      [ 105, 6, u'sverresborg',      'damsgaardsfjellet.uib.nornet', 'vnc://damsgaardsfjellet.uib.nornet:5701' ],
   ] },

 # ====== Universitetet i Agder =============================================
 # Server #1 at UiA: 158.36.50.179 / 2001:700:1500:c064::179
 # Server #2 at UiA: 158.36.50.180 / 2001:700:1500:c064::180
 # Server #3 at UiA: 158.36.50.181 / 2001:700:1500:c064::181
 # Server #4 at UiA: 158.36.50.182 / 2001:700:1500:c064::182
 { 'site_index'        : 7,
   'site_enabled'      : True,
   'site_long_name'    : u'Universitetet i Agder',
   'site_short_name'   : 'UiA',
   'site_url'          : 'https://www.uia.no',
   'site_domain'       : 'uia.nornet',
   'site_city'         : 'Kristiansand',
   'site_province'     : 'Vest-Agder',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 58.163833,
   'site_longitude'    : 8.002936,
   'site_altitude'     : 50,
   'site_contacts'     : [ u'Kittelsen, Rune: rune.kittelsen@uia.no', u'Prinz, Andreas: andreas.prinz@uia.no' ],
   'site_pcu'          : [ IPv4Address('158.36.50.179'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'Uninett', 'eth1',
           IPv4Network('158.36.50.178/29'),         IPv4Address('158.36.50.177'),
           IPv6Network('2001:700:1500:c064::2/64'), IPv6Address('2001:700:1500:c064::1'),
           1500, 'fibre, business', 0, 0 ],
      [ u'PowerTech', 'eth2',
           IPv4Network('195.159.203.50/30'),        IPv4Address('195.159.203.49'),
           IPv6Network('2001:840:490a::50/64'),     IPv6Address('2001:840:490a::1'),
           1492, 'ADSL, consumer', 0, 0 ]
      #[ u'Broadnet', 'eth3',
           #IPv4Network('193.69.209.10'),            IPv4Address('193.69.209.9'),
           #IPv6Network('::/0'),                     IPv6Address('::'),
           #1492, 'ADSL, consumer', 0, 0 ]
   ],
   'site_nodes' : [
      [ 100, 1, u'julenisse',    'wergeland.uia.nornet', 'vnc://wergeland.uia.nornet:5700' ],
      [ 101, 2, u'fjøsnisse',    'wergeland.uia.nornet', 'vnc://wergeland.uia.nornet:5701' ],
      [ 102, 3, u'gårdsnisse',   'holberg.uia.nornet',   'vnc://holberg.uia.nornet:5700'   ],
      [ 103, 4, u'hagenisse',    'holberg.uia.nornet',   'vnc://holberg.uia.nornet:5701'   ],
      [ 104, 5, u'skipsnisse',   'andersen.uia.nornet',  'vnc://andersen.uia.nornet:5700'  ],
      [ 105, 6, u'heinzelnisse', 'andersen.uia.nornet',  'vnc://andersen.uia.nornet:5701'  ]
   ] },

 { 'site_index'        : 8,
   'site_enabled'      : True,
   'site_long_name'    : u'Universitetet på Svalbard',
   'site_short_name'   : 'UNIS',
   'site_url'          : 'http://www.unis.no',
   'site_domain'       : 'unis.nornet',
   'site_city'         : 'Longyearbyen',
   'site_province'     : 'Svalbard',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 78.222652,
   'site_longitude'    : 15.653273,
   'site_altitude'     : 20,
   'site_contacts'     : [ u'Eggenfellner, Heinrich: heinrich@unis.no' ],
   'site_pcu'          : [ IPv4Address('158.39.149.133'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'Uninett', 'eth1',
           IPv4Network('158.39.149.132/25'), IPv4Address('158.39.149.129'),
           IPv6Network('::/0'),              IPv6Address('::'),
           1500, 'fibre, business', 0, 0 ],
      [ u'Telenor', 'eth2',
           IPv4Network('193.213.19.83/20'), IPv4Address('193.213.16.1'),
           IPv6Network('::/0'),              IPv6Address('::'),
           1500, 'fibre, consumer', 0, 0 ]
   ],
   'site_nodes' : [
      [ 100, 1, u'snøflak',       'fjellrev.unis.nornet', 'vnc://fjellrev.unis.nornet:5700'  ],
      [ 101, 2, u'isbre',         'fjellrev.unis.nornet', 'vnc://fjellrev.unis.nornet:5701'  ],
      [ 102, 3, u'nordlys',       'hval.unis.nornet',     'vnc://hval.unis.nornet:5700'      ],
      [ 103, 4, u'midnattssol',   'hval.unis.nornet',     'vnc://hval.unis.nornet:5701'      ],
      [ 104, 5, u'adventfjorden', 'sel.unis.nornet',      'vnc://sel.unis.nornet:5700'       ],
      [ 105, 6, u'isfjorden',     'sel.unis.nornet',      'vnc://sel.unis.nornet:5701'       ]
   ] },

 { 'site_index'        : 9,
   'site_enabled'      : True,
   'site_long_name'    : u'Universitetet i Trondheim',
   'site_short_name'   : 'NTNU',
   'site_url'          : 'https://www.ntnu.no',
   'site_domain'       : 'ntnu.nornet',
   'site_city'         : 'Trondheim',
   'site_province'     : 'Sør-Trøndelag',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 63.418003,
   'site_longitude'    : 10.401625,
   'site_altitude'     : 50,
   'site_contacts'     : [ u'Sæther, Pål S.: palss@item.ntnu.no', u'Helvik, Bjarne E.: bjarne@item.ntnu.no' ],
   'site_pcu'          : [ IPv4Address('129.241.200.129'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'Uninett', 'eth1',
           IPv4Network('129.241.200.128/24'),        IPv4Address('129.241.200.1'),
           IPv6Network('2001:700:300:2211::128/64'), IPv6Address('2001:700:300:2211::1'),
           1500, 'fibre, business', 0, 0 ],
      [ u'PowerTech', 'eth2',
           IPv4Network('195.159.158.134/30'),        IPv4Address('195.159.158.133'),
           IPv6Network('2001:840:490e::134/64'),     IPv6Address('2001:840:490e::1'),
           1492, 'ADSL, consumer', 0, 0 ]
   ],
   'site_nodes' : [
      [ 100, 1, u'bybro',      'munkholmen.ntnu.nornet',   'vnc://munkholmen.ntnu.nornet:5700'   ],
      [ 101, 2, u'bakklandet', 'munkholmen.ntnu.nornet',   'vnc://munkholmen.ntnu.nornet:5701'   ],
      [ 102, 3, u'byåsen',     'kristiansten.ntnu.nornet', 'vnc://kristiansten.ntnu.nornet:5700' ],
      [ 103, 4, u'lerkendal',  'kristiansten.ntnu.nornet', 'vnc://kristiansten.ntnu.nornet:5701' ],
      [ 104, 5, u'bymarka',    'nidelva.ntnu.nornet',      'vnc://nidelva.ntnu.nornet:5700'      ],
      [ 105, 6, u'heimdal',    'nidelva.ntnu.nornet',      'vnc://nidelva.ntnu.nornet:5701'      ]
   ] },

 { 'site_index'        : 10,
   'site_enabled'      : True,
   'site_long_name'    : u'Høgskolen i Narvik',
   'site_short_name'   : 'HiN',
   'site_url'          : 'http://www.hin.no',
   'site_domain'       : 'hin.nornet',
   'site_city'         : 'Narvik',
   'site_province'     : 'Nordland',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 68.436023,
   'site_longitude'    : 17.434984,
   'site_altitude'     : 75,
   'site_contacts'     : [ u'Pettersen, Ørjan Dypvik: orjan.dypvik.pettersen@hin.no', u'Bråthen Roger: roger.brathen@hin.no' ],
   'site_pcu'          : [ IPv4Address('158.39.93.232'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'Uninett', 'eth1',
           IPv4Network('158.39.93.231/27'),         IPv4Address('158.39.93.225'),
           IPv6Network('2001:700:c00:150::231/64'), IPv6Address('2001:700:c00:150::1'),
           1500, 'fibre, business', 0, 0 ],
      [ u'PowerTech', 'eth2',
           IPv4Network('195.159.158.174/30'),       IPv4Address('195.159.158.173'),
           IPv6Network('2001:840:490d::174/64'),    IPv6Address('2001:840:490d::1'),
           1492, 'ADSL, consumer', 0, 0 ],
      [ u'Broadnet', 'eth3',
           IPv4Network('85.252.123.242/30'),        IPv4Address('85.252.123.241'),
           IPv6Network('::/0'),                     IPv6Address('::'),
           1492, 'ADSL, consumer', 0, 0 ]
   ],
   'site_nodes' : [
      [ 100, 1, u'storsteinsfjellet', 'herjangsfjorden.hin.nornet', 'vnc://herjangsfjorden.hin.nornet:5700' ],
      [ 101, 2, u'nihkevarri',        'herjangsfjorden.hin.nornet', 'vnc://herjangsfjorden.hin.nornet:5701' ],
      [ 102, 3, u'beisfjordtøtta',    'skjomen.hin.nornet',         'vnc://skjomen.hin.nornet:5700'         ],
      [ 103, 4, u'rombakstøtta',      'skjomen.hin.nornet',         'vnc://skjomen.hin.nornet:5701'         ],
      [ 104, 5, u'bjørnfjell',        'beisfjorden.hin.nornet',     'vnc://beisfjorden.hin.nornet:5700'     ],
      [ 105, 6, u'fagernesfjellet',   'beisfjorden.hin.nornet',     'vnc://beisfjorden.hin.nornet:5701'     ]
   ] },

 { 'site_index'        : 11,
   'site_enabled'      : True,
   'site_long_name'    : u'Høgskolen i Oslo og Akershus',
   'site_short_name'   : 'HiOA',
   'site_url'          : 'http://www.hioa.no',
   'site_domain'       : 'hioa.nornet',
   'site_city'         : 'Oslo',
   'site_province'     : 'Oslo',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 59.921732,
   'site_longitude'    : 10.735502,
   'site_altitude'     : 20,
   'site_contacts'     : [ u'Ahmed, Amir Maqbool: amir-maqbool.ahmed@hioa.no', u'Hassan, Ismail: Ismail.Hassan@hioa.no', u'Haugerud, Hårek: Harek.Haugerud@hioa.no' ],
   'site_pcu'          : [ IPv4Address('128.39.120.63'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'Uninett', 'eth1',
           IPv4Network('128.39.120.60/23'),       IPv4Address('128.39.120.1'),
           IPv6Network('2001:700:700:22::60/64'), IPv6Address('2001:700:700:22::'),
           1500, 'fibre, business', 0, 0 ]
   ],
   # Server #251: 128.39.120.63
   # Server #252: 128.39.120.62
   # Server #253: 128.39.120.61
   'site_nodes' : [
      [ 100, 1, u'hovedøya',    'dalsbergstien.hioa.nornet', 'vnc://dalsbergstien.hioa.nornet:5700' ],
      [ 101, 2, u'lindøya',     'dalsbergstien.hioa.nornet', 'vnc://dalsbergstien.hioa.nornet:5701' ],
      [ 102, 3, u'nakholmen',   'dalsbergstien.hioa.nornet', 'vnc://dalsbergstien.hioa.nornet:5702' ],
      [ 103, 4, u'gressholmen', 'holbergsplass.hioa.nornet', 'vnc://holbergsplass.hioa.nornet:5700' ],
      [ 104, 5, u'bleikøya',    'holbergsplass.hioa.nornet', 'vnc://holbergsplass.hioa.nornet:5701' ],
      [ 105, 6, u'langøyene',   'holbergsplass.hioa.nornet', 'vnc://holbergsplass.hioa.nornet:5702' ],
      [ 106, 7, u'heggholmen',  'pilestredet.hioa.nornet',   'vnc:/pilestredet.hioa.nornet/:5700'   ],
      [ 107, 8, u'rambergøya',  'pilestredet.hioa.nornet',   'vnc://pilestredet.hioa.nornet:5701'   ],
      [ 108, 9, u'vippetangen', 'pilestredet.hioa.nornet',   'vnc://pilestredet.hioa.nornet:5702'   ]
   ] },

 { 'site_index'        : 40,
   'site_enabled'      : True,
   'site_long_name'    : u'Universität Kaiserslautern',
   'site_short_name'   : 'TUKL',
   'site_url'          : 'https://www.informatik.uni-kl.de',
   'site_domain'       : 'tukl.nornet',
   'site_city'         : 'Kaiserslautern',
   'site_province'     : 'Rheinland-Pfalz',
   'site_country'      : 'Deutschland',
   'site_country_code' : 'DE',
   'site_latitude'     : 49.4237695,
   'site_longitude'    : 7.7551096,
   'site_altitude'     : 50,
   'site_contacts'     : [ u'Schwerdel, Dennis: schwerdel@informatik.uni-kl.de' ],
   'site_pcu'          : [ IPv4Address('131.246.112.121'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'Deutsches Forschungsnetz', 'eth1',
           IPv4Network('131.246.112.120/24'),        IPv4Address('131.246.112.254'),
           IPv6Network('2001:638:208:ef2d::120/64'), IPv6Address('2001:638:208:ef2d:0:ff:fe00:ffd'),
           1500, 'fibre, business', 0, 0 ],
   ],
   'site_nodes' : [
      [ 100, 1, u'betzenberg' ],
      [ 101, 2, u'kaiserberg' ]
      #[ 102, 3, u'dansenberg' ],
   ] },

 { 'site_index'        : 41,
   'site_enabled'      : True,
   'site_long_name'    : u'Hochschule Hamburg',
   'site_short_name'   : 'HAW',
   'site_url'          : 'http://www.scimbe.de',
   'site_domain'       : 'haw.nornet',
   'site_city'         : 'Hamburg',
   'site_province'     : 'Hamburg',
   'site_country'      : 'Deutschland',
   'site_country_code' : 'DE',
   'site_latitude'     : 53.556122,
   'site_longitude'    : 10.022096,
   'site_altitude'     : 15,
   'site_contacts'     : [ u'Becke, Martin: scimbe@gmail.com', 'Ahlf, Christian: christian.ahlf@haw-hamburg.de' ],
   'site_pcu'          : [ IPv4Address('141.22.27.236'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'Deutsches Forschungsnetz', 'eth1',
           IPv4Network('141.22.27.235/23'),    IPv4Address('141.22.26.1'),
           IPv6Network('2001:4dd0:fe62::2/64'),IPv6Address('2001:4dd0:fe62::1'),
           1500, 'fibre, business', 0, 0 ],
   ],
   'site_nodes' : [
      [ 100, 1, u'reeperbahn',      'stpauli.haw.nornet',      'vnc://stpauli.haw.nornet:5700'      ],
      [ 101, 2, u'grossefreiheit',  'stpauli.haw.nornet',      'vnc://stpauli.haw.nornet:5701'      ],
      [ 102, 3, u'herbertstraße',   'wilhelmsburg.haw.nornet', 'vnc://wilhelmsburg.haw.nornet:5700' ]
      # [ 103, 4, u'spielbudenplatz', 'wilhelmsburg.haw.nornet', 'vnc://wilhelmsburg.haw.nornet:5701' ],
   ] },

 { 'site_index'        : 42,
   'site_enabled'      : True,
   'site_long_name'    : u'Universität Duisburg-Essen',
   'site_short_name'   : 'UDE',
   'site_url'          : 'https://www.uni-due.de',
   'site_domain'       : 'ude.nornet',
   'site_city'         : 'Essen',
   'site_province'     : 'Nordrhein-Westfalen',
   'site_country'      : 'Deutschland',
   'site_country_code' : 'DE',
   'site_latitude'     : 51.476144,
   'site_longitude'    : 7.011656,
   'site_altitude'     : 120,
   'site_contacts'     : [ u'Adhari, Hakim: hakim.adhari@uni-due.de', u'Cosić, Nihad: nihad.cosic@uni-due.de' ],
   'site_pcu'          : [ IPv4Address('132.252.152.73'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'Deutsches Forschungsnetz', 'eth1',
           IPv4Network('132.252.152.105/24'),        IPv4Address('132.252.152.1'),
           IPv6Network('2001:638:501:4ef2::105/64'), IPv6Address('2001:638:501:4ef2::1'),
           1500, 'fibre, business', 0, 0 ],
      [ u'Versatel', 'eth2',
           IPv4Network('89.246.242.228/29'), IPv4Address('89.246.242.225'),
           IPv6Network('::/0'),              IPv6Address('::'),
           1492, 'ADSL, consumer', 16000, 1000 ]
   ],
   'site_nodes' : [   # VMware cluster
      [ 100, 1, u'altenessen'  ],
      [ 101, 2, u'baldeneysee' ],
      [ 102, 3, u'borbeck'     ],
      [ 103, 4, u'kettwig'     ]
      #[ 104, 5, u'kray'        ],
      #[ 105, 6, u'kupferdreh'  ],
      #[ 106, 7, u'steele'      ],
      #[ 107, 8, u'zollverein'  ]
   ] },

 { 'site_index'        : 43,
   'site_enabled'      : True,
   'site_long_name'    : u'Universität Darmstadt',
   'site_short_name'   : 'TUDA',
   'site_url'          : 'https://www.deeds.informatik.tu-darmstadt.de',
   'site_domain'       : 'tuda.nornet',
   'site_city'         : 'Darmstadt',
   'site_province'     : 'Hessen',
   'site_country'      : 'Deutschland',
   'site_country_code' : 'DE',
   'site_latitude'     : 49.877621,
   'site_longitude'    : 8.654673,
   'site_altitude'     : 50,
   'site_contacts'     : [ u'Demir, Kubilay: kubidem@deeds.informatik.tu-darmstadt.de' ],
   'site_pcu'          : [ IPv4Address('130.83.162.211'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'Deutsches Forschungsnetz', 'eth1',
           IPv4Network('130.83.162.212/25'), IPv4Address('130.83.162.254'),
           IPv6Network('::/0'),              IPv6Address('::'),
           1500, 'fibre, business', 0, 0 ],
   ],
   'site_nodes' : [
      [ 100, 1, u'woogsviertel',     'herrngarten.tuda.nornet', 'vnc://herrngarten.tuda.nornet:5700' ],
      [ 101, 2, u'edelsteinviertel', 'herrngarten.tuda.nornet', 'vnc://herrngarten.tuda.nornet:5701' ],
      [ 102, 3, u'verlegerviertel',  'lichtwiese.tuda.nornet',  'vnc://lichtwiese.tuda.nornet:5700'  ],
      [ 103, 4, u'bessungen',        'lichtwiese.tuda.nornet',  'vnc://lichtwiese.tuda.nornet:5701'  ]
   ] },

 { 'site_index'        : 30,
   'site_enabled'      : True,
   'site_long_name'    : u'Karlstads Universitet',
   'site_short_name'   : 'KAU',
   'site_url'          : 'https://www.kau.se',
   'site_domain'       : 'kau.nornet',
   'site_city'         : 'Karlstad',
   'site_province'     : 'Värmland',
   'site_country'      : 'Sverige',
   'site_country_code' : 'SE',
   'site_latitude'     : 59.404101,
   'site_longitude'    : 13.58189,
   'site_altitude'     : 60,
   'site_contacts'     : [ u'Alfredsson, Stefan: Stefan.Alfredsson@kau.se', u'Eklund, Johan: Johan.Eklund@kau.se' ],
   'site_pcu'          : [ IPv4Address('193.10.227.86'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'Swedish University Network', 'eth1',
           IPv4Network('193.10.227.85/29'), IPv4Address('193.10.227.81'),
           IPv6Network('::/0'),             IPv6Address('::'),
           1500, 'fibre, business', 0, 0 ]
   ],
   'site_nodes' : [   # VMware cluster + physical machines
      [ 100, 1, u'vänern'           ],
      [ 101, 2, u'mariebergsskogen' ],
      [ 102, 3, u'klarälven'        ],
      [ 103, 4, u'stenbron'         ]
   ] },

 # Hainan University (海南大学)
 { 'site_index'        : 88,
   'site_enabled'      : True,
   'site_long_name'    : u'Hainan University',
   'site_short_name'   : 'HU',
   'site_url'          : 'http://cist.hainu.edu.cn',
   'site_domain'       : 'hu.nornet',
   'site_city'         : 'Haikou',
   'site_province'     : 'Hainan',
   'site_country'      : 'China',
   'site_country_code' : 'CN',
   'site_latitude'     : 20.059947,
   'site_longitude'    : 110.324425,
   'site_altitude'     : 10,
   'site_contacts'     : [ u'Fa, Fu: fufa@hainu.edu.cn', u'Zhou, Xing: xingzhou50@126.com' ],
   'site_pcu'          : [ IPv4Address('210.37.45.148'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'China Education and Research Network', 'eth1',
           IPv4Network('210.37.45.149/26'), IPv4Address('210.37.45.190'),
           IPv6Network('::/0'),             IPv6Address('::'),
           1500, 'fibre, business', 0, 0 ],
      [ u'China Unicom', 'eth2',
           IPv4Network('113.59.104.58/29'), IPv4Address('113.59.104.62'),
           IPv6Network('::/0'),             IPv6Address('::'),
           1500, 'fibre, consumer', 0, 0 ]
   ],
   'site_nodes' : [
      [ 100, 1, u'longlou',   'wenchang.hu.nornet', 'vnc://wenchang.hu.nornet:5700' ],   # Wenchang Satellite Launch Center/WSLC
      [ 101, 2, u'bamenbay',  'wenchang.hu.nornet', 'vnc://wenchang.hu.nornet:5701' ],   # This place is mangrove forests.
      [ 102, 3, u'boao',      'qionghai.hu.nornet', 'vnc://qionghai.hu.nornet:5700' ],   # This is the permanent address of Boao forum for asia.
      [ 103, 4, u'wanqun',    'qionghai.hu.nornet', 'vnc://qionghai.hu.nornet:5701' ],   # Wan-ch'uan River，Wanquan River before and called the white river.
      [ 104, 5, u'nanshan',   'sanya.hu.nornet',    'vnc://sanya.hu.nornet:5700'    ],   # Nanshan Buddhism Cultural Park is a display of traditional Chinese Buddhist culture
      [ 105, 6, u'yalongbay', 'sanya.hu.nornet',    'vnc://sanya.hu.nornet:5701'    ]    # This place has beautiful beach and tropical forest park
   ] },

 # Qiongzhou University (琼州大学)
 #{ 'site_index'        : 89,
   #'site_enabled'      : False,
   #'site_long_name'    : u'Qiongzhou University',
   #'site_short_name'   : 'QU',
   #'site_url'          : 'http://www.qzu.edu.cn',
   #'site_domain'       : 'qu.nornet',
   #'site_city'         : 'Sanya',
   #'site_province'     : 'Hainan',
   #'site_country'      : 'China',
   #'site_country_code' : 'CN',
   #'site_latitude'     : 18.288405,
   #'site_longitude'    : 109.55445,
   #'site_altitude'     : 10,
   #'site_contacts'     : [ u'Yu, Shi Huan: H.Y.Shi@163.com', u'Fa, Fu: fufa@hainu.edu.cn', u'Zhou, Xing: xingzhou50@126.com' ],
   #'site_pcu'          : [ IPv4Address('222.17.128.252'), 'pcu-root', 'a-secret-password' ],
   #'site_nornet_if'    : 'eth0',
   #'site_providers' : [
      #[ u'China Education and Research Network', 'eth1',
           #IPv4Network('222.17.128.253/26'), IPv4Address('222.17.128.193'),
           #IPv6Network('::/0'),              IPv6Address('::'),
           #1500, 'fibre, business', 0, 0 ]
   #],
   #'site_nodes' : [
      ## Naming scheme: places in Sanya
      #[ 100, 1, u'sanyabay',      'boating.qu.nornet',   'vnc://boating.qu.nornet:5700'   ],
      #[ 101, 2, u'luhuitou',      'boating.qu.nornet',   'vnc://boating.qu.nornet:5701'   ],
      #[ 102, 3, u'tianyahaijiao', 'lingshui.qu.nornet',  'vnc://lingshui.qu.nornet:5700'  ],
      #[ 103, 4, u'qiongzhou',     'lingshui.qu.nornet',  'vnc://lingshui.qu.nornet:5701'  ],
      #[ 104, 5, u'lizhigou',      'wuzhishan.qu.nornet', 'vnc://wuzhishan.qu.nornet:5700' ],
      #[ 105, 6, u'haitangbay',    'wuzhishan.qu.nornet', 'vnc://wuzhishan.qu.nornet:5701' ]
   #] },

 # Mongolian University of Science and Technology (Шинжлэх ухаан технологийн их сургууль)
 #{ 'site_index'        : 95,
   #'site_enabled'      : False,
   #'site_long_name'    : u'Mongolian Univeristy of Science and Technology',
   #'site_short_name'   : 'MUST',
   #'site_url'          : 'http://www.must.edu.mn',
   #'site_domain'       : 'must.nornet',
   #'site_city'         : 'Ulan Bator',
   #'site_province'     : 'Ulan Bator',
   #'site_country'      : 'Mongolia',
   #'site_country_code' : 'MN',
   #'site_latitude'     : 47.922041,
   #'site_longitude'    : 106.924384,
   #'site_altitude'     : 1350,
   #'site_contacts'     : [ u'Esbold, Unurkhaan: esbold98@gmail.com' ],
   #'site_pcu'          : [ IPv4Address('202.5.194.8'), 'pcu-root', 'a-secret-password' ],
   #'site_nornet_if'    : 'eth0',
   #'site_providers' : [
      #[ u'Erdemnet', 'eth0',   # << --- CHECK ME! ---
           #IPv4Network('202.5.194.9/24'), IPv4Address('202.5.194.2'),
           #IPv6Network('::/0'),           IPv6Address('::'),
           #1500, 'fibre, business', 0, 0 ]
   #],
   #'site_nodes' : [
      ## Naming scheme: districts of Ulan Bator
      ## Baganuur, Bagakhangai, Bayangol, Bayanzürkh, Chingeltei, Khan Uul, Nalaikh, Songino Khairkhan, and Sükhbaatar
      #[ 100, 1, u'baganuur',    'genghiskhan.must.nornet', 'vnc://genghiskhan.must.nornet:5700' ],
      #[ 101, 2, u'bagakhangai', 'genghiskhan.must.nornet', 'vnc://genghiskhan.must.nornet:5701' ]
   #] },

 { 'site_index'        : 100,
   'site_enabled'      : True,
   'site_long_name'    : u'The University of Kansas',
   'site_short_name'   : 'KU',
   'site_url'          : 'http://www.ittc.ku.edu',
   'site_domain'       : 'ku.nornet',
   'site_city'         : 'Lawrence',
   'site_province'     : 'Kansas',
   'site_country'      : 'United States of America',
   'site_country_code' : 'US',
   'site_latitude'     : 38.952,
   'site_longitude'    : -95.264,
   'site_altitude'     : 300,
   'site_contacts'     : [ u'Gangadhar, Siddharth: siddharth@ittc.ku.edu', u'Fleming, Brad: bdfleming@kanren.net', u'Sterbenz, James P.G.: jpgs@ittc.ku.edu' ],
   'site_pcu'          : [ IPv4Address('164.113.202.19'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'Kansas Research and Education Network', 'eth1',
           IPv4Network('164.113.202.17/28'),        IPv4Address('164.113.202.30'),
           IPv6Network('2001:49d0:3c00:6::17/64'),  IPv6Address('2001:49d0:3c00:6::1'),
           1500, 'fibre, business', 0, 0 ]
   ],
   'site_nodes' : [
      [ 100, 1, u'watson',  'oread.ku.nornet', 'vnc://oread.ku.nornet:5700' ],
      [ 101, 2, u'clinton', 'oread.ku.nornet', 'vnc://oread.ku.nornet:5701' ]
      #[ 102, 3, u'williamstown' ],
      #[ 103, 4, u'stull' ]
   ] },

 #{ 'site_index'        : 101,
   #'site_enabled'      : False,
   #'site_long_name'    : u'New York University',
   #'site_short_name'   : 'NYU',
   #'site_url'          : 'http://engineering.nyu.edu',
   #'site_domain'       : 'nyu.nornet',
   #'site_city'         : 'Brooklyn',
   #'site_province'     : 'New York',
   #'site_country'      : 'United States of America',
   #'site_country_code' : 'US',
   #'site_latitude'     : 40.694074,
   #'site_longitude'    :  -73.986932,
   #'site_altitude'     : 20,
   #'site_contacts'     : [ u'Rivera, Julio: jr847@nyu.edu', u'Cappos, Justin: jcappos@nyu.edu', u'Rafetseder, Albert: albert.rafetseder+nyu@univie.ac.at' ],
   #'site_pcu'          : [ IPv4Address('128.238.63.80'), 'pcu-root', 'a-secret-password' ],
   #'site_nornet_if'    : 'eth0',
   #'site_providers' : [
      #[ u'Lightower Fiber Networks', 'eth1',
           #IPv4Network('128.238.63.79/24'), IPv4Address('128.238.63.1'),
           #IPv6Network('::/0'),             IPv6Address('::'),
           #1500, 'fibre, business', 0, 0 ]
   #],
   #'site_nodes' : [   # VMware cluster
      #[ 100, 1, u'brooklyn'  ],
      #[ 101, 2, u'manhattan' ],
      #[ 102, 3, u'bronx'     ],
      #[ 103, 4, u'queens'    ]
   #] },

 { 'site_index'        : 160,
   'site_enabled'      : True,
   'site_long_name'    : u'Korea University',   # 고려대학교
   'site_short_name'   : 'KRU',
   'site_url'          : 'http://www.korea.ac.kr',
   'site_domain'       : 'korea.nornet',
   'site_city'         : 'Seoul',
   'site_province'     : 'Seoul',
   'site_country'      : 'South Korea',
   'site_country_code' : 'KR',
   'site_latitude'     : 37.585175,
   'site_longitude'    : 127.028460,
   'site_altitude'     : 50,
   'site_contacts'     : [ u'Hwang, Jae Hyun: jh.hwang@alcatel-lucent.com', u'Walid, Anwar: anwar@research.bell-labs.com' ],
   'site_pcu'          : [ IPv4Address('203.230.60.126'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'Korea Research Environment Open NETwork', 'eth1',
           IPv4Network('203.230.60.125/26'), IPv4Address('203.230.60.65'),
           IPv6Network('::/0'),              IPv6Address('::'),
           1500, 'fibre, business', 0, 0 ]
   ],
   'site_nodes' : [
      # Naming schemes:
      # Research nodes: stations in Seoul
      # Physical machines: rivers in Seoul
      [ 100, 1, u'yongsan', 'gwanaksan.korea.nornet', 'vnc://gwanaksan.korea.nornet:5700' ],
      [ 101, 2, u'mapo',    'gwanaksan.korea.nornet', 'vnc://gwanaksan.korea.nornet:5701' ]
      #[ 102, 3, u'ichon',   'gwanaksan.korea.nornet', 'vnc://gwanaksan.korea.nornet:5702' ],
      #[ 103, 4, u'gireum',  'gwanaksan.korea.nornet', 'vnc://gwanaksan.korea.nornet:5703' ],
      #[ 104, 5, u'aram',    'hangang.korea.nornet',   'vnc://hangang.korea.nornet:5700'   ],
      #[ 105, 6, u'geumho',  'hangang.korea.nornet',   'vnc://hangang.korea.nornet:5701'   ]
   ] },

 #{ 'site_index'        : 120,
   #'site_enabled'      : False,
   #'site_long_name'    : u'Universidade Federal de São Carlos',
   #'site_short_name'   : 'UFSCAR',
   #'site_url'          : 'http://www.ufscar.br',
   #'site_domain'       : 'ufscar.nornet',
   #'site_city'         : 'Sorocaba',
   #'site_province'     : 'São Paulo',
   #'site_country'      : 'Brazil',
   #'site_country_code' : 'BR',
   #'site_latitude'     : -21.980956,
   #'site_longitude'    : -47.883528,
   #'site_altitude'     : 50,
   #'site_contacts'     : [ u'Sandri, Marcus: mwws55@gmail.com', u'Verdi, Fábio Luciano: verdi@ufscar.br', u'Silva, Alan: alansilva@acm.org' ],
   #'site_pcu'          : [ IPv4Address('200.133.238.124'), 'pcu-root', 'a-secret-password' ],
   #'site_nornet_if'    : 'eth0',
   #'site_providers' : [
      #[ u'Rede Nacional de Ensino e Pesquisa', 'eth1',
           #IPv4Network('200.133.238.125/27'), IPv4Address('200.133.238.97'),
           #IPv6Network('::/0'),               IPv6Address('::'),
           #1500, 'fibre, business', 0, 0 ]
      ##[ u'Academic Network at São Paulo', 'eth2',
           ##IPv4Network('186.219.95.214/24'), IPv4Address('186.219.95.1'),
           ##IPv6Network('::/0'),              IPv6Address('::'),
           ##1500, 'fibre, business', 0, 0 ]
   #],
   #'site_nodes' : [
      #[ 100, 1, u'soroc'   ],
      #[ 101, 2, u'lerisor' ]
   #] },

 { 'site_index'        : 200,
   'site_enabled'      : True,
   'site_long_name'    : u'National ICT Australia',
   'site_short_name'   : 'NICTA',
   'site_url'          : 'https://www.nicta.com.au',
   'site_domain'       : 'nicta.nornet',
   'site_city'         : 'Sydney',
   'site_province'     : 'New South Wales',
   'site_country'      : 'Australia',
   'site_country_code' : 'AU',
   'site_latitude'     : -33.895430,
   'site_longitude'    : 151.197021,
   'site_altitude'     : 15,
   'site_contacts'     : [ u'Mehani, Olivier: olivier.mehani@nicta.com.au',
                           u'Rakotoarivelo, Thierry: Thierry.Rakotoarivelo@nicta.com.au' ],
   'site_pcu'          : [ IPv4Address('221.199.217.168'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ u'Australian Academic and Research Network', 'eth1',
           IPv4Network('221.199.217.167/26'), IPv4Address('221.199.217.129'),
           IPv6Network('::/0'),               IPv6Address('::'),
           1500, 'fibre, business', 0, 0 ]
   ],
   'site_nodes' : [
      [ 100, 1, u'coogee' ],
      [ 101, 2, u'bondi'  ]
   ] }

      #[ 100, 1, u'lutefisk'     ],
      #[ 101, 2, u'pinnekjøtt'   ],
      #[ 102, 3, u'ribbe'        ],
      #[ 103, 4, u'laks'         ],
      #[ 104, 5, u'torsk'        ],
      #[ 105, 6, u'tørrfisk'     ],
      #[ 106, 7, u'rekesmørbrød' ],
      #[ 107, 8, u'brunost'      ]

]


# ###### Remove site ########################################################
def removeSite(site):
   if site == None:
      fullSiteList = fetchNorNetSiteList()
      if fullSiteList != None:
         for siteIndex in fullSiteList:
            site = fullSiteList[siteIndex]
            removeNorNetSite(site['site_long_name'])
   else:
      siteName = makeNameFromUnicode(site['site_long_name'], False)['ascii']
      removeNorNetSite(siteName)


# ###### Add site ###########################################################
def makeSite(fullSliceList, site, norNetInformation, ntpServers):
   # ====== Add tag types ===================================================
   makeNorNetTagTypes()

   # ====== Make site ========================================================
   siteIndex = site['site_index']

   newSite = makeNorNetSite(site['site_long_name'], site['site_short_name'], site['site_enabled'],
                            str.lower(site['site_short_name']),
                            site['site_url'], site['site_domain'], siteIndex,
                            site['site_city'], site['site_province'], site['site_country'], site['site_country_code'],
                            site['site_latitude'], site['site_longitude'], site['site_altitude'],
                            site['site_contacts'],
                            site['site_providers'], site['site_providers'][0][0], site['site_nornet_if'],
                            ntpServers)
   newPCU = makeNorNetPCU(newSite, 'pcu', site['site_domain'],
                          site['site_pcu'][0], site['site_pcu'][1], site['site_pcu'][2],
                          'ssh', 'Amiga 5099', 'Jeg vet ikke.')

   # ====== Make nodes ======================================================
   i = 100
   for node in site['site_nodes']:
      address = node[0]
      if address <= 0:
         address = i
      port = node[1]
      if port <= 0:
        port = i
      try:
         machineHost    = node[3]
         machineDisplay = node[4]
      except:
         machineHost    = ''
         machineDisplay = 'physical'
      makeNorNetNode(fullSliceList, newSite, node[2], address, newPCU, port,
                     'eth0', 'Amiga 5000', 'boot', machineHost, machineDisplay)


# ###### Make test setup ####################################################
def getBootISOs(isoDirectory):
   allNorNetNodes = fetchNorNetNodeList()
   for node in allNorNetNodes:
      nodeID   = node['node_id']
      nodeName = node['node_name']
      isoName  = os.path.normpath(os.path.join(isoDirectory, nodeName + '.iso'))
      if not os.path.exists(isoName):
         log('Downloading ' + isoName + ' ...')
         try:
            isoBase64 = getPLCServer().GetBootMedium(getPLCAuthentication(), nodeID, 'node-iso' , '', [])
            iso       = base64.b64decode(isoBase64)
            outputFile = open(isoName, 'w')
            outputFile.write(iso)
            outputFile.close()
         except:
            error('Unable to generate ' + isoName + '!')

      else:
         log('Not downloading ' + isoName + ', it already exists!')


# ###### Perform site action ################################################
def performAction(fullSliceList, action, site):
   if ((action == 'remove') or (action == 'renew')):
      removeSite(site)
   if ((action == 'add') or (action == 'renew')):
      makeSite(fullSliceList, site, norNetInformation, ntpServers)



# ###### Main program #######################################################
action = ''
if len(sys.argv) > 2:
   if sys.argv[1] == 'add':
      action = 'add'
   elif sys.argv[1] == 'renew':
      action = 'renew'
   elif sys.argv[1] == 'remove':
      action = 'remove'
   elif sys.argv[1] == 'manage':
      action = 'manage'
if action == '':
   error('Usage: ' + sys.argv[0] + ' add|renew|remove|manage Site|ALL [Site] ... [--user=user_name] [--slice=slice_name]')


log('***** Welcome to NorNet! *****')
loginToPLC()

fullSliceList = fetchNorNetSliceList()


# ====== Some server settings ===============================================
# norNetInformation = getNorNetInformationForAddress(getPLCAddress())
norNetInformation = getMyNorNetInformation()
print(norNetInformation)
ntpServerNames = [ 'ntp1.ptb.de', 'ntp2.ptb.de', 'ntp3.ptb.de',   # The PTB servers (very reliable sources)
                   'ntp1.uio.no', 'ntp2.uio.no' ]                 # UiO (nearby)

ntpServers = []
for ntpServer in ntpServerNames:
   ntpAddress = resolveHostname(ntpServer, AF_INET6)
   if ntpAddress != None:
      ntpServers.append(ntpAddress)
   ntpAddress = resolveHostname(ntpServer, AF_INET)
   if ntpAddress != None:
      ntpServers.append(ntpAddress)
# ===========================================================================


# ====== Add tag types ======================================================
if ((action == 'add') or (action == 'renew')):
   makeNorNetTagTypes()


# ====== Remove or create sites =============================================
if str.upper(sys.argv[2]) == 'ALL':
   if ((action == 'remove') or (action == 'renew')):
      removeSite(None)
   if action != 'remove':
      for site in norNetSetup:
         performAction(fullSliceList, action, site)
   i = 3
else:
   i = 2

userID       = 0
sliceID      = 0
isoDirectory = None
while i < len(sys.argv):
   match = re.search('^--([a-z]*)=(.*)', sys.argv[i])
   if ((match != None) and (match.group(1) == 'user')):
      userName = match.group(2)
      userID   = lookupPersonID(userName)
      if userID == 0:
         error('Unable to find user ' + userName + '\n')

   elif ((match != None) and (match.group(1) == 'slice')):
      sliceName = match.group(2)
      sliceID   = lookupSliceID(sliceName)
      if sliceID == 0:
         error('Unable to find slice ' + sliceName + '\n')

   elif ((match != None) and (match.group(1) == 'isodirectory')):
      isoDirectory = match.group(2)

   else:
      found = None
      for site in norNetSetup:
         if ((site['site_long_name'] == sys.argv[i]) or
             (site['site_short_name'] == sys.argv[i])):
            found = site
            break
      if found == None:
         error('Site "' + sys.argv[i] + '" is not defined!')
      performAction(fullSliceList, action, found)

   i = i + 1


# ====== Set user ===========================================================
if userID != 0:
   log('Adding user to all sites ...')
   # ====== Add user to all sites ===========================================
   allNorNetSites = fetchNorNetSiteList(False)
   for siteIndex in allNorNetSites:
      site = allNorNetSites[siteIndex]
      getPLCServer().AddPersonToSite(getPLCAuthentication(), userID, site['site_id'])
      if site['site_id'] == NorNet_SiteIndex_Central:
         getPLCServer().SetPersonPrimarySite(getPLCAuthentication(), userID, site['site_id'])

# ====== Set slice ==========================================================
if sliceID != 0:
   log('Adding slice to all nodes ...')
   # ====== Add slice to all nodes ==========================================
   nodeIDs = []
   allNorNetNodes = fetchNorNetNodeList()
   for node in allNorNetNodes:
      nodeIDs.append(int(node['node_id']))
   getPLCServer().AddSliceToNodes(getPLCAuthentication(), sliceID, nodeIDs)

# ====== Get boot ISOs ======================================================
if isoDirectory != None:
   getBootISOs(isoDirectory)
