#!/bin/bash

command=$1   ; shift
slicename=$1 ; shift

# The packages to be installed inside a NorNet sliver
NORNET_PACKAGES="autoconf automake libtool gcc gcc-c++ gdb automake autoconf joe libstdc++-devel boost-devel gcc gcc-c++ glib-devel glib2-devel make subversion libpcap bzip2-devel findutils valgrind strace lksctp-tools-devel GeoIP-devel libcurl-devel openssl-devel bison flex subversion git htop mlocate"


# ###### Configure proxy ####################################################
function proxy_setup ()
{
   hostName=`hostname --fqdn`
   domainName=`echo "$hostName" | sed -e "s/^[^\.]*\.//g"`
   proxyName="proxy.$domainName"
   (
      echo "export http_proxy=\"http://$proxyName:3128/\""
      echo "export ftp_proxy=\"http://$proxyName:3128/\""
      echo "export no_proxy=\"$domainName\""
   ) >/etc/profile.d/proxy.sh
   . /etc/profile.d/proxy.sh
   (
      echo "setenv http_proxy \"http://$proxyName:3128/\""
      echo "setenv ftp_proxy \"http://$proxyName:3128/\""
      echo "setenv no_proxy \"$domainName\""
   ) >/etc/profile.d/proxy.csh
}


# ###### yum-based package installation #####################################
function yum_install ()
{
   packages="$@"
   echo "Checking $packages ..."
   while true ; do
      # If all packages are installed, we are done.
      rpm -q $packages && break

      # Install the given packages.
      # NOTE: Using "-i" for sudo to read the profile settings. Otherwise,
      #       the proxy settings would not be used!
      # sudo rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY
      sudo -i yum -y install $packages

      # Try again after a short break ...
      sleep 10
   done
   echo "$packages installed."
}


# ###### Start sliver #######################################################
function start () {
   (
      echo "`/bin/date`: Running slice initscript ..."
      proxy_setup
      yum_install yum-plugin-fastestmirror
      yum_install $NORNET_PACKAGES
      echo "`/bin/date`: Done!"
   ) >>/var/log/nornet-sliceinit.log 2>&1
}


# ###### Stop sliver ########################################################
function stop () {
   dummy=0
}


# ###### Restart sliver #####################################################
function restart () {
  stop
  start
}


case $command in
   start)
      start
      ;;
   stop)
      stop
      ;;
   restart)
      restart
      ;;
   *)
      echo "Unknown command in initscript $command for slice $slicename"
      ;;
esac
