#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# NorNet Setup
# Copyright (C) 2012-2013 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

import re;
import os;
import base64;

# Needs package python-ipaddr (Fedora Core, Ubuntu, Debian)!
from ipaddr import IPv4Address, IPv4Network, IPv6Address, IPv6Network;

# NorNet
from NorNetTools         import *;
from NorNetAPI           import *;
from NorNetProviderSetup import *;
from NorNetSiteSetup     import *;


norNetSetup = [
 { 'site_index'        : 1,
   'site_enabled'      : True,
   'site_long_name'    : u'Simula Research Laboratory',
   'site_short_name'   : 'SRL',
   'site_url'          : 'http://www.simula.nornet',
   'site_domain'       : 'simula.nornet',
   'site_city'         : 'Fornebu',
   'site_province'     : 'Akershus',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 59.895933,
   'site_longitude'    : 10.627635,
   'site_altitude'     : 15,
   'site_pcu'          : [ IPv4Address('158.39.4.3'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ 'Uninett',  'eth1', IPv4Network('158.39.4.2/24'),                     IPv4Address('158.39.4.1'),
                            IPv6Network('2001:700:4100:4::2/64'),             IPv6Address('2001:700:4100:4::1') ],
      [ 'Hafslund', 'eth2', IPv4Network('77.88.71.151/26'),                   IPv4Address('77.88.71.133'),
                            IPv6Network('2a02:270:2014:111:77:88:71:151/64'), IPv6Address('2a02:270:2014:111::1') ]
   ],
   'site_nodes' : [
      [ 100,  1, u'akerbrygge'  ],
      [ 101,  2, u'bygdøy'      ],
      [ 102,  3, u'tullinløkka' ],
      [ 103,  4, u'frogner'     ],
      [ 104,  5, u'nordberg'    ],
      [ 105,  6, u'solvang'     ],
      [ 106,  7, u'nordreaker'  ],
      [ 107,  8, u'vestreaker'  ],
      [ 108,  9, u'skøyen'      ],
      [ 109, 10, u'vækerø'      ],
      [ 110, 11, u'akerselva'   ],
      [ 111, 12, u'ullern'      ]
   ] },

 { 'site_index'        : 2,
   'site_enabled'      : True,
   'site_long_name'    : u'Universitetet i Oslo',
   'site_short_name'   : 'UiO',
   'site_url'          : 'http://www.uio.nornet',
   'site_domain'       : 'uio.nornet',
   'site_city'         : 'Oslo',
   'site_province'     : 'Oslo',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 59.944034,
   'site_longitude'    : 10.719013,
   'site_altitude'     : 100,
   'site_pcu'          : [ IPv4Address('129.240.66.75'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ 'Uninett', 'eth1', IPv4Network('129.240.66.74/29'),       IPv4Address('129.240.66.73'),
                           IPv6Network('2001:700:100:279::4/64'), IPv6Address('2001:700:100:279::1') ]
   ],
   'site_nodes' : [
      [ 100, 1, u'bjørvika' ],
      [ 101, 2, u'ekeberg'  ],
      [ 102, 3, u'furuset'  ],
      [ 103, 4, u'grefsen'  ],
      [ 104, 5, u'helsfyr'  ],
      [ 105, 6, u'tøyen'    ]
   ] },

 { 'site_index'        : 3,
   'site_enabled'      : True,
   'site_long_name'    : u'Høgskolen i Gjøvik',
   'site_short_name'   : 'HiG',
   'site_url'          : 'http://www.hig.nornet',
   'site_domain'       : 'hig.nornet',
   'site_city'         : 'Gjøvik',
   'site_province'     : 'Oppland',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 60.789615,
   'site_longitude'    : 10.68166,
   'site_altitude'     : 200,
   'site_pcu'          : [ IPv4Address('128.39.49.165'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ 'Uninett', 'eth1', IPv4Network('128.39.49.154/25'),         IPv4Address('128.39.49.129'),
                           IPv6Network('2001:700:1d00:18::154/64'), IPv6Address('2001:700:1d00:18::1') ]
   ],
   'site_nodes' : [
      [ 100, 1, u'kapp'      ],
      [ 101, 2, u'eina'      ],
      [ 102, 3, u'raufoss'   ],
      [ 103, 4, u'reinsvoll' ],
      [ 104, 5, u'skreia'    ],
      [ 105, 6, u'lena'      ]
   ] },

 { 'site_index'        : 4,
   'site_enabled'      : True,
   'site_long_name'    : u'Universitetet i Tromsø',
   'site_short_name'   : 'UiT',
   'site_url'          : 'http://www.uit.nornet',
   'site_domain'       : 'uit.nornet',
   'site_city'         : 'Tromsø',
   'site_province'     : 'Troms',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 69.681897,
   'site_longitude'    : 18.980541,
   'site_altitude'     : 50,
   'site_pcu'          : [ IPv4Address('129.242.157.229'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ 'Uninett', 'eth1', IPv4Network('129.242.157.228/28'), IPv4Address('129.242.157.225'),
                           IPv6Network('::/0'),               IPv6Address('::') ]
   ],
   'site_nodes' : [
      [ 100, 1, u'amundsen'    ],
      [ 101, 2, u'nansen'      ],
      [ 102, 3, u'aunegården'  ],
      [ 103, 4, u'skarven'     ],
      [ 104, 5, u'arctandria'  ],
      [ 105, 6, u'kongsbakken' ]
   ] },

 { 'site_index'        : 5,
   'site_enabled'      : True,
   'site_long_name'    : u'Universitetet i Stavanger',
   'site_short_name'   : 'UiS',
   'site_url'          : 'http://www.uis.nornet',
   'site_domain'       : 'uis.nornet',
   'site_city'         : 'Stavanger',
   'site_province'     : 'Rogaland',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 58.938063,
   'site_longitude'    : 5.691172,
   'site_altitude'     : 25,
   'site_pcu'          : [ IPv4Address('152.94.120.7'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ 'Uninett', 'eth1', IPv4Network('152.94.120.6/24'), IPv4Address('152.94.120.1'),
                           IPv6Network('::/0'),            IPv6Address('::') ]
   ],
   'site_nodes' : [
      [ 100, 1, u'mosterøy'  ],
      [ 101, 2, u'klosterøy' ],
      [ 102, 3, u'askje'     ],
      [ 103, 4, u'sokn'      ],
      [ 104, 5, u'rennesoey' ],
      [ 105, 6, u'fjøløy'    ]
   ] },

 { 'site_index'        : 6,
   'site_enabled'      : True,
   'site_long_name'    : u'Universitetet i Bergen',
   'site_short_name'   : 'UiB',
   'site_url'          : 'http://www.uib.nornet',
   'site_domain'       : 'uib.nornet',
   'site_city'         : 'Bergen',
   'site_province'     : 'Hordaland',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 60.384904,
   'site_longitude'    : 5.328636,
   'site_altitude'     : 50,
   'site_pcu'          : [ IPv4Address('158.37.6.194'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ 'Uninett', 'eth1', IPv4Network('158.37.6.195/26'),           IPv4Address('158.37.6.193'),
                           IPv6Network('2001:700:201:F002::195/64'), IPv6Address('2001:700:201:F002::1') ],
      [ 'Bergenshalvøens Kommunale Kraftselskap',
                   'eth2', IPv4Network('62.97.202.70/30'),           IPv4Address('62.97.202.69'),
                           IPv6Network('2A00:14D8:1001:556::2/126'), IPv6Address('2A00:14D8:1001:556::1') ]
   ],
   'site_nodes' : [
      [ 100, 1, u'fløibanen'        ],
      [ 101, 2, u'fisketorget'      ],
      [ 102, 3, u'ulriksbanen'      ],
      [ 103, 4, u'lungegårdsvannet' ],
      [ 104, 5, u'bergenhus'        ],
      [ 105, 6, u'sverresborg'      ]
   ] },

 { 'site_index'        : 7,
   'site_enabled'      : True,
   'site_long_name'    : u'Universitetet i Agder',
   'site_short_name'   : 'UiA',
   'site_url'          : 'http://www.uia.nornet',
   'site_domain'       : 'uia.nornet',
   'site_city'         : 'Kristiansand',
   'site_province'     : 'Vest-Agder',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 58.163833,
   'site_longitude'    : 8.002936,
   'site_altitude'     : 50,
   'site_pcu'          : [ IPv4Address('158.36.50.178'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ 'Uninett', 'eth1', IPv4Network('158.36.50.178/29'),         IPv4Address('158.36.50.177'),
                           IPv6Network('2001:700:1500:c064::2/64'), IPv6Address('2001:700:1500:c064::1') ]
   ],
   'site_nodes' : [
      [ 100, 1, u'julenisse'    ],
      [ 101, 2, u'fjøsnisse'    ],
      [ 102, 3, u'gårdsnisse'   ],
      [ 103, 4, u'hagenisse'    ],
      [ 104, 5, u'skipsnisse'   ],
      [ 105, 6, u'heinzelnisse' ]
   ] },

 { 'site_index'        : 8,
   'site_enabled'      : True,
   'site_long_name'    : u'Universitetet på Svalbard',
   'site_short_name'   : 'UNIS',
   'site_url'          : 'http://www.unis.nornet',
   'site_domain'       : 'unis.nornet',
   'site_city'         : 'Longyearbyen',
   'site_province'     : 'Svalbard',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 78.222652,
   'site_longitude'    : 15.653273,
   'site_altitude'     : 20,
   'site_pcu'          : [ IPv4Address('158.39.149.133'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ 'Uninett', 'eth1', IPv4Network('158.39.149.132/25'), IPv4Address('158.39.149.129'),
                           IPv6Network('::/0'),              IPv6Address('::') ]
   ],
   'site_nodes' : [
      [ 100, 1, u'snøflak'       ],
      [ 101, 2, u'isbre'         ],
      [ 102, 3, u'nordlys'       ],
      [ 103, 4, u'midnattssol'   ],
      [ 104, 5, u'adventfjorden' ],
      [ 105, 6, u'isfjorden'     ]
   ] },

 { 'site_index'        : 9,
   'site_enabled'      : True,
   'site_long_name'    : u'Universitetet i Trondheim',
   'site_short_name'   : 'NTNU',
   'site_url'          : 'http://www.ntnu.nornet',
   'site_domain'       : 'ntnu.nornet',
   'site_city'         : 'Trondheim',
   'site_province'     : 'Sør-Trøndelag',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 63.418003,
   'site_longitude'    : 10.401625,
   'site_altitude'     : 50,
   'site_pcu'          : [ IPv4Address('129.241.200.129'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ 'Uninett', 'eth1', IPv4Network('129.241.200.128/24'),        IPv4Address('129.241.200.1'),
                           IPv6Network('2001:700:300:2211::128/64'), IPv6Address('2001:700:300:2211::1') ]
   ],
   'site_nodes' : [
      [ 100, 1, u'bybro'      ],
      [ 101, 2, u'bakklandet' ],
      [ 102, 3, u'byåsen'     ],
      [ 103, 4, u'lerkendal'  ],
      [ 104, 5, u'bymarka'    ],
      [ 105, 6, u'heimdal'    ]
   ] },

 { 'site_index'        : 10,
   'site_enabled'      : True,
   'site_long_name'    : u'Høgskolen i Narvik',
   'site_short_name'   : 'HiN',
   'site_url'          : 'http://www.hin.nornet',
   'site_domain'       : 'hin.nornet',
   'site_city'         : 'Narvik',
   'site_province'     : 'Nordland',
   'site_country'      : 'Norge',
   'site_country_code' : 'NO',
   'site_latitude'     : 68.436023,
   'site_longitude'    : 17.434984,
   'site_altitude'     : 75,
   'site_pcu'          : [ IPv4Address('158.39.93.232'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ 'Uninett', 'eth1', IPv4Network('158.39.93.231/27'),         IPv4Address('158.39.93.225'),
                           IPv6Network('2001:700:c00:150::231/64'), IPv6Address('2001:700:c00:150::1') ]
   ],
   'site_nodes' : [
      [ 100, 1, u'storsteinsfjellet' ],
      [ 101, 2, u'nihkevarri'        ],
      [ 102, 3, u'beisfjordtøtta'    ],
      [ 103, 4, u'rombakstøtta'      ],
      [ 104, 5, u'bjørnfjell'        ],
      [ 105, 6, u'fagernesfjellet'   ]
   ] },

 { 'site_index'        : 42,
   'site_enabled'      : True,
   'site_long_name'    : u'Universität Duisburg-Essen',
   'site_short_name'   : 'UDE',
   'site_url'          : 'http://www.ude.nornet',
   'site_domain'       : 'ude.nornet',
   'site_city'         : 'Essen',
   'site_province'     : 'Nordrhein-Westfalen',
   'site_country'      : 'Deutschland',
   'site_country_code' : 'DE',
   'site_latitude'     : 51.476144,
   'site_longitude'    : 7.011656,
   'site_altitude'     : 120,
   'site_pcu'          : [ IPv4Address('132.252.156.12'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ 'Deutsches Forschungsnetz', 'eth1', IPv4Network('132.252.152.105/24'),        IPv4Address('132.252.152.1'),
                                            IPv6Network('2001:638:501:4ef2::105/64'), IPv6Address('2001:638:501:4ef2::1') ],
      [ 'Versatel',                 'eth2', IPv4Network('89.246.242.228/29'), IPv4Address('89.246.242.225'),
                                            IPv6Network('::/0'),              IPv6Address('::') ]
   ],
   'site_nodes' : [
      [ 100, 1, u'altenessen'  ],
      [ 101, 2, u'baldeneysee' ],
      [ 102, 3, u'borbeck'     ],
      [ 103, 4, u'kettwig'     ]
      #[ 104, 5, u'kray'        ],
      #[ 105, 6, u'kupferdreh'  ],
      #[ 106, 7, u'steele'      ],
      #[ 107, 8, u'zollverein'  ]
   ] },

 { 'site_index'        : 30,
   'site_enabled'      : True,
   'site_long_name'    : u'Karlstads Universitet',
   'site_short_name'   : 'KAU',
   'site_url'          : 'http://www.kau.nornet',
   'site_domain'       : 'kau.nornet',
   'site_city'         : 'Karlstad',
   'site_province'     : 'Värmland',
   'site_country'      : 'Sverige',
   'site_country_code' : 'SE',
   'site_latitude'     : 59.404101,
   'site_longitude'    : 13.58189,
   'site_altitude'     : 60,
   'site_pcu'          : [ IPv4Address('0.0.0.0'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ 'SUNET', 'eth1', IPv4Network('193.10.227.85/29'), IPv4Address('193.10.227.81'),
                         IPv6Network('::/0'),  IPv6Address('::') ]
      #[ 'Provider Zwei', 'eth2', IPv4Network('3.3.3.3/24'),     IPv4Address('3.3.3.1'),
                                 #IPv6Network('::/0'),  IPv6Address('::') ]
   ],
   'site_nodes' : [
      [ 100, 1, u'vänern'           ],
      [ 101, 2, u'mariebergsskogen' ],
      [ 102, 3, u'klarälven'        ],
      [ 103, 4, u'stenbron'         ]
   ] },

 { 'site_index'        : 88,
   'site_enabled'      : True,
   'site_long_name'    : u'Hainan University',
   'site_short_name'   : 'HU',
   'site_url'          : 'http://www.hu.nornet',
   'site_domain'       : 'hu.nornet',
   'site_city'         : 'Haikou',
   'site_province'     : 'Hainan',
   'site_country'      : 'China',
   'site_country_code' : 'CN',
   'site_latitude'     : 20.059947,
   'site_longitude'    : 110.324425,
   'site_altitude'     : 10,
   'site_pcu'          : [ IPv4Address('210.37.45.148'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ 'China Education and Research Network', 'eth1', IPv4Network('210.37.45.149/26'), IPv4Address('210.37.45.190'),
                                                        IPv6Network('::/0'), IPv6Address('::') ],
      [ 'China Unicom',                         'eth2', IPv4Network('113.59.104.58/29'), IPv4Address('113.59.104.62'),
                                                        IPv6Network('::/0'), IPv6Address('::') ]
   ],
   'site_nodes' : [
      [ 100, 1, u'longlou'   ],   # Wenchang Satellite Launch Center/WSLC
      [ 101, 2, u'bamenbay'  ],   # This place is mangrove forests.
      [ 102, 3, u'boao'      ],   # This is the permanent address of Boao forum for asia.
      [ 103, 4, u'wanqun'    ],   # Wan-ch'uan River，Wanquan River before and called the white river.
      [ 104, 5, u'nanshan'   ],   # Nanshan Buddhism Cultural Park is a display of traditional Chinese Buddhist culture
      [ 105, 6, u'yalongbay' ]    # This place has beautiful beach and tropical forest park
   ] },

 { 'site_index'        : 100,
   'site_enabled'      : False,
   'site_long_name'    : u'University of Kansas',
   'site_short_name'   : 'KU',
   'site_url'          : 'http://www.ku.nornet',
   'site_domain'       : 'ku.nornet',
   'site_city'         : 'Lawrence',
   'site_province'     : 'Kansas',
   'site_country'      : 'U.S.A.',
   'site_country_code' : 'US',
   'site_latitude'     : 38.952,
   'site_longitude'    : -95.264,
   'site_altitude'     : 300,
   'site_pcu'          : [ IPv4Address('0.0.0.0'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ 'Provider Eins', 'eth1', IPv4Network('2.2.2.2/24'),     IPv4Address('2.2.2.1'),
                                 IPv6Network('::/0'),  IPv6Address('::') ],
      [ 'Provider Zwei', 'eth2', IPv4Network('3.3.3.3/24'),     IPv4Address('3.3.3.1'),
                                 IPv6Network('::/0'),  IPv6Address('::') ]
   ],
   'site_nodes' : [
      #[ 100, 1, u'smörgåstårta' ],
      #[ 101, 2, u'knäckebröd'   ]
   ] },

 { 'site_index'        : 120,
   'site_enabled'      : False,
   'site_long_name'    : u'Universidade Federal de São Carlos',
   'site_short_name'   : 'UFSCAR',
   'site_url'          : 'http://www.ufscar.nornet',
   'site_domain'       : 'ufscar.nornet',
   'site_city'         : 'São Paulo',
   'site_province'     : 'São Paulo',
   'site_country'      : 'Brazil',
   'site_country_code' : 'BR',
   'site_latitude'     : -21.980956,
   'site_longitude'    : -47.883528,
   'site_altitude'     : 50,
   'site_pcu'          : [ IPv4Address('0.0.0.0'), 'pcu-root', 'a-secret-password' ],
   'site_nornet_if'    : 'eth0',
   'site_providers' : [
      [ 'Rede Nacional de Ensino e Pesquisa', 'eth1', IPv4Network('200.133.238.124/27'),   IPv4Address('200.133.238.97'),
                                                      IPv6Network('::/0'),  IPv6Address('::') ],
      [ 'Academic Network at São Paulo', 'eth2',      IPv4Network('186.219.95.214/24'),    IPv4Address('186.219.95.1'),
                                                      IPv6Network('::/0'),  IPv6Address('::') ]
   ],
   'site_nodes' : [
      #[ 100, 1, u'smörgåstårta' ],
      #[ 101, 2, u'knäckebröd'   ]
   ] }

      #[ 100, 1, u'lutefisk'     ],
      #[ 101, 2, u'pinnekjøtt'   ],
      #[ 102, 3, u'ribbe'        ],
      #[ 103, 4, u'laks'         ],
      #[ 104, 5, u'torsk'        ],
      #[ 105, 6, u'tørrfisk'     ],
      #[ 106, 7, u'rekesmørbrød' ],
      #[ 107, 8, u'brunost'      ]

]


# ###### Remove site ########################################################
def removeSite(site):
   if site == None:
      fullSiteList = fetchNorNetSiteList()
      if fullSiteList != None:
         for siteIndex in fullSiteList:
            site = fullSiteList[siteIndex]
            removeNorNetSite(site['site_long_name'])
   else:
      siteName = makeNameFromUnicode(site['site_long_name'], False)['ascii']
      removeNorNetSite(siteName)


# ###### Add site ###########################################################
def makeSite(site, norNetInformation, ntpServers):
   # ====== Add tag types ===================================================
   makeNorNetTagTypes()

   # ====== Make site ========================================================
   siteIndex = site['site_index']

   newSite = makeNorNetSite(site['site_long_name'], site['site_short_name'], site['site_enabled'], str.lower(site['site_short_name']),
                            site['site_url'], site['site_domain'], siteIndex,
                            site['site_city'], site['site_province'], site['site_country'], site['site_country_code'],
                            site['site_latitude'], site['site_longitude'], site['site_altitude'],
                            site['site_providers'],
                            site['site_providers'][0][0], site['site_nornet_if'],
                            ntpServers)
   newPCU = makeNorNetPCU(newSite, 'pcu', site['site_domain'],
                          site['site_pcu'][0], site['site_pcu'][1], site['site_pcu'][2],
                          'ssh', 'Amiga 5099', 'Jeg vet ikke.')

   # ====== Make nodes ======================================================
   i = 100
   for node in site['site_nodes']:
      address = node[0]
      if address <= 0:
         address = i
      port = node[1]
      if port <= 0:
        port = i
      makeNorNetNode(newSite, node[2], address, newPCU, port, 'eth0', 'Amiga 5000', 'boot')


# ###### Make test setup ####################################################
def getBootISOs(isoDirectory):
   allNorNetNodes = fetchNorNetNodeList()
   for node in allNorNetNodes:
      nodeID   = node['node_id']
      nodeName = node['node_name']
      isoName  = os.path.normpath(os.path.join(isoDirectory, nodeName + '.iso'))
      if not os.path.exists(isoName):
         log('Downloading ' + isoName + ' ...')
         try:
            isoBase64 = getPLCServer().GetBootMedium(getPLCAuthentication(), nodeID, 'node-iso' , '', [])
            iso       = base64.b64decode(isoBase64)
            outputFile = open(isoName, 'w')
            outputFile.write(iso)
            outputFile.close()
         except:
            error('Unable to generate ' + isoName + '!')

      else:
         log('Not downloading ' + isoName + ', it already exists!')


# ###### Perform site action ################################################
def performAction(action, site):
   if ((action == 'remove') or (action == 'renew')):
      removeSite(site)
   if ((action == 'add') or (action == 'renew')):
      makeSite(site, norNetInformation, ntpServers)



# ###### Main program #######################################################
action = ''
if len(sys.argv) > 2:
   if sys.argv[1] == 'add':
      action = 'add'
   elif sys.argv[1] == 'renew':
      action = 'renew'
   elif sys.argv[1] == 'remove':
      action = 'remove'
   elif sys.argv[1] == 'manage':
      action = 'manage'
if action == '':
   error('Usage: ' + sys.argv[0] + ' add|renew|remove|manage Site|ALL [Site] ... [--user=user_name] [--slice=slice_name]')


log('***** Welcome to NorNet! *****')
loginToPLC()


# ====== Some server settings ===============================================
norNetInformation = getNorNetInformationForAddress(getPLCAddress())
ntpServerNames = [ 'ntp1.ptb.de', 'ntp2.ptb.de', 'ntp3.ptb.de',   # The PTB servers (very reliable sources)
                   'ntp1.uio.no', 'ntp2.uio.no' ]                 # UiO (nearby)

ntpServers = []
for ntpServer in ntpServerNames:
   ntpAddress = resolveHostname(ntpServer, AF_INET6)
   if ntpAddress != None:
      ntpServers.append(ntpAddress)
   ntpAddress = resolveHostname(ntpServer, AF_INET)
   if ntpAddress != None:
      ntpServers.append(ntpAddress)
# ===========================================================================


# ====== Add tag types ======================================================
if ((action == 'add') or (action == 'renew')):
   makeNorNetTagTypes()


# ====== Remove or create sites =============================================
if str.upper(sys.argv[2]) == 'ALL':
   if ((action == 'remove') or (action == 'renew')):
      removeSite(None)
   if action != 'remove':
      for site in norNetSetup:
         performAction(action, site)
   i = 3
else:
   i = 2

userID       = 0
sliceID      = 0
isoDirectory = None
while i < len(sys.argv):
   match = re.search('^--([a-z]*)=(.*)', sys.argv[i])
   if ((match != None) and (match.group(1) == 'user')):
      userName = match.group(2)
      userID   = lookupPersonID(userName)
      if userID == 0:
         error('Unable to find user ' + userName + '\n')

   elif ((match != None) and (match.group(1) == 'slice')):
      sliceName = match.group(2)
      sliceID   = lookupSliceID(sliceName)
      if sliceID == 0:
         error('Unable to find slice ' + sliceName + '\n')

   elif ((match != None) and (match.group(1) == 'isodirectory')):
      isoDirectory = match.group(2)

   else:
      found = None
      for site in norNetSetup:
         if ((site['site_long_name'] == sys.argv[i]) or
             (site['site_short_name'] == sys.argv[i])):
            found = site
            break
      if found == None:
         error('Site "' + sys.argv[i] + '" is not defined!')
      performAction(action, found)

   i = i + 1


# ====== Set user ===========================================================
if userID != 0:
   log('Adding user to all sites ...')
   # ====== Add user to all sites ===========================================
   allNorNetSites = fetchNorNetSiteList(False)
   for siteIndex in allNorNetSites:
      site = allNorNetSites[siteIndex]
      getPLCServer().AddPersonToSite(getPLCAuthentication(), userID, site['site_id'])
      if site['site_id'] == NorNet_SiteIndex_Central:
         getPLCServer().SetPersonPrimarySite(getPLCAuthentication(), userID, site['site_id'])

# ====== Set slice ==========================================================
if sliceID != 0:
   log('Adding slice to all nodes ...')
   # ====== Add slice to all nodes ==========================================
   nodeIDs = []
   allNorNetNodes = fetchNorNetNodeList()
   for node in allNorNetNodes:
      nodeIDs.append(int(node['node_id']))
   getPLCServer().AddSliceToNodes(getPLCAuthentication(), sliceID, nodeIDs)

# ====== Get boot ISOs ======================================================
if isoDirectory != None:
   getBootISOs(isoDirectory)
