#!/bin/bash
#
# FreeBSD VM Preparation Script
# Copyright (C) 2015-2019 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no
#

if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 [user@host]"
   exit 1
fi

KEYDIR=~/.ssh
KEY=id_dsa.pub
VM="$1"

scp -o PreferredAuthentications=keyboard-interactive nornetapi-constants System-Maintenance System-Info Server-Setup Make-Server-Configuration FreeBSD/profile $KEYDIR/$KEY $1:

cmd="mkdir -p .ssh ; chmod 700 .ssh ; cat $KEY >>.ssh/authorized_keys ; rm -f $KEY ; sudo mkdir -p /etc/nornet/ ; sudo mv nornetapi-constants /etc/nornet/ ; mv profile .profile"
ssh -t -o PreferredAuthentications=keyboard-interactive $1 "$cmd"
