#!/bin/bash -e

SNIFFING_INTERFACE="eth1"
SNIFFING_INTERFACE_PROVIDER=255

FORWARDING_INTERFACE="tdr1"
FORWARDING_LOCAL="11.254.3.1"
FORWARDING_REMOTE="11.254.1.50"
FORWARDING_GRE_KEY="0x00030001"
FORWARDING_TTL="64"
FORWARDING_MTU="1280"

COLLECTOR_ADDRESS="192.168.3.1"


remove-sniffer ()
{
   echo "rem..."
   ip rule del iif "$FORWARDING_INTERFACE" lookup "$table" >/dev/null 2>&1 || true
   ip -4 route del "$COLLECTOR_ADDRESS/32" dev "$FORWARDING_INTERFACE" >/dev/null 2>&1 || true
   ip -6 tunnel del "$FORWARDING_INTERFACE" >/dev/null 2>&1 || true
   
   iptables -t nat -D PREROUTING -i "$SNIFFING_INTERFACE" -p tcp --dport 5060 -j DNAT --to "$COLLECTOR_ADDRESS" >/dev/null 2>&1 || true
   echo "rem OK!"
}


install-sniffer ()
{
   remove-sniffer
   ip tunnel add "$FORWARDING_INTERFACE" mode gre key "$FORWARDING_GRE_KEY" local "$FORWARDING_LOCAL" remote "$FORWARDING_REMOTE" ttl "$FORWARDING_TTL"
   ip link set dev "$FORWARDING_INTERFACE" up mtu "$FORWARDING_MTU"
   ip -4 route add "$COLLECTOR_ADDRESS/32" dev "$FORWARDING_INTERFACE"
   ip rule add iif "$FORWARDING_INTERFACE" lookup "$table"

   echo "????"
   iptables -t nat -A PREROUTING -i "$SNIFFING_INTERFACE" -p tcp --dport 5060 -j DNAT --to "$COLLECTOR_ADDRESS"
}


# NOTE: Make sure that the provider ID is right
# If changing the table scheme in Make-Tunnelbox-Configuration,
# make sure to adapt the following line, too!
let table=1000+$SNIFFING_INTERFACE_PROVIDER

install-sniffer
ip -4 route flush cache
