#!/bin/bash -e

SLICE="$1"
if [ "$SLICE" = "" ] ; then 
   SLICE="as_test"
fi

NODE="$2"
if [ "$NODE" = "" ] ; then 
   NODE="pinnekjoett.alpha.test"
fi

DELAY=15
INSTANCES=1

if ! cat /etc/planetlab/root_ssh_key.rsa >/dev/null 2>&1 ; then
   echo 2>&1 "ERROR: run as PLC root!"
   exit 1
fi


run-nodemanager ()
{
   echo "====== Running node manager ======"
   echo "ssh -i /etc/planetlab/root_ssh_key.rsa root@$NODE /usr/bin/env /usr/bin/python /usr/share/NodeManager/nodemanager.py"
   ssh -i /etc/planetlab/root_ssh_key.rsa root@$NODE "/usr/bin/env /usr/bin/python /usr/share/NodeManager/nodemanager.py >>/tmp/nodemanager-run.txt 2>&1" &
   echo "Waiting $DELAY s ..."
   sleep $DELAY
   ssh -i /etc/planetlab/root_ssh_key.rsa root@$NODE killall /usr/bin/python || return 1
   return 0
}


i=0
while [ true ] ; do
   let i=$i+1
   
   echo ""
   date
   echo "###### ROUND $i ###################################################"
   echo ""

   echo "====== Making slice ======"
   j=0
   while [ $j -lt $INSTANCES ] ; do
       sliceName="${SLICE}_${j}"
       echo "- $sliceName"
      ./Slice-Setup add --own-addresses --user=plc-root@simula.nornet --name=$sliceName >>slicetest.log
      let j=$j+1
   done
   run-nodemanager
   
   echo "====== Checking working slice ======"
   j=0
   while [ $j -lt $INSTANCES ] ; do
      sliceName="${SLICE}_${j}"
      echo "- $sliceName"
      if ssh -i /etc/planetlab/root_ssh_key.rsa $sliceName@$NODE uname -a | grep "^Linux" ; then
         echo "PASS"
      else
         ssh -i /etc/planetlab/root_ssh_key.rsa $sliceName@$NODE uname -a || true
         echo "FAIL in round $i"
         exit 1
      fi
      let j=$j+1
   done
   
   echo "====== Removing slice ======"
   j=0
   while [ $j -lt $INSTANCES ] ; do
      sliceName="${SLICE}_${j}"
      echo "- $sliceName"
      ./Slice-Setup remove --name=$sliceName >>slicetest.log
      let j=$j+1
   done
   run-nodemanager

   echo "====== Checking removed slice ======"
   j=0
   while [ $j -lt $INSTANCES ] ; do
      sliceName="${SLICE}_${j}"
      echo "- $sliceName"
      if ! ssh -i /etc/planetlab/root_ssh_key.rsa $sliceName@$NODE uname -a | grep "^Linux" ; then
         echo "PASS"
      else
         ssh -i /etc/planetlab/root_ssh_key.rsa $sliceName@$NODE uname -a || true
         echo "FAIL in round $i"
         exit 1
      fi
      let j=$j+1
   done

done
