.\" Server Setup
.\" Copyright (C) 2012-2015 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd May 21, 2015
.Dt Server-Setup 1
.Os Server-Setup
.\" ###### Name #############################################################
.Sh NAME
.Nm Server-Setup
.Nd NorNet Server Configuration Script
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm Server-Setup
FQDN
node_index
\-site site_index
\-interface interface_name
\-providers default_provider[,provider2,...]
.Op \-bridge interface_name
.Op \-controlbox
.Op \-from-current-dir
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm Server-Setup
generates and sets the server configuration for a NorNet physical machine,
based on hostname, site index, node index and NorNet interface name. It is
intended to be used on a freshly-installed server system.
.br
For all Ethernet interfaces not being the NorNet interface, the exisiting
configuration is copied (from /etc/network/interface). If no configuration
is provided, an empty configuration is generated (IP: 0.0.0.0). This sets the
corresponding interface up, without IP configuration. Then, it can be
accessed from within virtual machines running on the system.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following parameters need to be provided:
.Bl -tag -width indent
.It node_index
Provides the node index.
.It \-site site_index
Provides the site index.
.It \-interface interface_name
Provides the NorNet interface name (e.g. eth0).
.It \-providers default_provider[,provider2,...]
Provides the providers the server is conntected to. They will be configured
on the NorNet interface. Providers can be given by their name or provider
index.
.It \-bridge interface_name
Sets the NorNet interface into bridge mode. The new bridge interface's name
is given as parameter. All configuration is made with the bridge interface.
.It \-controlbox
If set, the node is a Control Box. That is, the default routes are not via
the NorNet network. In this case, static routes for just the NorNet address
range are configured instead of using default routes.
.It \-from-current-dir
If set, System-Setup looks for scripts in the current directory rather than
in the system installation paths. This is useful for using System-Setup
without installing it or for using a different version.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It Server-Setup isbjoern.unis.nornet 254 \-site 8 \-interface eth0 \-providers Uninett,Telenor
.It Server-Setup queenstown.simula.nornet 200 \-site 1 \-interface p16p1 \-providers Uninett,Kvantel,PowerTech,Telenor
.It Server-Setup midtstuen.simula.nornet 16 \-site 1 \-interface eth0 \-providers Uninett,Kvantel,PowerTech,Telenor \-bridge br0
.El
