#!/bin/sh -e
#
# Show all virtual systems
# Copyright (C) 2013 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


######### KVM
# virsh list --all
show ()
{
if [ $@ = "vbox" ] ;  then
    VBoxManage list vms 2>&1 | grep "^\"" | sed -e "s/ {.*}$//g" -e "s/^\"//g" -e "s/\"$//g"
elif [ $@ = "kvm" ] ;  then
    virsh list --all | sed -e '1,/^-*/d' | sed '/^$/d' | awk '{print $2}'
fi
}



# ###### Main program #######################################################
NORNET_DIRECTORY="/etc/nornet"


# ====== Get NorNet user name ===============================================
if [ -e $NORNET_DIRECTORY/nornetapi-config ] ; then
   . $NORNET_DIRECTORY/nornetapi-config
elif [ -e ./nornetapi-config ] ; then  
   . ./nornetapi-config
fi
if [ "$NorNet_LocalNode_Vplatform" = "kvm" ] ; then
   Vplatform="kvm"
elif [ "$NorNet_LocalNode_Vplatform" = "vbox" ] ; then
   Vplatform="vbox"
fi
show $Vplatform

