#!/bin/bash -e
#
# Start virtual system
# Copyright (C) 2013 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


# ###### Main program #######################################################
if [ $# -lt 1 ] ; then
   echo >&2 "Usage: $0 VM_name [start_delay num_cpus memory gethosttime_disabled vnc_port vnc_password options]"
   exit 1
fi

NORNET_DIRECTORY="/etc/nornet"


# ====== Get NorNet user name ===============================================
if [ -e $NORNET_DIRECTORY/nornetapi-config ] ; then
   . $NORNET_DIRECTORY/nornetapi-config
elif [ -e ./nornetapi-config ] ; then
   . ./nornetapi-config
fi
if [ "$NorNet_LocalNode_NorNetUser" = "" ] ; then
   NorNet_LocalNode_NorNetUser="nornetpp"
fi
if [ "$NorNet_Server_DefaultVNCPassword" = "" ] ; then
   NorNet_Server_DefaultVNCPassword="Access4Me"
fi


# ====== Obtain machine status ==============================================
NAME="$1"
STARTDELAY="$2"
NUMCPUS=$3
MEMORY=$4
GETHOSTTIMEDISABLED=$5
VNCPORT=$6
VNCPASSWORD="$7"
OPTIONS="$8"
if [ "$VNCPASSWORD" = "" ] ; then
   VNCPASSWORD="$NorNet_Server_DefaultVNCPassword"
fi
if [ "$OPTIONS" = "default" ] ; then
   OPTIONS="--audio none --mouse ps2 --keyboard ps2 --usb off --hpet on --pae on --hwvirtex on --nestedpaging on --largepages on --hwvirtexexcl on --vtxvpid on --nictype1 82545EM --nictype2 82545EM --nictype3 82545EM --nictype4 82545EM"
fi

if [ `Check-VSystem "$NAME"` != "running" ] ; then
   # ====== Set options =====================================================
   echo "`env LANG=C date +%FT%H:%M:%S`: Starting $NAME"
   if [ "$NUMCPUS" != "" ] ; then
      sudo -u $NorNet_LocalNode_NorNetUser VBoxManage modifyvm "$NAME" --cpus "$NUMCPUS" || true
   fi
   if [ "$MEMORY" != "" ] ; then
      sudo -u $NorNet_LocalNode_NorNetUser VBoxManage modifyvm "$NAME" --memory "$MEMORY" || true
   fi
   if [ "$OPTIONS" != "" ] ; then
      sudo -u $NorNet_LocalNode_NorNetUser VBoxManage modifyvm "$NAME" $OPTIONS || true
   fi
   if [ "$GETHOSTTIMEDISABLED" != "" ] ; then
      sudo -u $NorNet_LocalNode_NorNetUser VBoxManage setextradata "$NAME" "VBoxInternal/Devices/VMMDev/0/Config/GetHostTimeDisabled" $GETHOSTTIMEDISABLED || true
   fi

   # ====== Set VNC options =================================================
   vncOptions=
   if [ "$VNCPORT" != "" ] ; then
      if [ $VNCPORT -ne 0 ] ; then
         version=( `VBoxManage --version | tr '.' ' '` )
         # echo "`env LANG=C date +%FT%H:%M:%S`: VirtualBox version is ${version[0]}.${version[1]}"
         if [ ${version[0]} -eq 4 -a ${version[1]} -lt 2 ] ; then
            vncOptions="--vrde off --vnc --vncport $VNCPORT"
            if [ "$VNCPASSWORD" != "" ] ; then
               vncOptions="$vncOptions --vncpass \"$VNCPASSWORD\""
            fi
         else
            sudo -u $NorNet_LocalNode_NorNetUser VBoxManage setproperty vrdeextpack VNC
            sudo -u $NorNet_LocalNode_NorNetUser VBoxManage modifyvm "$NAME" \
               --vrdeproperty "VNCPassword=$VNCPASSWORD" \
               --vrdeauthlibrary null \
               --vrdeport=$VNCPORT
         fi
      fi
   fi

   # ====== Start the virtual system ========================================
   touch "/var/log/nornet-server-$NAME.log"
   touch "/var/run/nornet-server-$NAME.pid"
   chown $NorNet_LocalNode_NorNetUser:$NorNet_LocalNode_NorNetUser "/var/log/nornet-server-$NAME.log" "/var/run/nornet-server-$NAME.pid"
   # Note: The "permission denied" error is a false positive from libjpeg-turbo8. Bug #1014487 and #1031718 => filtering it out!"
   sudo -u $NorNet_LocalNode_NorNetUser /bin/sh -c \
      "nohup </dev/null VBoxHeadless --startvm \"$NAME\" $vncOptions >\"/var/log/nornet-server-$NAME.log\" 2>&1 & echo \$! >\"/var/run/nornet-server-$NAME.pid\" 2>&1" || true
      
   # ====== Give the system time to boot ====================================
   if [ "$STARTDELAY" != "" ] ; then
      echo "`env LANG=C date +%FT%H:%M:%S`: Waiting $STARTDELAY seconds ..."
      sleep "$STARTDELAY"
   fi
   
else
   echo "`env LANG=C date +%FT%H:%M:%S`: $NAME is already running -> okay."
fi
