#!/bin/bash -e

# Fixes
echo -e "\x1b[34m`date +%FT%H:%M:%S`: Applying package fixes, if necessary ...\x1b[0m"
sudo DEBIAN_FRONTEND=noninteractive dpkg --configure -a  >/tmp/install.log 2>&1 &
wait
cat /tmp/install.log

# Update package repositories
echo -e "\x1b[34m`date +%FT%H:%M:%S`: Updating package repositories ...\x1b[0m"
sudo DEBIAN_FRONTEND=noninteractive apt-get update -qq

# Fixes
echo -e "\x1b[34m`date +%FT%H:%M:%S`: Installing missing dependencies, if necessary ...\x1b[0m"
sudo DEBIAN_FRONTEND=noninteractive nohup apt-get install -f -y -q  >/tmp/install.log 2>&1 &
wait
cat /tmp/install.log

# Remove obsolete kernel packages
echo -e "\x1b[34m`date +%FT%H:%M:%S`: Removing obsolete kernels ...\x1b[0m"
ktype=$(uname -r | sed 's/.*-\(generic\|i386\|server\|common\|rt\|xen\|ec2\)/\1/')
sudo DEBIAN_FRONTEND=noninteractive nohup apt-get remove -y -qq --purge 'linux-(headers|image)-.*' linux-headers-$(uname -r)+ linux-headers-$(uname -r | sed s/-$ktype//)+ linux-headers-$ktype+ linux-image-$(uname -r)+ linux-image-$ktype+ linux-$ktype+ >/tmp/install.log 2>&1 &
wait
cat /tmp/install.log

# System update
echo -e "\x1b[34m`date +%FT%H:%M:%S`: Installing updates ...\x1b[0m"
sudo DEBIAN_FRONTEND=noninteractive nohup apt-get dist-upgrade -y -q >/tmp/install.log 2>&1 &
wait
cat /tmp/install.log

echo -e "\x1b[34m`date +%FT%H:%M:%S`: Cleaning up ...\x1b[0m"
sudo DEBIAN_FRONTEND=noninteractive apt-get autoremove -y -q >/tmp/install.log 2>&1 &
wait
cat /tmp/install.log
sudo DEBIAN_FRONTEND=noninteractive apt-get clean

# Cache updates
echo -e "\x1b[34m`date +%FT%H:%M:%S`: Updating caches ...\x1b[0m"
if [ -e /usr/bin/apt-file ] ; then
   sudo /usr/bin/apt-file update >/dev/null
fi
sudo updatedb

if [ -e /usr/bin/apt-show-versions ] ; then
   echo "====== Installed NorNet Software ============================================="
   /usr/bin/apt-show-versions | grep "^nornet-"   
   echo "=============================================================================="
fi
