#!/bin/bash
#
# Print system information
# Copyright (C) 2013 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


# ###### Main program #######################################################
echo ""
echo "   System information as of `env LANG=en date`"
echo ""


# ====== Get system information =============================================
hostnameResult=`hostname --fqdn`
uptimeResult=`env LANG=en uptime`

cpu=`uname -m`
kernel=`uname -r`

cores=$(grep -c ^processor /proc/cpuinfo 2>/dev/null)
[ "$cores" -eq "0" ] && cores=1
systemLoad=`echo "$uptimeResult" | awk -F 'average:' '{ print $2 }'`

uuptime="uptimeResult"
if $(echo $ruptime | grep -E "min|days" >/dev/null); then
   uptime=`echo "$uptimeResult" | awk '{ print $3 $4 }'`
else
   uptime=`echo "$uptimeResult" | awk '{ print $3 " hours" }'`
fi

processes=`ps axue | grep -vE "^USER|grep|ps" | wc -l`
users=`who | awk ' { print $1 }' | sort -ud | wc -l`

memoryUsed=`env LANG=en free -mto | grep Mem: | awk '{ print $3 }'  | xargs printf "%5d"`
memoryFree=`env LANG=en free -mto | grep Mem: | awk '{ print $4 }'  | xargs printf "%5d"`
memoryTotal=`env LANG=en free -mto | grep Mem: | awk '{ print $2 }' | xargs printf "%5d"`
swapUsed=`env LANG=en free -mto | grep Swap | awk '{ print $3 }'    | xargs printf "%5d"`
swapFree=`env LANG=en free -mto | grep Swap: | awk '{ print $4 }'   | xargs printf "%5d"`
swapTotal=`env LANG=en free -mto | grep Swap: | awk '{ print $2 }'  | xargs printf "%5d"`

DISTRIB_ID="Unknown"
DISTRIB_RELEASE="00.00"
DISTRIB_CODENAME="unknown"
if [ -e /etc/lsb-release ] ; then
   . /etc/lsb-release 
fi


# ====== Print system information ===========================================

echo -en "\x1b[1;34m"
echo "   ====================================================="
echo -en "\x1b[1;31m"
echo "      #     #                 #     #"
echo "      ##    #   ####   #####  ##    #  ######   #####"
echo "      # #   #  #    #  #    # # #   #  #          #"
echo "      #  #  #  #    #  #    # #  #  #  #####      #"
echo "      #   # #  #    #  #####  #   # #  #          #"
echo "      #    ##  #    #  #   #  #    ##  #          #"
echo "      #     #   ####   #    # #     #  ######     #"
echo -en "\x1b[1;34m"
echo "   ====================================================="
echo -e "\x1b[0m"

echo "Host:          ${hostnameResult}"
echo "Uptime:        ${uptime}"
echo ""
echo "CPU:           $cores × ${cpu}"
echo "System Load:   ${systemLoad}"
echo "Processes:     ${processes}"
echo "Users:         ${users}"
echo "Used Memory:   ${memoryUsed} MiB of ${memoryTotal} MiB (${memoryUsed} MiB free)"
echo "Used Swap:     ${swapUsed} MiB of ${swapTotal} MiB (${swapUsed} MiB free)"

echo ""
echo "Kernel:        ${kernel}"
echo "System:        ${DISTRIB_ID} ${DISTRIB_RELEASE} (${DISTRIB_CODENAME})"
echo ""
