#!/usr/bin/python
# -*- coding: utf-8 -*-

import hashlib;


# ###### Filter for text ####################################################
def filterForText(s):
   return filter(lambda x: x in '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz \t', s)


print filterForText("This is key söpgjdsögdjgdsösjgdögdsjgdsök")
