#!/usr/bin/python
# -*- coding: utf-8 -*-

from NorNetTools         import *;
from NorNetConfiguration import *;


print removeComment('"ilo-åklungen"       "HP DL-320"  "iLO on Physical Server #1"')
print removeComment('\'"ilo-åklungen"       "HP DL-320"  "iLO on Physical Server #1"\'')

print removeComment('"ilo-åklungen"       "HP DL-320"  "iLO on Physical Server #1" # bla')
print removeComment('\'"ilo-åklungen"       "HP DL-320"  "iLO on Physical Server #1"\' # bla bla')

print removeComment('"ilo-åklungen"       "HP DL-320"  "iLO on Physical Server #1" # bla """"')
print removeComment('\'"ilo-åklungen"       "HP DL-320"  "iLO on Physical Server #1"\' # bla bla \'"\'')
