#!/bin/bash

echo "TEST" >a
echo "TES2T" >b


# ###### Check whether file needs an update #################################
needs-update ()
{
   if [ ! -e "$2" ] ; then
      # Target does not exist => update needed!
      return 0
   fi
   if ! diff -q "$1" "$2" ; then
      # Target differs => update needed!
      return 0
   fi
   return 1
}


if needs-update a a ; then
   echo "differ"
else
   echo "not differ"
fi
