#!/usr/bin/env bash
#
# NTP Server Configuration Test
# Copyright (C) 2015-2019 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


ntp4=`grep "^server" /etc/ntp.conf | grep -v ':' | awk '{ print $2; }'`
ntp6=`grep "^server" /etc/ntp.conf | grep ':'    | awk '{ print $2; }'`


echo "Running in parallel ..."
for ntp in $ntp4 $ntp6 ; do
   ntpdate -q $ntp >/tmp/$ntp.out 2>&1 &
done
wait
for ntp in $ntp4 $ntp6 ; do
   echo -e "\x1b[32m----- $ntp -----\x1b[0m"
   cat /tmp/$ntp.out
   rm -f /tmp/$ntp.out
done
