.\" Tunnelbox Setup
.\" Copyright (C) 2012-2023 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd May 28, 2013
.Dt Tunnelbox-Setup 1
.Os Tunnelbox-Setup
.\" ###### Name #############################################################
.Sh NAME
.Nm Tunnelbox-Setup
.Nd NorNet Tunnelbox Setup Script
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm Tunnelbox-Setup
start|stop|status|reset|coldstart
.Op -providers list_of_providers
.Op -interfaces list_of_interfaces
.Op -event event_information
.Op -bootstrap
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm Tunnelbox-Setup
is the service configuration script for the NorNet tunnelbox device. It
configures, reconfigures and unconfigures the tunnels, according to the
provider-specific scripts generated by Make-Tunnelbox-Configuration.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following options are available:
.Bl -tag -width indent
.It start|stop|restart|status|reset|coldstart
This parameter specifies the action to be taken, i.e. start (set up the
tunnels), stop (tear down the tunnels), restart (stop and start again),
status (test the tunnels), reset (stop and flush of NAT table and ip rules;
for debugging purposes), coldstart (reset and start; for debugging purposes).
.It -providers list_of_providers
This option restricts the action to the given list of providers
(comma-separated, no spaces allowed). This list must be a subset of the
providers available at the tunnelbox.
.br
Use "@ALL" to select all providers. By default, NO providers are selected!
.It -interfaces list_of_interfaces
Alternatively, instead of specifying providers, it is possible to specify
the corresponding interfaces with this option.
.It -event event_information
This parameter adds the given event information to the log output. For
example, the event information could contain a string like "interface xyz
comes up" when the corresponding interface becomes active and triggers a
tunnelbox reconfiguration.
.It -bootstrap
Only apply the bootstrap configuration, i.e. create a tunnel via the default
provider to the Central Site.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It Tunnelbox-Setup
.El
