#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Update node state
# Copyright (C) 2017-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# NorNet
from NorNetAPI import *


# ###### Main program #######################################################
if len(sys.argv) != 3:
   error('Usage: ' + sys.argv[0] + ' [node] [state]')

nodeName  = sys.argv[1]
bootState = sys.argv[2]

loginToPLC()

getPLCServer().UpdateNode(getPLCAuthentication(),
                          nodeName, { 'boot_state' : bootState })
