#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# User Setup
# Copyright (C) 2012-2016 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

import re
import os

# NorNet
from NorNetTools         import *
from NorNetAPI           import *
from NorNetProviderSetup import *
from NorNetSiteSetup     import *


# ###### Main program #######################################################
action = ''
if len(sys.argv) > 2:
   if sys.argv[1] == 'add':
      action = 'add'
   elif sys.argv[1] == 'renew':
      action = 'renew'
   elif sys.argv[1] == 'remove':
      action = 'remove'
if action == '':
   error('Usage: ' + sys.argv[0] + ' add|renew|remove [--user=User] [--site=Site] [--password=Password] [--firstname=Name] [--lastname=Name] [--phone=Phone] [--url=URL] [--publickey=Key] [--admin] [--pi] [--tech] [--user]')


userName  = None
siteName  = None
password  = makeUnixPassword('top-secret')
publicKey = None
title     = ''
firstName = 'Ola'
lastName  = 'Nordmann'
phone     = ''
url       = 'https://www.nntb.no'
roles     = [ ]

i = 2
while i < len(sys.argv):
   match = re.search('^--([a-z]*)=(.*)', sys.argv[i])
   if match != None:
      if match.group(1) == 'user':
         userName = match.group(2)
      elif match.group(1) == 'site':
         siteName = match.group(2)
      elif match.group(1) == 'title':
         title = match.group(2)
      elif match.group(1) == 'firstname':
         firstName = match.group(2)
      elif match.group(1) == 'lastname':
         lastName = match.group(2)
      elif match.group(1) == 'phone':
         phone = match.group(2)
      elif match.group(1) == 'url':
         url = match.group(2)
      elif match.group(1) == 'password':
         password = match.group(2)
      elif match.group(1) == 'publickey':
         publicKey = match.group(2)
      else:
        error('Invalid option parameter: ' + sys.argv[i])
   else:
     if sys.argv[i] == '--admin':
        roles.append('admin')
     elif sys.argv[i] == '--pi':
        roles.append('pi')
     elif sys.argv[i] == '--tech':
        roles.append('tech')
     elif sys.argv[i] == '--user':
        roles.append('user')
     else:
        error('Invalid role parameter: ' + sys.argv[i])

   i = i + 1


log('***** Welcome to NorNet! *****')
loginToPLC()


if ((action == 'remove') or (action == 'renew')):
   userID = lookupPersonID(userName)
   if userID != 0:
      removeNorNetUser(userName)

if ((action == 'add') or (action == 'renew')):

   if siteName != None:
      site = fetchNorNetSite(siteName, False)
      if site == None:
         error('Cannot find site ' + siteName)
   else:
      site = None

   makeNorNetUser(userName, password, site, title, firstName, lastName, phone, url, publicKey, roles)
