.\" NorNet Watchdog
.\" Copyright (C) 2019 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd January 30, 2013
.Dt Watchdog 1
.Os Watchdog
.\" ###### Name #############################################################
.Sh NAME
.Nm Watchdog
.Nd NorNet Watchdog
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm Watchdog
configuration_file
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm Watchdog
runs a given check program to check for correct operation (e.g. network
connectivity). If the check fails, a failure counter is increased. If it
reaches a configured threshold, a configured action is taken.
.br
All configuration is made in the given configuration file. It provides the
following options:
.Bl -tag -width indent
.It WATCHDOG_FAILCOUNT_FILE="watchdog-failcount-file"
Sets a file name for the failure counter file.
.It WATCHDOG_COMMAND="some-command"
Sets a command for the operation check. If the check is successful, the
failure counter is reset (by deleting the failure counter file).
.It WATCHDOG_MAXFAILURES="number"
Sets the threshold for the number of failures after which an action is taken.
.It WATCHDOG_FAILURE_ACTION='some-action'
Sets the action to be taken (e.g. reset a service) when the failure counter
reaches the threshold. The failure action is performed only once!
.It WATCHDOG_FAILURE_FINAL='some-action'
If the check fails again after the failure action has been performed, the
given final action (e.g. reset the whole machine) is taken.
.It WATCHDOG_LOOPMODE=0|1
If WATCHDOG_LOOPMODE=1, the failure counter is reset after calling
WATCHDOG_FAILURE_ACTION. That is, it starts counting from 0 again.
.El
.Pp
.\" .\" ###### Arguments ########################################################
.\" .Sh ARGUMENTS
.\" The following options are available:
.\" .Bl -tag -width indent
.\" .It xxx
.\" xxx
.\" .El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It Watchdog /etc/nornet/watchdog-config
.El
