#!/bin/sh -e

# Include the GRUB helper library for grub-mkconfig.
. /usr/lib/grub/grub-mkconfig_lib

# We want to work in /boot/grub/ only.
test -d /boot/grub; cd /boot/grub

# ====== NorNet theme =======================================================
echo >&2 "Using NorNet Tunnelbox theme!"

echo "insmod jpeg"   # Load JPEG reader!
echo "if background_image `make_system_path_relative_to_its_root "/boot/Splash-Tunnelbox1-1024x768.jpeg"`; then"
echo "   set menu_color_normal=red/black"
echo "   set menu_color_highlight=blue/red"
echo "   set color_normal=red/black"
echo "fi"
