#!/bin/bash -e
#
# MPTCP Test
# Copyright (C) 2014 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


if [ $# -lt 3 ] ; then
   echo >&2 "Usage: $0 [slice] [node] [provider_index_1] ..."
   exit 1
fi

BASE_PORT=9000

SLICE="$1"
NODE="$2"
shift ; shift

commands="hostname"
while [ "$1" != "" ] ; do
   ISP="$1"

   let port=$BASE_PORT+10*$ISP

   commands="$commands && nohup netperfmeter $port -local=

   shift
done
