#!/bin/sh

./User-Setup add --user=dreibh@simula.no --firstname=Thomas --lastname=Dreibholz "--title=Priv.-Doz. Dr." --pi --tech --password=kpl07


# *After* adding the Slice!
./NorNet-Setup manage ALL --user=dreibh@simula.no --slice=srl_test
