#!/bin/sh

./User-Setup add --user=dreibh@simula.no --firstname=Thomas --lastname=Dreibholz "--title=Priv.-Doz. Dr." --pi --tech --user --password=set-a-password-here "--url=https://www.nntb.no"
./User-Setup add --user=dummy@simula.nornet --firstname=Ola --lastname=Nordmann "--site=NorNet Testbed Central" --tech --user --password=dummy-password "--url=https://www.nntb.no"

# Add "tech" user:
./NorNet-Setup manage ALL --user=dummy@simula.nornet

# *After* adding the Slice!
./NorNet-Setup manage ALL --user=dreibh@simula.no --slice=srl_test
