#!/bin/bash -e
#
# Debian Packaging Scripts
# Copyright (C) 2002-2017 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de

if [ $# -ne 1 ] ; then
   echo >&2 "Usage: $0 [cfengine source directory]"
   exit 1
fi
CFENGINE_DIRECTORY="$1"
if [ ! -e "$CFENGINE_DIRECTORY" ] ; then
   echo >&2 "ERROR: Directory $CFENGINE_DIRECTORY does not exist!"
   exit 1
fi

cp make-deb clean-deb build-deb debian.conf filter-empty-entries renew-debian-changelog make-ppa "$CFENGINE_DIRECTORY"
rm -rf "$CFENGINE_DIRECTORY/debian"
cp -r debian "$CFENGINE_DIRECTORY/debian"
