#!/bin/bash -e
#
# NorNet CA Setup
# Copyright (C) 2015-2016 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no


SERVER_DIRECTORY=NorNet-Servers   # <-- where to place server certificates
CA_DIRECTORY=NorNet-CAs           # <-- where to place CAs
CA_KEYLEN=2048
CERT_KEYLEN=$(($CA_KEYLEN/2))

CA_DAYS=3650     # 10 years
CERT_DAYS=1825   # 5 years

SUBJECTHEADER_SRL="/C=NO/ST=Akershus/L=Fornebu/O=Simula Research Laboratory/OU=Centre for Resilient Networks and Applications"
SUBJECTHEADER_UDE="/C=DE/ST=Nordrhein-Westfalen/L=Essen/O=Universität Duisburg-Essen/OU=Institut für Experimentelle Mathematik"


# ###### Make a CA ##########################################################
make-ca ()
{
   EXTENSION="$1"
   UPPERLEVEL="$2"
   NAME="$3"
   SUBJECT="$4"

   echo ""
   echo -e "\x1b[34m###### Creating Certification Authority: $NAME ######\x1b[0m"
   echo ""

   mkdir -p -m 0700 \
      $CA_DIRECTORY/$NAME \
      $CA_DIRECTORY/$NAME/certs \
      $CA_DIRECTORY/$NAME/crl \
      $CA_DIRECTORY/$NAME/csr \
      $CA_DIRECTORY/$NAME/newcerts \
      $CA_DIRECTORY/$NAME/private \
      $CA_DIRECTORY/$NAME/chains
   if [ ! -e $CA_DIRECTORY/$NAME/index.txt ] ; then
      touch $CA_DIRECTORY/$NAME/index.txt
   fi
   if [ ! -e $CA_DIRECTORY/$NAME/serial ] ; then
      echo "1000" >$CA_DIRECTORY/$NAME/serial
   fi

   # ====== Create key ======================================================
   if [ -e $CA_DIRECTORY/$NAME/private/$NAME.key ] ; then
      echo >&2 "ERROR: Key $CA_DIRECTORY/$NAME/private/$NAME.key already exists!"
      exit 1
   fi
   if [ ! -e $NAME.password ] ; then
      echo >&2 "ERROR: Key $NAME.password does not exist!"
      echo >&2 "Create this file containing the password on the first line!"
      exit 1
   fi
   echo "- Creating key for $NAME"
   openssl genrsa -aes256 \
      -passout file:$NAME.password \
      -out $CA_DIRECTORY/$NAME/private/$NAME.key \
      $CA_KEYLEN 2>/dev/null

   if [ "$UPPERLEVEL" = "root" ] ; then
      # ====== Create top-level certificate =================================
      openssl req -utf8 -new -days $CA_DAYS \
         -x509 \
         -config $NAME.config -extensions $EXTENSION \
         -key $CA_DIRECTORY/$NAME/private/$NAME.key \
         -passin file:$NAME.password \
         -out $CA_DIRECTORY/$NAME/certs/$NAME.crt -outform PEM \
         -subj "$SUBJECT"
   else
      # ====== Create signed certificate ====================================
      echo "- Creating CSR for $NAME"
      openssl req -utf8 -new \
         -key $CA_DIRECTORY/$NAME/private/$NAME.key \
         -passin file:$NAME.password \
         -out $CA_DIRECTORY/$NAME/certs/$NAME.csr -days $CA_DAYS \
         -config $NAME.config -extensions $EXTENSION \
         -subj "$SUBJECT"

      echo "- Letting $UPPERLEVEL issue CRT for $NAME"

      openssl ca -days $CERT_DAYS -batch -notext \
         -config $UPPERLEVEL.config -extensions $EXTENSION \
         -cert $CA_DIRECTORY/$UPPERLEVEL/certs/$UPPERLEVEL.crt \
         -keyfile $CA_DIRECTORY/$UPPERLEVEL/private/$UPPERLEVEL.key \
         -passin file:$UPPERLEVEL.password \
         -in $CA_DIRECTORY/$NAME/certs/$NAME.csr \
         -out $CA_DIRECTORY/$NAME/certs/$NAME.crt \
         -subj "$SUBJECT"
   fi

   # ====== Write chain file ================================================
   echo "- Writing chain to $NAME"
   if [ "$UPPERLEVEL" = "root" ] ; then
      cp $CA_DIRECTORY/$NAME/certs/$NAME.crt $CA_DIRECTORY/$NAME/chains/$NAME-chain.pem
      openssl verify -verbose -CAfile $CA_DIRECTORY/$NAME/chains/$NAME-chain.pem $CA_DIRECTORY/$NAME/certs/$NAME.crt
   else
      (
         cat $CA_DIRECTORY/$UPPERLEVEL/chains/$UPPERLEVEL-chain.pem
         cat $CA_DIRECTORY/$NAME/certs/$NAME.crt
      ) >$CA_DIRECTORY/$NAME/chains/$NAME-chain.pem
      openssl verify -CAfile $CA_DIRECTORY/$UPPERLEVEL/chains/$UPPERLEVEL-chain.pem $CA_DIRECTORY/$NAME/certs/$NAME.crt
   fi
}


# ###### Make a server certificate ##########################################
make-certificate ()
{
   UPPERLEVEL="$1"
   NAME="$2"
   SUBJECT="$3"
   ALTNAME="$4"

   echo ""
   echo -e "\x1b[34m###### Creating Certificate: $NAME ######\x1b[0m"
   echo ""

   mkdir -p -m 0700 $SERVER_DIRECTORY/$NAME
   if [ -e $SERVER_DIRECTORY/$NAME.key ] ; then
      echo >&2 "ERROR: Key $SERVER_DIRECTORY/$NAME/$NAME.key already exists!"
      exit 1
   fi

   # ====== Create key ======================================================
   openssl genrsa -out $SERVER_DIRECTORY/$NAME/$NAME.key $CERT_KEYLEN 2>/dev/null

   # ====== Create server certificate =======================================
   (
      echo "[req]"
      echo "distinguished_name = SAN"
      echo "[SAN]"
      echo "basicConstraints = CA:FALSE"
      echo "keyUsage         = nonRepudiation,digitalSignature,keyEncipherment"
      if [ "$ALTNAME" != "" ] ; then
         echo "subjectAltName   = $ALTNAME"
      fi
   ) >$NAME.config

   openssl req -new \
      -key $SERVER_DIRECTORY/$NAME/$NAME.key \
      -out $SERVER_DIRECTORY/$NAME/$NAME.csr -days $CERT_DAYS -outform PEM \
      -config $NAME.config -reqexts SAN \
      -subj "$SUBJECT"

   # OpenSSL would create the certificate without subjectAltName.
   # Therefore, it is necessary to specify the config file and section again:
   # -extfile ... -extensions SAN
   openssl ca \
      -config $UPPERLEVEL.config \
      -extfile $NAME.config -extensions SAN \
      -cert $CA_DIRECTORY/$UPPERLEVEL/certs/$UPPERLEVEL.crt -keyfile $CA_DIRECTORY/$UPPERLEVEL/private/$UPPERLEVEL.key \
      -batch -notext \
      -passin file:$UPPERLEVEL.password \
      -days $CERT_DAYS \
      -in $SERVER_DIRECTORY/$NAME/$NAME.csr \
      -out $CA_DIRECTORY/$UPPERLEVEL/certs/$NAME.crt \
      -subj "$SUBJECT"
   cp $CA_DIRECTORY/$UPPERLEVEL/certs/$NAME.crt $SERVER_DIRECTORY/$NAME/$NAME.crt
   openssl verify -verbose -CAfile $CA_DIRECTORY/$UPPERLEVEL/chains/$UPPERLEVEL-chain.pem $SERVER_DIRECTORY/$NAME/$NAME.crt
}


# ###### NorNet CA ##########################################################
make-ca v3_ca              root             NorNet-CA-Level1     "$SUBJECTHEADER_SRL/CN=NorNet Level-1 CA"
make-ca v3_ca              NorNet-CA-Level1 NorNet-CA-Level2     "$SUBJECTHEADER_SRL/CN=NorNet Level-2 CA"
make-ca v3_intermediate_ca NorNet-CA-Level2 NorNet-CA-Simula     "$SUBJECTHEADER_SRL/CN=*.simula.nornet"

# # make-ca v3_intermediate_ca NorNet-CA-Level2 NorNet-CA-UDE        "$SUBJECTHEADER_UDE/CN=*.ude.nornet"
#
# # make-ca v3_intermediate_ca NorNet-CA-Level2 NorNet-CA-Test       "$SUBJECTHEADER_SRL/CN=*.test"
# # make-ca v3_intermediate_ca NorNet-CA-Test   NorNet-CA-Test-Alpha "$SUBJECTHEADER_SRL/CN=*.alpha.test"


make-certificate NorNet-CA-Simula   monitor.simula.nornet   "$SUBJECTHEADER_SRL/CN=monitor.simula.nornet" "DNS:holmenkollen.simula.nornet"
